# Generated by Django 6.0.7 on 2026-08-09 17:59

import billing.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_wipe_and_drop_legacy_split_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="test_connect_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Connect application client ID (ca_…) for TEST mode. Used only while Testing Mode is on.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_connect_platform_publishable_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="TEST-mode Stripe publishable key (pk_test_…). Sent to the browser only while Testing Mode is on.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_connect_platform_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="TEST-mode Stripe secret key (sk_test_…). Used only while Testing Mode is on. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_connect_platform_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="TEST-mode webhook signing secret for /billing/webhooks/stripe/, from the TEST-mode webhook listener in the Stripe dashboard. Used only while Testing Mode is on. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_mode",
            field=models.BooleanField(
                default=True,
                help_text="Master mode switch. When on, all Stripe operations (charges, SetupIntents, webhooks) use the TEST key set below. Turn off to charge real cards using the LIVE key set. Toggle from the admin Payments dashboard → Stripe tab.",
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Connect application client ID (ca_…) for LIVE mode. From dashboard.stripe.com/settings/connect. Used only while Testing Mode is off.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_platform_publishable_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LIVE-mode Stripe publishable key (pk_live_…). Sent to the browser only while Testing Mode is off.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_platform_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="LIVE-mode Stripe secret key (sk_live_…). Used only while Testing Mode is off. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_platform_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="LIVE-mode webhook signing secret for the global /billing/webhooks/stripe/ endpoint. Used only while Testing Mode is off. Encrypted at rest.",
                max_length=512,
            ),
        ),
    ]
