# Generated by Django 6.0.7 on 2026-08-26 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_migrate_existing_stripe_keys_to_test_slot"),
        ("classes", "0053_alter_cmsactivity_kind"),
        ("membership", "0140_alter_admincapability_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe re_… refund id. Blank only between row-create and Stripe responding; unique when set, which makes webhook upserts idempotent.",
                        max_length=255,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField(help_text="Amount of THIS refund, in cents.")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="pending",
                        help_text="Refund lifecycle status. Card refunds usually succeed synchronously; refund.updated flips late failures.",
                        max_length=20,
                    ),
                ),
                (
                    "attempt",
                    models.PositiveIntegerField(
                        default=1, help_text="Attempt counter, bumped by Retry; feeds the fresh idempotency-key suffix."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("in_app", "Issued in app"), ("stripe_dashboard", "Issued in Stripe dashboard")],
                        default="in_app",
                        help_text="Where the refund was initiated. Reconciled dashboard refunds get 'Issued in Stripe dashboard'.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional internal note from the refund modal. The payer never sees this."
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, help_text="Stripe's failure reason, for the admin to read.", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this refund row was created.")),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped on entering SUCCEEDED or FAILED. Also the 'side effects already fired' guard: the succeeded-transition effects run exactly once.",
                        null=True,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who issued the refund in app. Null for webhook-sourced/system refunds.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orientation_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for orientation-payment refunds. Exactly one source FK is set per row.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="membership.orientationbooking",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for class-payment refunds. Exactly one source FK is set per row.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="classes.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["registration", "status"], name="idx_refund_reg_status"),
                    models.Index(fields=["orientation_booking", "status"], name="idx_refund_booking_status"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("registration__isnull", False), ("orientation_booking__isnull", True)),
                            models.Q(("registration__isnull", True), ("orientation_booking__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_refund_one_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("stripe_refund_id", ""), _negated=True),
                        fields=("stripe_refund_id",),
                        name="uq_refund_stripe_id",
                    ),
                ],
            },
        ),
    ]
