# Generated by Django 6.0.7 on 2026-08-28 01:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_paymentrefund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="class_guild_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Percent of each paid class registration that goes to the guild (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="class_instructor_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("70.00"),
                help_text="Percent of each paid class registration that goes to the instructor (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="class_pl_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Percent of each paid class registration that goes to Past Lives (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="orientation_guild_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Percent of each paid orientation that goes to the guild (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="orientation_orientator_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("70.00"),
                help_text="Percent of each paid orientation that goes to the orientator (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="orientation_pl_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Percent of each paid orientation that goes to Past Lives (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="ReconciliationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", help_text="Optional label, e.g. 'August 2026'.", max_length=255
                    ),
                ),
                ("period_start", models.DateField(help_text="First day of the window this snapshot froze.")),
                ("period_end", models.DateField(help_text="Last day of the window this snapshot froze.")),
                (
                    "results",
                    models.JSONField(
                        default=dict,
                        help_text="The frozen allocation: per-recipient totals, each guild's voting figure, and the split % in force.",
                    ),
                ),
                (
                    "grand_total_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Total net collected in the window, denormalized for the history list."
                    ),
                ),
                (
                    "is_auto",
                    models.BooleanField(
                        default=False, help_text="True when the month-end job took it; False for a manual take."
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this snapshot was taken (ordering key)."),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took the snapshot. Null for the automated month-end job.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Snapshot",
                "verbose_name_plural": "Reconciliation Snapshots",
                "ordering": ["-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("tab", "Tab"), ("class", "Class"), ("orientation", "Orientation")],
                        help_text="Which payment stream the target transaction lives in.",
                        max_length=20,
                    ),
                ),
                (
                    "source_pk",
                    models.PositiveIntegerField(
                        help_text="PK of the TabCharge / Registration / OrientationBooking being adjusted."
                    ),
                ),
                (
                    "is_omitted",
                    models.BooleanField(
                        default=False, help_text="When on, the transaction is excluded from the allocation entirely."
                    ),
                ),
                (
                    "override_percents",
                    models.JSONField(
                        blank=True,
                        help_text='Null uses the configured split. Otherwise a per-recipient percent map (e.g. {"instructor": 60, "guild": 20, "pl": 20}) whose keys match the source kind. Tab charges stay null (omit-only).',
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal note on why this transaction was adjusted. Members never see it.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this adjustment was first created."),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this adjustment was last edited.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created or last edited this adjustment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Adjustment",
                "verbose_name_plural": "Transaction Adjustments",
                "ordering": ["-updated_at"],
                "constraints": [models.UniqueConstraint(fields=("source_kind", "source_pk"), name="uq_txnadj_source")],
            },
        ),
    ]
