# Generated by Django 6.0.7 on 2026-09-25 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_billingsettings_class_guild_percent_and_more"),
        ("membership", "0180_late_cancel_fee_cents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LateCancellationFee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount_cents",
                    models.PositiveIntegerField(help_text="The fee in cents, frozen from the policy at cancel time."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        help_text="Where the fee stands: unpaid, paid, waived or refunded.",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The newest Stripe Checkout Session minted for this fee, if any.",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Stripe PaymentIntent that paid the fee; blank until it is paid.",
                        max_length=255,
                    ),
                ),
                (
                    "checkout_attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="How many Checkout Sessions have been minted; part of each session's idempotency key.",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, help_text="When Stripe confirmed the payment.", null=True),
                ),
                (
                    "waived_reason",
                    models.CharField(blank=True, default="", help_text="Why the fee was waived.", max_length=300),
                ),
                ("waived_at", models.DateTimeField(blank=True, help_text="When the fee was waived.", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the late cancel created the fee."),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who owes, or paid, the fee.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_cancellation_fees",
                        to="membership.member",
                    ),
                ),
                (
                    "orientation_booking",
                    models.OneToOneField(
                        blank=True,
                        help_text="The cancelled orientation booking this fee is for. Exactly one source is set per row.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="late_fee",
                        to="membership.orientationbooking",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The cancelled equipment reservation this fee is for. Exactly one source is set per row.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="late_fee",
                        to="membership.equipmentreservation",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who waived the fee, when it was waived.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("orientation_booking__isnull", False), ("reservation__isnull", True)),
                            models.Q(("orientation_booking__isnull", True), ("reservation__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_latefee_one_source",
                    )
                ],
            },
        ),
    ]
