# Generated by Django 6.0.7 on 2026-09-25 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0015_latecancellationfee"),
        ("classes", "0069_discountcoderequest"),
        ("membership", "0180_late_cancel_fee_cents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentrefund",
            name="ck_refund_one_source",
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="late_fee",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for late cancellation fee refunds (#456). Exactly one source FK is set per row.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="billing.latecancellationfee",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(fields=["late_fee", "status"], name="idx_refund_late_fee_status"),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("late_fee__isnull", True),
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", False),
                    ),
                    models.Q(
                        ("late_fee__isnull", True),
                        ("orientation_booking__isnull", False),
                        ("registration__isnull", True),
                    ),
                    models.Q(
                        ("late_fee__isnull", False),
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_refund_one_source",
            ),
        ),
    ]
