# Generated by Django 6.0.8 on 2026-10-07 19:41

import billing.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0016_paymentrefund_late_fee"),
        ("membership", "0210_alter_member_status_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="connect_accounts_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="LIVE-mode signing secret of the second webhook endpoint, the one Stripe scopes to Connected accounts (it delivers account.updated for instructor and orientor payouts). Same URL as the platform endpoint. Used only while Testing Mode is off. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_connect_accounts_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="TEST-mode signing secret of the Connected accounts webhook endpoint (account.updated for payouts). Used only while Testing Mode is on. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Pay instructors and orientors through Stripe (#662). Off by default; while off nobody sees the Payouts tab or its nudges and no share is sent. Charges never read this switch.",
            ),
        ),
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        help_text="The Stripe Express account (acct_...) that receives this member's shares.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        help_text="True for a live-mode Stripe account, False for one made while Testing Mode was on."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_info", "Stripe needs more info"),
                            ("active", "Payouts on"),
                            ("paused", "Paused by Stripe"),
                        ],
                        default="needs_info",
                        help_text="Where the account stands with Stripe, from the account.updated webhook or the return from signup.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the Stripe account was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last time the status was written."),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The instructor or orientor this Stripe account pays.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_accounts",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "livemode"),
                        name="payout_account_one_per_mode",
                    )
                ],
            },
        ),
    ]
