# Generated by Django 6.0.8 on 2026-10-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0017_payout_accounts"),
        ("classes", "0081_classoffering_eventbrite"),
        ("membership", "0212_merge_0211"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="payouts_on_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When payouts were first turned on. A share that fell due before it is never sent and stays owed at month end. Turning the switch off pauses sending; nothing is sent while it is off.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payoutaccount",
            name="active_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When Stripe first turned payouts on for this account. Only a share paid for after this goes through Stripe; one paid for earlier stays owed at month end.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        help_text="The share in cents: the reconciliation split when it fell due."
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        help_text="When the share fell due: 48 hours after the class or slot started, or after payment if later."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Transfer failed"),
                            ("owed_manually", "Owed at month end"),
                            ("taken_back", "Taken back"),
                            ("nothing_due", "Nothing left to send"),
                        ],
                        default="pending",
                        help_text="Where the share stands.",
                        max_length=20,
                    ),
                ),
                (
                    "owed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not owed by hand"),
                            (
                                "not_connected",
                                "Payouts were not on when this was paid for",
                            ),
                            ("not_through_stripe", "Not paid through Stripe"),
                            ("transfer_failed", "Stripe kept rejecting the transfer"),
                        ],
                        default="",
                        help_text="Why an owed share is paid by hand at month end instead of through Stripe.",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Stripe transfer (tr_...) once sent.",
                        max_length=64,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Stripe's reason for the last rejected transfer.",
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Transfer attempt number; part of the idempotency key.",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last transfer was tried.",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Stripe accepted the transfer.",
                        null=True,
                    ),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        blank=True,
                        help_text="The Stripe mode of the last transfer attempt (True live, False test, empty never attempted). Only the mode Testing Mode selects can look up, send or give up the row.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this row was made: the share fell due, or a snapshot froze it.",
                    ),
                ),
                (
                    "counted_as_stripe_in",
                    models.ForeignKey(
                        blank=True,
                        help_text="The month-end snapshot that counted this share as Sent through Stripe, so the finance lead did not pay it. If Stripe then rejects it, it is owed by hand at once and flagged with this snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts_counted_as_stripe",
                        to="billing.reconciliationsnapshot",
                    ),
                ),
                (
                    "orientation_booking",
                    models.OneToOneField(
                        blank=True,
                        help_text="The orientation booking this share comes from (exactly one of this and the registration).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout",
                        to="membership.orientationbooking",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        help_text="The instructor or orientor who earned the share.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="membership.member",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        help_text="The class registration this share comes from (exactly one of this and the booking).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout",
                        to="classes.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("orientation_booking__isnull", True),
                                ("registration__isnull", False),
                            ),
                            models.Q(
                                ("orientation_booking__isnull", False),
                                ("registration__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="payout_exactly_one_source",
                    )
                ],
            },
        ),
    ]
