# Generated by Django 6.0.8 on 2026-10-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_payout_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrefund",
            name="share_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No share had been sent"),
                    ("take_back", "Take the share back from the payee"),
                    ("pl_covers", "Past Lives covers it"),
                    ("not_asked", "Past Lives covers it (nobody was asked)"),
                ],
                default="",
                help_text="For a refund of a payment whose producer share was already sent through Stripe: the admin's required choice, or Not asked for a refund nobody could be asked about (Past Lives covers it).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="share_reversal_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why Stripe refused the take back; Past Lives then covers the refund and the line is flagged.",
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="share_reversed_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How much of the sent share Stripe took back from the payee for this refund.",
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="stripe_transfer_reversal_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Stripe transfer reversal (trr_...) that took it back.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="reversed_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How much of the sent share refunds took back from the payee (transfer reversals).",
            ),
        ),
    ]
