# Generated by Django 6.0.8 on 2026-10-08 15:03

import billing.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_refund_share_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingsettings",
            name="connect_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unused: an OAuth leftover nothing reads (#702); payouts use account links. Kept so the release before #702 can still read the column; remove once PLM FOG closes.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="test_connect_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unused: an OAuth leftover nothing reads (#702); payouts use account links. Kept so the release before #702 can still read the column; remove once PLM FOG closes.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="previous_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="LIVE-mode secret key (sk_live_…) of the previous Stripe account. Refunds and lookups on payments made there use it while Testing Mode is off. Leave blank when there is no previous account. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="previous_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="LIVE-mode webhook signing secret of the previous Stripe account's endpoint. Leave blank when there is no previous account. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_previous_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="TEST-mode secret key (sk_test_…) of the previous Stripe account. Used only while Testing Mode is on. Leave blank when there is no previous account. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="test_previous_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="TEST-mode webhook signing secret of the previous Stripe account's endpoint. Used only while Testing Mode is on. Leave blank when there is no previous account. Encrypted at rest.",
                max_length=512,
            ),
        ),
    ]
