# Generated by Django 6.0.8 on 2026-10-10 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0020_stripe_previous_account"),
        ("classes", "0088_classoffering_eventbrite_rules_agreed"),
        ("membership", "0222_equipment_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentrefund",
            name="ck_refund_one_source",
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for equipment reservation payment refunds (#749). Exactly one source FK is set per row.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="membership.equipmentreservation",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(fields=["reservation", "status"], name="idx_refund_reservation_status"),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("late_fee__isnull", True),
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", False),
                        ("reservation__isnull", True),
                    ),
                    models.Q(
                        ("late_fee__isnull", True),
                        ("orientation_booking__isnull", False),
                        ("registration__isnull", True),
                        ("reservation__isnull", True),
                    ),
                    models.Q(
                        ("late_fee__isnull", False),
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", True),
                        ("reservation__isnull", True),
                    ),
                    models.Q(
                        ("late_fee__isnull", True),
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", True),
                        ("reservation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_refund_one_source",
            ),
        ),
    ]
