# Generated by Django 6.0.8 on 2026-10-10 04:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0021_reservation_refunds"),
        ("classes", "0088_classoffering_eventbrite_rules_agreed"),
        ("membership", "0224_equipment_payee"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payout",
            name="payout_exactly_one_source",
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="reservation_guild_percent",
            field=models.DecimalField(
                db_default=Decimal("15.00"),
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Percent of each paid equipment reservation that goes to the item's guild (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="reservation_manager_percent",
            field=models.DecimalField(
                db_default=Decimal("70.00"),
                decimal_places=2,
                default=Decimal("70.00"),
                help_text="Percent of each paid equipment reservation that goes to the item's picked manager (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="reservation_pl_percent",
            field=models.DecimalField(
                db_default=Decimal("15.00"),
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Percent of each paid equipment reservation that goes to Past Lives (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                help_text="The paid equipment reservation this share comes from (#749; exactly one source is set).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout",
                to="membership.equipmentreservation",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="orientation_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The orientation booking this share comes from (exactly one source is set).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout",
                to="membership.orientationbooking",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="payee",
            field=models.ForeignKey(
                help_text="The instructor, orientor or equipment manager who earned the share.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="membership.member",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="registration",
            field=models.OneToOneField(
                blank=True,
                help_text="The class registration this share comes from (exactly one source is set).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout",
                to="classes.registration",
            ),
        ),
        migrations.AlterField(
            model_name="transactionadjustment",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("tab", "Tab"),
                    ("class", "Class"),
                    ("orientation", "Orientation"),
                    ("reservation", "Reservation"),
                ],
                help_text="Which payment stream the target transaction lives in.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionadjustment",
            name="source_pk",
            field=models.PositiveIntegerField(
                help_text="PK of the TabCharge / Registration / OrientationBooking / EquipmentReservation being adjusted."
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", False),
                        ("reservation__isnull", True),
                    ),
                    models.Q(
                        ("orientation_booking__isnull", False),
                        ("registration__isnull", True),
                        ("reservation__isnull", True),
                    ),
                    models.Q(
                        ("orientation_booking__isnull", True),
                        ("registration__isnull", True),
                        ("reservation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="payout_exactly_one_source",
            ),
        ),
    ]
