# Generated by Django 6.0.5 on 2026-05-22 22:44

import secrets

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    """Generate an order number for every Registration that doesn't have one.

    Picks from an unambiguous alphabet and uses the year-suffix of registered_at
    so historic rows get a code that reflects when they were created.
    """
    Registration = apps.get_model("classes", "Registration")
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    existing = set(Registration.objects.exclude(order_number="").values_list("order_number", flat=True))
    for reg in Registration.objects.filter(order_number=""):
        year_suffix = reg.registered_at.strftime("%y") if reg.registered_at else "00"
        for _ in range(40):
            candidate = "PL-" + "".join(secrets.choice(alphabet) for _ in range(4)) + f"-{year_suffix}"
            if candidate not in existing:
                existing.add(candidate)
                break
        else:
            raise RuntimeError(f"Failed to generate a unique order number for Registration pk={reg.pk}")
        reg.order_number = candidate
        reg.save(update_fields=["order_number"])


def clear_order_numbers(apps, schema_editor):
    """Reverse the backfill — clears order_number on every Registration.

    Safe because nothing else references this field. Use only if rolling
    back this migration.
    """
    Registration = apps.get_model("classes", "Registration")
    Registration.objects.update(order_number="")


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0014_registration_wants_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=12,
                help_text="Human-readable confirmation number shown in emails and used by the guest lookup flow (PL-XXXX-YY).",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_order_numbers, clear_order_numbers),
        migrations.AlterField(
            model_name="registration",
            name="order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=12,
                unique=True,
                help_text="Human-readable confirmation number shown in emails and used by the guest lookup flow (PL-XXXX-YY).",
            ),
        ),
    ]
