# Generated by Django 6.0.3 on 2026-05-23 00:36

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0015_registration_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        help_text="Additional class photo.",
                        upload_to="classes/images/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Short description of the image for accessibility.", max_length=255
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_offering",
                    models.ForeignKey(
                        help_text="Parent class offering.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="classes.classoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
