# Generated by Django 6.0.3 on 2026-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0016_classimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="hero_crop_h",
            field=models.PositiveIntegerField(
                blank=True, help_text="Crop box height in source-image pixels — set by the hero cropper.", null=True
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="hero_crop_w",
            field=models.PositiveIntegerField(
                blank=True, help_text="Crop box width in source-image pixels — set by the hero cropper.", null=True
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="hero_crop_x",
            field=models.PositiveIntegerField(
                blank=True, help_text="Crop box left edge in source-image pixels — set by the hero cropper.", null=True
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="hero_crop_y",
            field=models.PositiveIntegerField(
                blank=True, help_text="Crop box top edge in source-image pixels — set by the hero cropper.", null=True
            ),
        ),
    ]
