# Generated by Django 6.0.3 on 2026-05-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0017_hero_crop_fields"),
        ("membership", "0031_remove_calendarevent_uq_calendarevent_guild_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the makerspace Guild that owns this category. Used for Mailchimp tagging.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="membership.guild",
            ),
        ),
    ]
