# Generated by Django 6.0.3 on 2026-05-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0018_category_guild"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.CharField(help_text="The question shown to the registrant.", max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("yes_no", "Yes/No"),
                            ("single_choice", "Single choice"),
                        ],
                        default="short_text",
                        help_text="Input style — short text, paragraph, yes/no, or pick-one.",
                        max_length=20,
                    ),
                ),
                (
                    "choices_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options for SINGLE_CHOICE as a JSON list of strings; ignored for other types.",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, help_text="When on, the registrant must answer.")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to retire a question without deleting historical answers."
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending sort; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer_text", models.TextField(blank=True, help_text="Free-form answer text.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The registration the answer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_answers",
                        to="classes.registration",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question being answered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="classes.registrationquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question__sort_order", "id"],
                "indexes": [models.Index(fields=["registration"], name="classes_reg_registr_68c75d_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("registration", "question"), name="uq_registration_answer_question")
                ],
            },
        ),
    ]
