# Generated by Django 6.0.3 on 2026-05-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0019_registration_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(help_text="Email subject line.", max_length=255)),
                ("body", models.TextField(help_text="Email body as composed (plain text).")),
                ("recipient_count", models.PositiveIntegerField(help_text="Number of registrants BCC'd at send time.")),
                (
                    "bcc_self",
                    models.BooleanField(
                        default=True, help_text="Whether a copy was sent to the instructor's own email."
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, help_text="When the message was sent.")),
                (
                    "class_offering",
                    models.ForeignKey(
                        help_text="The class the recipients are registered for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_messages",
                        to="classes.classoffering",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="The instructor who composed and sent this message.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="classes.instructor",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="InstructorMessageRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="The email address used at send time (snapshot).", max_length=254),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this row belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="classes.instructormessage",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The registration the message was sent to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_instructor_messages",
                        to="classes.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(fields=("message", "registration"), name="uq_instructor_message_recipient")
                ],
            },
        ),
    ]
