# Generated by Django 6.0.3 on 2026-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0020_instructor_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Admin-approved codes are usable. Instructor-created codes start unapproved."
            ),
        ),
    ]
