# Generated by Django 6.0.3 on 2026-06-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_instructor_message_nullable_instructor_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoffering',
            name='legacy_cms_id',
            field=models.CharField(blank=True, db_index=True, help_text='Drupal node UUID from classes.pastlives.space. Empty on manually-created offerings.', max_length=100),
        ),
        migrations.AddField(
            model_name='classoffering',
            name='legacy_image_url',
            field=models.URLField(blank=True, help_text='Hero image URL from the legacy CMS. Cleared after download_legacy_images runs.'),
        ),
        migrations.AlterField(
            model_name='classoffering',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Assigned instructor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.instructor'),
        ),
    ]
