# Generated by Django 6.0.3 on 2026-06-07 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0024_classoffering_uq_legacy_cms_id"),
        ("classes", "0028_cms_activity"),
    ]

    operations = []
