# Generated by Django 6.0.3 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0031_instructor_to_member"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="classapproval",
            new_name="classes_cla_class_o_01bfc5_idx",
            old_name="classes_cla_class_o_50fe07_idx",
        ),
        migrations.RenameIndex(
            model_name="cmsactivity",
            new_name="classes_cms_created_c3374d_idx",
            old_name="classes_cms_created_d18bca_idx",
        ),
        migrations.RenameIndex(
            model_name="cmsactivity",
            new_name="classes_cms_class_o_c7bf13_idx",
            old_name="classes_cms_class_o_a3fc4f_idx",
        ),
        migrations.RenameIndex(
            model_name="cmsactivity",
            new_name="classes_cms_kind_9be9c2_idx",
            old_name="classes_cms_kind_c0eb3e_idx",
        ),
        migrations.AlterField(
            model_name="classapproval",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="cmsactivity",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
