# Generated by Django 6.0.6 on 2026-06-19 03:29

from django.db import migrations, models


def backfill_single_session(apps, schema_editor):
    """Stamp any unset offering as a single session — the behaviour-preserving default.

    The ``AddField`` default already populates every existing row; this is the
    auditable backfill that also catches any row written between the schema add
    and the deploy. Every offering today bills once for its sessions, which is
    exactly Single semantics, so no offering's price, capacity, or checkout
    behaviour changes.
    """
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.filter(scheduling_type="").update(scheduling_type="single_session")


def reverse_backfill(apps, schema_editor):
    """Deliberate no-op reverse.

    The field default already covers a down-migration, and we never want a
    reverse to wipe a value an operator deliberately set to ``series_package``.
    Defined (not ``RunPython.noop``) per the project rule against unexplained
    no-op reverses — the intent is recorded here for future readers.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0034_classoffering_grouping_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="scheduling_type",
            field=models.CharField(
                choices=[("single_session", "Single Session"), ("series_package", "Series Package")],
                default="single_session",
                help_text="Single Session: one date, one seat, one payment. Series Package: one purchase enrolls the registrant in every scheduled date of this class under a single payment.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_single_session, reverse_backfill),
    ]
