# Generated by Django 6.0.3 on 2026-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0037_deactivate_demo_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("class_created", "Class created"),
                    ("class_submitted", "Submitted for review"),
                    ("class_approved", "Approved"),
                    ("class_changes_requested", "Changes requested"),
                    ("class_denied", "Declined"),
                    ("class_published", "Published"),
                    ("class_archived", "Archived"),
                    ("registration_created", "Registered"),
                    ("registration_confirmed", "Payment confirmed"),
                    ("registration_cancelled", "Cancelled"),
                    ("registration_refunded", "Refunded"),
                    ("registration_moved", "Moved"),
                    ("waitlist_joined", "Joined waitlist"),
                    ("waitlist_notified", "Notified of open spot"),
                    ("waitlist_left", "Left waitlist"),
                    ("discount_code_created", "Discount code created"),
                    ("discount_code_redeemed", "Discount code redeemed"),
                ],
                help_text="What happened.",
                max_length=40,
            ),
        ),
    ]
