# Generated by Django 6.0.3 on 2026-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0038_alter_cmsactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="welcome_email_body",
            field=models.TextField(
                blank=True,
                help_text="The welcome message sent to each new registrant. Plain text; line breaks are preserved.",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="welcome_email_enabled",
            field=models.BooleanField(
                default=False, help_text="When on, every new registrant also receives the instructor's welcome email."
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="welcome_email_subject",
            field=models.CharField(
                blank=True, help_text="Subject line for the instructor's welcome email.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="welcome_email_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the welcome email content was last edited.", null=True
            ),
        ),
    ]
