# Generated by Django 6.0.6 on 2026-06-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0039_classoffering_welcome_email_body_and_more"),
        ("membership", "0049_migrate_orienters_to_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["sort_order", "name"], "verbose_name": "Guild", "verbose_name_plural": "Guilds"},
        ),
        migrations.AlterField(
            model_name="category",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the membership Guild that owns this grouping. Used for Mailchimp tagging.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text="Inline SVG markup shown next to the guild name on public pages. Tint via currentColor. Defaults to a Lucide icon seeded for known guilds.",
            ),
        ),
        migrations.AlterField(
            model_name="classoffering",
            name="category",
            field=models.ForeignKey(
                help_text="Guild grouping.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="classes.category",
            ),
        ),
    ]
