# Generated by Django 6.0.6 on 2026-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0040_alter_category_options_alter_category_guild_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationquestion",
            name="mailchimp_tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional Mailchimp tag prefix for this question's answers. Leave blank to auto-derive a tag from the prompt. Only Yes/No and Single Choice answers are pushed to Mailchimp as tags.",
                max_length=80,
            ),
        ),
    ]
