# Generated by Django 6.0.6 on 2026-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0041_registrationquestion_mailchimp_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="create_account",
            field=models.BooleanField(
                default=False,
                help_text="Did an anonymous registrant opt into having a passwordless Past Lives account created once their booking is confirmed? Always False for already-logged-in registrants.",
            ),
        ),
    ]
