# Generated by Django 6.0.6 on 2026-06-25 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0042_registration_create_account"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registrationreminder",
            name="uq_reminder_registration_session",
        ),
        migrations.DeleteModel(
            name="RegistrationReminder",
        ),
    ]
