# Generated by Django 6.0.7 on 2026-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0043_remove_registrationreminder_uq_reminder_registration_session_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Guild Type",
                "verbose_name_plural": "Guild Types",
            },
        ),
        migrations.AlterField(
            model_name="classoffering",
            name="requires_model_release",
            field=models.BooleanField(default=False, help_text="When on, registrants also sign photo release."),
        ),
        migrations.AlterField(
            model_name="waiver",
            name="kind",
            field=models.CharField(
                choices=[("liability", "Liability"), ("model_release", "Photo Release")],
                help_text="Which waiver was signed.",
                max_length=20,
            ),
        ),
    ]
