# Generated by Django 6.0.7 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0044_guild_type_and_photo_release_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Codes are usable only once approved. Every new code starts unapproved until an admin — or a "
                    "member with the self-approve permission, for their own codes — approves it."
                ),
            ),
        ),
    ]
