# Generated by Django 6.0.7 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0045_alter_discountcode_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classoffering",
            name="welcome_email_body",
            field=models.TextField(
                blank=True,
                help_text="The welcome message sent to each new registrant. Supports rich text formatting.",
            ),
        ),
    ]
