# Generated by Django 6.0.7 on 2026-07-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0046_alter_classoffering_welcome_email_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFaq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(help_text="The question.", max_length=500)),
                ("answer", models.TextField(help_text="The answer (plain text; URLs and emails become links).")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "class_offering",
                    models.ForeignKey(
                        help_text="Parent class offering.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="classes.classoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
