# Generated by Django 6.0.6 on 2026-07-21 15:20
"""Add ``channel_announced_at`` to ClassOffering, backfilled to *now* on every
currently-published offering so the first enabled announcer run doesn't flood the
Discord #classes channel with ~550 historical classes. Offerings published after this
migration start NULL and get announced (or silently stamped) by the 15-minute
``announce_new_classes`` job.
"""

from django.db import migrations, models
from django.utils import timezone


def mark_published_offerings_announced(apps, schema_editor):
    """Stamp every already-published offering as announced (migration-run time)."""
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.filter(status="published", channel_announced_at__isnull=True).update(
        channel_announced_at=timezone.now()
    )


def unmark_offerings(apps, schema_editor):
    """Reverse: clear the stamp everywhere (the field is dropped right after anyway)."""
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.update(channel_announced_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0047_classfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="channel_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this class was announced (or silently marked announced) in the Discord #classes "
                    "channel. NULL = not yet announced; the 15-minute announcer picks it up once it is "
                    "publicly bookable. The stamp survives unpublish/republish so a class never re-announces."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(mark_published_offerings_announced, unmark_offerings),
    ]
