# Generated by Django 6.0.6 on 2026-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0048_classoffering_channel_announced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="sale_allow_discount_codes",
            field=models.BooleanField(
                default=False,
                help_text="Off by default — the sale price can't be combined with other offers. Turn on to let registrants add a discount code on top of the sale.",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="sale_amount_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Flat amount off, in cents (edited in dollars). Must be less than the price. Used for a dollar-amount sale.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="sale_banner_text",
            field=models.CharField(
                blank=True,
                default="🔥 Limited-time sale — save on this class while it lasts!",
                help_text="The headline shown on the sale banner. Leave blank to use the default.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="sale_enabled",
            field=models.BooleanField(
                default=False, help_text="When on, this class shows a sale banner and charges the sale price."
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="sale_kind",
            field=models.CharField(
                choices=[("percent", "Percent off"), ("fixed", "Dollar amount off")],
                default="percent",
                help_text="Percent off the full price, or a flat dollar amount off.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="sale_percent",
            field=models.PositiveIntegerField(
                blank=True, help_text="Percent off (1–99). Used for a percent-off sale.", null=True
            ),
        ),
    ]
