# Generated by Django 6.0.8 on 2026-08-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0050_update_default_faq_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="wants_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Is this registration a newsletter opt-in? True when the registrant ticked the box, and also when the box was hidden because they had already opted in elsewhere.",
            ),
        ),
    ]
