# Generated by Django 6.0.7 on 2026-08-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0053_alter_cmsactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payment_due_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="What this registration owes, stamped at promote time. 0 = nothing owed (normal flow, free class, or fully settled at registration).",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_link_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time a payment-link email was sent for this registration. Display-only ('Link sent Aug 26'); dedupe lives in the emit period.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cmsactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("class_created", "Class created"),
                    ("class_submitted", "Submitted for review"),
                    ("class_approved", "Approved"),
                    ("class_changes_requested", "Changes requested"),
                    ("class_denied", "Declined"),
                    ("class_published", "Published"),
                    ("class_archived", "Archived"),
                    ("registration_created", "Registered"),
                    ("registration_confirmed", "Payment confirmed"),
                    ("registration_cancelled", "Cancelled"),
                    ("registration_refunded", "Refunded"),
                    ("registration_partial_refund", "Partially refunded"),
                    ("registration_refund_failed", "Refund failed"),
                    ("registration_moved", "Moved"),
                    ("registration_marked_paid", "Marked paid"),
                    ("payment_link_sent", "Payment link sent"),
                    ("duplicate_payment", "Duplicate payment received"),
                    ("waitlist_joined", "Joined waitlist"),
                    ("waitlist_notified", "Notified of open spot"),
                    ("waitlist_left", "Left waitlist"),
                    ("waitlist_promoted", "Promoted from waitlist"),
                    ("discount_code_created", "Discount code created"),
                    ("discount_code_redeemed", "Discount code redeemed"),
                ],
                help_text="What happened.",
                max_length=40,
            ),
        ),
    ]
