# Generated by Django 6.0.7 on 2026-09-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0054_registration_payment_due"),
        ("membership", "0165_equipment_orientation_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="cancellation_reason",
            field=models.CharField(
                blank=True, help_text="Why the class was cancelled. Emailed to everyone registered.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When this class was cancelled (status CANCELLED).", null=True
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Member who cancelled this class, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.member",
            ),
        ),
        migrations.AlterField(
            model_name="classoffering",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Lifecycle status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cmsactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("class_created", "Class created"),
                    ("class_submitted", "Submitted for review"),
                    ("class_approved", "Approved"),
                    ("class_changes_requested", "Changes requested"),
                    ("class_denied", "Declined"),
                    ("class_published", "Published"),
                    ("class_archived", "Archived"),
                    ("class_cancelled", "Class cancelled"),
                    ("class_withdrawn", "Submission withdrawn"),
                    ("class_restored", "Restored to draft"),
                    ("class_change_requested", "Change requested by instructor"),
                    ("registration_created", "Registered"),
                    ("registration_confirmed", "Payment confirmed"),
                    ("registration_cancelled", "Cancelled"),
                    ("registration_refunded", "Refunded"),
                    ("registration_partial_refund", "Partially refunded"),
                    ("registration_refund_failed", "Refund failed"),
                    ("registration_moved", "Moved"),
                    ("registration_marked_paid", "Marked paid"),
                    ("payment_link_sent", "Payment link sent"),
                    ("duplicate_payment", "Duplicate payment received"),
                    ("waitlist_joined", "Joined waitlist"),
                    ("waitlist_notified", "Notified of open spot"),
                    ("waitlist_left", "Left waitlist"),
                    ("waitlist_promoted", "Promoted from waitlist"),
                    ("discount_code_created", "Discount code created"),
                    ("discount_code_redeemed", "Discount code redeemed"),
                ],
                help_text="What happened.",
                max_length=40,
            ),
        ),
    ]
