# Generated by Django 6.0.7 on 2026-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0055_class_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("class_created", "Class created"),
                    ("class_submitted", "Submitted for review"),
                    ("class_approved", "Approved"),
                    ("class_changes_requested", "Changes requested"),
                    ("class_denied", "Declined"),
                    ("class_published", "Published"),
                    ("class_archived", "Archived"),
                    ("class_cancelled", "Class cancelled"),
                    ("class_withdrawn", "Submission withdrawn"),
                    ("class_restored", "Restored to draft"),
                    ("class_unpublished", "Taken back to draft"),
                    ("class_change_requested", "Change requested by instructor"),
                    ("registration_created", "Registered"),
                    ("registration_confirmed", "Payment confirmed"),
                    ("registration_cancelled", "Cancelled"),
                    ("registration_refunded", "Refunded"),
                    ("registration_partial_refund", "Partially refunded"),
                    ("registration_refund_failed", "Refund failed"),
                    ("registration_moved", "Moved"),
                    ("registration_marked_paid", "Marked paid"),
                    ("payment_link_sent", "Payment link sent"),
                    ("duplicate_payment", "Duplicate payment received"),
                    ("waitlist_joined", "Joined waitlist"),
                    ("waitlist_notified", "Notified of open spot"),
                    ("waitlist_left", "Left waitlist"),
                    ("waitlist_promoted", "Promoted from waitlist"),
                    ("discount_code_created", "Discount code created"),
                    ("discount_code_redeemed", "Discount code redeemed"),
                ],
                help_text="What happened.",
                max_length=40,
            ),
        ),
    ]
