# Generated by Django 6.0.7 on 2026-09-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0056_class_unpublished_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsettings",
            name="example_class",
            field=models.ForeignKey(
                blank=True,
                help_text="The class page shown as the worked example on the Teach at Past Lives page. Leave blank to hide that link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="classes.classoffering",
            ),
        ),
    ]
