# Generated by Django 6.0.7 on 2026-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0058_seed_example_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="card_focus_x",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Horizontal focal point for the catalog card, 0 to 100. Null follows the banner.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="card_focus_y",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Vertical focal point for the catalog card, 0 to 100. Null follows the banner.",
                null=True,
            ),
        ),
    ]
