# Generated by Django 6.0.7 on 2026-09-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0059_classoffering_card_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_cta_line",
            field=models.TextField(
                blank=True,
                default="Tell us what you have in mind and an admin will take it from there.",
                help_text="The line under that headline on the bottom card. Plain text. Leave blank to show no line.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_cta_title",
            field=models.CharField(
                blank=True,
                default="Got Something to Share?",
                help_text="The headline on the card at the bottom of the page, above the I'm Interested button. Leave blank to show no headline.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_expectations",
            field=models.TextField(
                blank=True,
                default="- Know your material and know the tools you're using.\n- Show up on time and leave the space the way you found it.\n- Answer people when they message you through the app.\n- Tell an admin as early as you can if you need to move or cancel a date.",
                help_text="The What We Ask Of You list, a bullet list. Markdown works here: **bold**, lists, links. Leave blank to hide the section.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_faq",
            field=models.TextField(
                blank=True,
                default="### Do I Need to Be an Expert?\nNo. You need to be safe and clear. Plenty of great workshops are run by people two steps ahead of everyone else in the room.\n\n### How Long Until I Hear Back?\nAn admin usually gets to it within a week. You can check this page any time to see where things stand.\n\n### Can I Charge for It?\nYes. You set the price and an optional member discount when you build the page. You can also run it free.\n\n### What If Nobody Signs Up?\nYou can cancel from your dashboard and everyone who signed up is told automatically. Nothing is stuck.",
                help_text="The Common Questions section. Write each question as a ### heading with the answer under it. Markdown works here: **bold**, lists, links. Leave blank to hide the section.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_features",
            field=models.TextField(
                blank=True,
                default="A Page Worth Sharing: Your workshop gets its own page with a wide banner photo, a gallery, the schedule, your bio, and a sign up panel that follows the reader down the page.\nYour Words, Your Photos: Write it the way you would say it. Add a banner and as many gallery shots as you like, and choose which part of each photo shows.\nSign Ups That Run Themselves: When it fills up, people join a waitlist. The moment a seat opens, the next person is offered it and held for three days.\nEveryone On One Screen: See who is coming, mark someone as paid, move a person to another date, and email the whole group without leaving the page.\nFree, Paid, Or On Sale: Run it free, set a price with a member discount, or put it on sale and the new price shows up everywhere on its own.\nRun It Again In One Click: Went well? Make a copy with new dates and keep everything else exactly as it was.",
                help_text="The What You Get cards, one per line, written as Title: description. Six lines make two even rows. Icons are decoration and follow the position of the line, so reordering the lines moves the icons with them. Leave blank to hide the section.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_how_it_works",
            field=models.TextField(
                blank=True,
                default="1. **Say you're interested.** Tell us what you'd like to host. A sentence is plenty. An admin reads every note.\n2. **Build your page.** Once you're in, the editor walks you through it in five short steps. Save a draft any time and come back.\n3. **Open sign ups.** Send it for a quick look. Your guild lead and an admin check it over, then it goes into the catalog and out to members.",
                help_text="The How It Works steps, a numbered list. Each step shows a gold number. Markdown works here: **bold**, lists, links. Leave blank to hide the section.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_lead",
            field=models.TextField(
                blank=True,
                default="Run a workshop or a class for the people already in the shop. Show a technique, teach a skill, or just get folks making things together. You get a page for it, a sign up list, and the tools to run the day.",
                help_text="The paragraph under the headline. Plain text. Leave blank to show no paragraph.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_title",
            field=models.CharField(
                blank=True,
                default="Share What You Love",
                help_text="The big headline at the top of the Host a Workshop page. Leave blank to show no headline.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="example_class",
            field=models.ForeignKey(
                blank=True,
                help_text="The class page shown as the worked example on the Host a Workshop page. Leave blank to hide that link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="classes.classoffering",
            ),
        ),
    ]
