# Generated by Django 6.0.7 on 2026-09-09 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0060_host_a_workshop_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_split_enabled",
            field=models.BooleanField(
                default=True, help_text="Show the Where the Money Goes section on the Host a Workshop page."
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_split_guild_pct",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="The guild's share, as a percentage.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_split_instructor_pct",
            field=models.PositiveSmallIntegerField(
                default=70,
                help_text="The host's share of a paid class, as a percentage.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_split_note",
            field=models.TextField(
                blank=True,
                default="Every paid class splits the same way. Run it free and there is nothing to split.",
                help_text="The line under the split. Plain text. Leave blank to show no line.",
            ),
        ),
        migrations.AddField(
            model_name="classsettings",
            name="teach_page_split_space_pct",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Past Lives' share, as a percentage.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_expectations",
            field=models.TextField(
                blank=True,
                default="<ul><li>Know your material and know the tools you're using.</li><li>Show up on time and leave the space the way you found it.</li><li>Answer people when they message you through the app.</li><li>Tell an admin as early as you can if you need to move or cancel a date.</li></ul>",
                help_text="The What We Ask Of You list, a bullet list. Each item shows as a card with a gold check. Use the toolbar for bold, lists and links. Leave blank to hide the section.",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_faq",
            field=models.TextField(
                blank=True,
                default="<h3>Do I Need to Be an Expert?</h3><p>No. You need to be safe and clear. Plenty of great workshops are run by people two steps ahead of everyone else in the room.</p><h3>How Long Until I Hear Back?</h3><p>An admin usually gets to it within a week. You can check this page any time to see where things stand.</p><h3>Can I Charge for It?</h3><p>Yes. You set the price and an optional member discount when you build the page. You can also run it free.</p><h3>What If Nobody Signs Up?</h3><p>You can cancel from your dashboard and everyone who signed up is told automatically. Nothing is stuck.</p>",
                help_text="The Common Questions section. Make each question a heading and write the answer under it: every heading becomes one question that opens and closes. Use the toolbar for bold, lists and links. Leave blank to hide the section.",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_how_it_works",
            field=models.TextField(
                blank=True,
                default="<ol><li><strong>Say you're interested.</strong> Tell us what you'd like to host. A sentence is plenty. An admin reads every note.</li><li><strong>Build your page.</strong> Once you're in, the editor walks you through it in five short steps. Save a draft any time and come back.</li><li><strong>Open sign ups.</strong> Send it for a quick look. Your guild lead and an admin check it over, then it goes into the catalog and out to members.</li></ol>",
                help_text="The How It Works steps, a numbered list. Each step shows a gold number. Use the toolbar for bold, lists and links. Leave blank to hide the section.",
            ),
        ),
    ]
