# Generated by Django 6.0.7 on 2026-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0065_cancel_duplicate_signups"),
        ("membership", "0173_video_provider_help_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("confirmed", "pending", "waitlisted"))),
                fields=("class_offering", "email"),
                name="uq_registration_seat_email",
            ),
        ),
    ]
