# Generated by Django 6.0.7 on 2026-09-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0066_registration_uq_registration_seat_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="classapproval",
            name="approved_schedule_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash of the session schedule this row approved; lets a later submission tell whether the dates changed since. Stamped only when a guild lead approves; empty means never stamped.",
                max_length=64,
            ),
        ),
    ]
