# Generated by Django 6.0.7 on 2026-09-19 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0067_class_approval_approved_schedule_fingerprint"),
        ("membership", "0173_video_provider_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="classapproval",
            name="opened_for_guild",
            field=models.ForeignKey(
                blank=True,
                help_text="The guild whose lead this gate was opened for, stamped when the row is created. A guild lead's authority comes from the guild that was asked, so this is fixed at the moment of asking and never moves; a class re-filed under another guild stops matching and that guild's lead is asked. Null on admin rows and on rows predating the field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals_granted",
                to="membership.guild",
            ),
        ),
    ]
