# Generated by Django 6.0.7 on 2026-09-18 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0067_class_approval_approved_schedule_fingerprint"),
        ("membership", "0173_video_provider_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="classapproval",
            name="approved_for_guild",
            field=models.ForeignKey(
                blank=True,
                help_text="The guild this row approved the class for; lets a later submission tell whether the class moved to another guild since. Stamped only when a guild lead approves; empty means never stamped.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.guild",
            ),
        ),
    ]
