# Generated by Django 6.0.7 on 2026-09-25 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0068_classapproval_opened_for_guild"),
        ("membership", "0178_orientation_anchor_date_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCodeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="The code the instructor asked for, uppercased on save. Not unique here: uniqueness is enforced on the DiscountCode an approval creates.",
                        max_length=40,
                    ),
                ),
                (
                    "discount_pct",
                    models.PositiveIntegerField(blank=True, help_text="Percent off (0 to 100).", null=True),
                ),
                (
                    "discount_fixed_cents",
                    models.PositiveIntegerField(blank=True, help_text="Flat cents off.", null=True),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, help_text="First date the code should be valid.", null=True),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, help_text="Last date the code should be valid.", null=True),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cap total uses. Blank means unlimited.", null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why the instructor wants this code; shown to the admin who decides."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("declined", "Declined")],
                        default="pending",
                        help_text="Pending until an admin approves or declines it.",
                        max_length=10,
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The admin's note; required on a decline, shown to the instructor.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, help_text="When the admin decided. Null while pending.", null=True
                    ),
                ),
                (
                    "class_offering",
                    models.ForeignKey(
                        help_text="The class the code is for. The approved code is scoped to it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_code_requests",
                        to="classes.classoffering",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who approved or declined it. Null while pending.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discount_code",
                    models.OneToOneField(
                        blank=True,
                        help_text="The code an approval created. Null until approved, and again if that code is later deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request",
                        to="classes.discountcode",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="The instructor who asked. Protected: a request is an audit line that means nothing without its requester.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_code_requests",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_pct__isnull", False), ("discount_fixed_cents__isnull", False), _connector="OR"
                        ),
                        name="discount_request_has_value",
                    )
                ],
            },
        ),
    ]
