# Generated by Django 6.0.7 on 2026-09-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0069_discountcoderequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="classimage",
            name="legacy_source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The classes.pastlives.space file this row was imported from, or blank for an upload. The nightly gallery import skips a file its class already holds under this URL.",
                max_length=500,
            ),
        ),
        migrations.AddIndex(
            model_name="classimage",
            index=models.Index(
                condition=models.Q(("legacy_source_url__gt", "")),
                fields=["legacy_source_url"],
                name="ix_classimage_legacy_src",
            ),
        ),
    ]
