# Generated by Django 6.0.7 on 2026-10-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0070_classimage_legacy_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="hero_cropped",
            field=models.ImageField(
                blank=True,
                help_text="The hero image cut to the composer's crop box. Rendered by save() whenever the box or the image changes and shown in place of the image wherever the class's own photo appears; empty when there is no box.",
                upload_to="classes/hero-crops/",
            ),
        ),
    ]
