# Generated by Django 6.0.7 on 2026-10-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0072_remove_member_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="flexible_ends_on",
            field=models.DateField(
                blank=True,
                help_text="Last day a flexible class runs; it leaves the catalog the day after. Blank for no last day.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="flexible_starts_on",
            field=models.DateField(
                blank=True,
                help_text="First day a flexible class runs; blank when the window has no first day.",
                null=True,
            ),
        ),
    ]
