# Generated by Django 6.0.8 on 2026-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0073_classoffering_flexible_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="subtitle",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Optional plain line shown under the title in the class page hero. Blank shows nothing.",
                max_length=150,
            ),
        ),
    ]
