# Generated by Django 6.0.8 on 2026-10-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0074_classoffering_subtitle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Class Type",
                "verbose_name_plural": "Class Types",
            },
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="example_class",
            field=models.ForeignKey(
                blank=True,
                help_text="The class page shown as the worked example on the Host a Class page. Leave blank to hide that link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="classes.classoffering",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_faq",
            field=models.TextField(
                blank=True,
                default="<h3>Do I Need to Be an Expert?</h3><p>No. You need to be safe and clear. Plenty of great classes are run by people two steps ahead of everyone else in the room.</p><h3>How Long Until I Hear Back?</h3><p>An admin usually gets to it within a week. You can check this page any time to see where things stand.</p><h3>Can I Charge for It?</h3><p>Yes. You set the price when you build the page. Every class costs at least $1.00.</p><h3>What If Nobody Signs Up?</h3><p>You can cancel from your dashboard and everyone who signed up is told automatically. Nothing is stuck.</p>",
                help_text="The Common Questions section. Make each question a heading and write the answer under it: every heading becomes one question that opens and closes. Use the toolbar for bold, lists and links. Leave blank to hide the section.",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_features",
            field=models.TextField(
                blank=True,
                default="A Page Worth Sharing: Your class gets its own page with a wide banner photo, a gallery, the schedule, your bio, and a sign up panel that follows the reader down the page.\nYour Words, Your Photos: Write it the way you would say it. Add a banner and as many gallery shots as you like, and choose which part of each photo shows.\nSign Ups That Run Themselves: When it fills up, people join a waitlist. The moment a seat opens, the next person is offered it and held for three days.\nEveryone On One Screen: See who is coming, mark someone as paid, move a person to another date, and email the whole group without leaving the page.\nPaid Or On Sale: Set a price, or put it on sale and the new price shows up everywhere on its own.\nRun It Again In One Click: Went well? Make a copy with new dates and keep everything else exactly as it was.",
                help_text="The What You Get cards, one per line, written as Title: description. Six lines make two even rows. Icons are decoration and follow the position of the line, so reordering the lines moves the icons with them. Leave blank to hide the section.",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_lead",
            field=models.TextField(
                blank=True,
                default="Run a class for the people already in the shop. Show a technique, teach a skill, or just get folks making things together. You get a page for it, a sign up list, and the tools to run the day.",
                help_text="The paragraph under the headline. Plain text. Leave blank to show no paragraph.",
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_split_enabled",
            field=models.BooleanField(
                default=True, help_text="Show the Where the Money Goes section on the Host a Class page."
            ),
        ),
        migrations.AlterField(
            model_name="classsettings",
            name="teach_page_title",
            field=models.CharField(
                blank=True,
                default="Share What You Love",
                help_text="The big headline at the top of the Host a Class page. Leave blank to show no headline.",
                max_length=120,
            ),
        ),
    ]
