# Generated by Django 6.0.8 on 2026-10-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0076_host_a_class_starting_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="registration_cutoff_hours",
            field=models.PositiveIntegerField(
                blank=True,
                default=48,
                help_text="Registration closes this many hours before the first session. Blank takes sign-ups right up to the start. Ignored for a flexible class.",
                null=True,
            ),
        ),
    ]
