# Generated by Django 6.0.8 on 2026-10-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0077_registration_cutoff_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="flexible_booking_text",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Replaces the standard line on the class page that says how students book a flexible class. Blank shows the standard line, which names the instructor and the window.",
            ),
        ),
    ]
