# Generated by Django 6.0.8 on 2026-10-04 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0078_classoffering_flexible_booking_text"),
        ("membership", "0205_location_and_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The area of the building it meets in. Its guild page shows the area in use during sessions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_offerings",
                to="membership.location",
                verbose_name="Location",
            ),
        ),
    ]
