# Generated by Django 6.0.8 on 2026-10-06 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0079_classoffering_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="classimage",
            name="focus_x",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Horizontal focal point for the gallery frame, 0 to 100. Null is the centre.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="classimage",
            name="focus_y",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Vertical focal point for the gallery frame, 0 to 100. Null is the centre.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
