# Generated by Django 6.0.8 on 2026-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0080_classimage_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_enabled",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="List this class on Eventbrite too. Seats stay in step with this site. Not offered for flexible classes.",
                verbose_name="Also sell on Eventbrite",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_event_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The Eventbrite event ID. Blank until listed.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_fee_payer",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer pays it on top"),
                    ("included", "Included in my price"),
                ],
                db_default="buyer",
                default="buyer",
                help_text="Whether Eventbrite's fee is added on top of the class price or taken out of it.",
                max_length=10,
                verbose_name="Who pays Eventbrite's fee",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_sync_error",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Why the last Eventbrite push failed or is still pending. Blank when it went through.",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_sync_state",
            field=models.CharField(
                choices=[
                    ("idle", "Not listed"),
                    ("pending", "Pending"),
                    ("listed", "Listed"),
                    ("ended", "Ended"),
                    ("failed", "Failed"),
                ],
                db_default="idle",
                default="idle",
                help_text="Where this class's Eventbrite listing stands.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Eventbrite listing last synced.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_ticket_class_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The Eventbrite ticket type that sells this class's seats. Blank until listed.",
                max_length=64,
            ),
        ),
    ]
