# Generated by Django 6.0.8 on 2026-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0081_classoffering_eventbrite"),
        ("membership", "0211_equipment_unlocking_orientations"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="eventbrite_attendee_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The Eventbrite attendee (one ticket) this registration is. Unique, so a redelivered order adds nothing.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="eventbrite_order_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The Eventbrite order this ticket was bought in. One order can hold several registrations.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="source",
            field=models.CharField(
                choices=[("site", "This site"), ("eventbrite", "Eventbrite")],
                db_default="site",
                default="site",
                help_text="Where the booking was made: this site, or a ticket bought on Eventbrite.",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                condition=models.Q(("eventbrite_order_id", ""), _negated=True),
                fields=["eventbrite_order_id"],
                name="registration_eb_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eventbrite_attendee_id", ""), _negated=True),
                fields=("eventbrite_attendee_id",),
                name="uq_registration_eb_attendee",
            ),
        ),
    ]
