# Generated by Django 6.0.8 on 2026-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0082_registration_eventbrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="classimage",
            name="eventbrite_image_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The Eventbrite media ID of this photo once it was uploaded for the class's Eventbrite listing. Blank until then; later syncs reuse it instead of uploading again.",
                max_length=64,
            ),
        ),
    ]
