# Generated by Django 6.0.8 on 2026-10-08 23:58

from __future__ import annotations

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def mark_listed_events_published(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Every class listed on Eventbrite was published by plfog's sync (#720).

    An ended class is left unmarked: plfog unpublished it itself, so a relist publishes it again.
    In production on 2026-10-08 the one listed class is 675, whose event Eventbrite took down;
    marking it keeps the next sync from republishing it.
    """
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.exclude(eventbrite_event_id="").filter(eventbrite_sync_state="listed").update(
        eventbrite_published=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0084_classoffering_eventbrite_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_published",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="plfog has published this class's Eventbrite event. A draft after that was taken down outside plfog and is never republished.",
                verbose_name="Published on Eventbrite by plfog",
            ),
        ),
        migrations.RunPython(mark_listed_events_published, migrations.RunPython.noop),
    ]
