# Generated by Django 6.0.8 on 2026-10-08 23:58

from __future__ import annotations

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def mark_listed_events_published(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Every class with an Eventbrite event that plfog has not ended was published by plfog's sync (#720).

    Listed, pending, failed or idle alike: a save before this deploy moves a listed class to
    pending, and it must still count as published. An ended class is left unmarked, because plfog
    unpublished it itself and a relist publishes it again. In production on 2026-10-08 that marks
    class 675, whose event Eventbrite took down, so the next sync never republishes it.
    """
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.exclude(eventbrite_event_id="").exclude(eventbrite_sync_state="ended").update(
        eventbrite_published=True
    )


def unmark_published_events(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Reverse: clear the mark, as the field's default has it, before the column is dropped."""
    ClassOffering = apps.get_model("classes", "ClassOffering")
    ClassOffering.objects.filter(eventbrite_published=True).update(eventbrite_published=False)


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0084_classoffering_eventbrite_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_published",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="plfog has published this class's Eventbrite event. A draft after that was taken down outside plfog and is never republished.",
                verbose_name="Published on Eventbrite by plfog",
            ),
        ),
        migrations.RunPython(mark_listed_events_published, unmark_published_events),
    ]
