# Generated by Django 6.0.8 on 2026-10-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0086_delete_locked_class_faq_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="The Instagram post's picture, copied into our storage by the video thumbnail job and shown on the class page's Watch card. Empty until fetched, and for any other kind of link.",
                null=True,
                upload_to="classes/video-thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="video_thumbnail_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the job last tried to fetch the picture. A failed try waits a day before the next.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="video_thumbnail_source_url",
            field=models.URLField(
                blank=True,
                db_default="",
                help_text="The video link the picture was taken from, or last tried. When it no longer matches the video link, the picture is stale: the page hides it and the job fetches again.",
                max_length=500,
            ),
        ),
    ]
