# Generated by Django 6.0.8 on 2026-10-09 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0087_classoffering_video_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_rules_agreed_at",
            field=models.DateTimeField(
                blank=True,
                db_default=None,
                default=None,
                help_text="When Eventbrite's selling rules were agreed to for this class. Blank until they are.",
                null=True,
                verbose_name="Agreed to Eventbrite's rules on",
            ),
        ),
        migrations.AddField(
            model_name="classoffering",
            name="eventbrite_rules_agreed_by",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                default=None,
                help_text="Who ticked I agree to Eventbrite's selling rules for this class. Blank until someone does.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agreed to Eventbrite's rules",
            ),
        ),
    ]
