# Generated by Django 6.0.8 on 2026-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0088_classoffering_eventbrite_rules_agreed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classoffering",
            name="video_thumbnail_source_url",
            field=models.URLField(
                blank=True,
                db_default="",
                default="",
                help_text="The video link the picture was taken from, or last tried. When it no longer matches the video link, the picture is stale: the page hides it and the job fetches again.",
                max_length=500,
            ),
        ),
    ]
