# Generated by Django 6.0.5 on 2026-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_note",
            field=models.TextField(blank=True, help_text="Free-text accessibility note from onboarding step 3."),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_attendance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_time", "First time"),
                    ("returning", "Returning"),
                    ("event_only", "Event only, no class"),
                    ("unknown", "Can't remember"),
                ],
                help_text="Self-reported on first signup. Used for welcome flows.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interest_category_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Category slugs the user opted into for new-class email notifications.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamp set when the user finishes (or skips through) the 3-step onboarding.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_name",
            field=models.CharField(blank=True, help_text="Preferred name on rosters.", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("friend", "Friend or family"),
                    ("instagram", "Instagram"),
                    ("google", "Google"),
                    ("event", "Open studio / event"),
                    ("main_site", "Past Lives main site"),
                    ("other", "Somewhere else"),
                ],
                help_text="Self-reported referral source. Aggregated for marketing analysis.",
                max_length=20,
            ),
        ),
    ]
