# Generated by Django 6.0.3 on 2026-05-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_userprofile_onboarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown on the Community Calendar legend (e.g. 'General Calendar', 'Workshops').",
                        max_length=100,
                    ),
                ),
                (
                    "ical_url",
                    models.URLField(
                        help_text="Public iCal URL. Paste the 'Secret address in iCal format' from Google Calendar settings."
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#EEB44B",
                        help_text="Hex color for this feed's events on the Community Calendar (e.g. #EEB44B).",
                        max_length=7,
                    ),
                ),
                (
                    "last_fetched_at",
                    models.DateTimeField(
                        blank=True, help_text="When this feed was last synced. Set by the calendar service.", null=True
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Lower values appear first on the legend."),
                ),
            ],
            options={
                "verbose_name": "Calendar Feed",
                "verbose_name_plural": "Calendar Feeds",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
