# Generated by Django 6.0.3 on 2026-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_backfill_general_calendar_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="completed_tour_at",
            field=models.DateTimeField(
                blank=True, help_text="Cached from Simplybook; refreshed by the tour-status sync.", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscribed_to_mailchimp_at",
            field=models.DateTimeField(
                blank=True, help_text="Stamp set when the account-signup push to Mailchimp succeeded.", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tour_status_checked_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time Simplybook was polled for this user's tour status.", null=True
            ),
        ),
    ]
