# Generated by Django 6.0.3 on 2026-06-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_cache_and_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='legacy_cms_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful legacy CMS sync. Read-only.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legacy_cms_sync_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, classes.pastlives.space offerings sync into plfog every 15 minutes.'),
        ),
    ]
