# Generated by Django 6.0.3 on 2026-06-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_siteconfiguration_legacy_cms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legacy_cms_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of the last successful legacy CMS sync.",
                null=True,
                verbose_name="Legacy CMS last synced at",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legacy_cms_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, classes.pastlives.space offerings sync into plfog every 15 minutes.",
                verbose_name="Sync offerings from legacy CMS",
            ),
        ),
    ]
