# Generated by Django 6.0.3 on 2026-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_siteconfiguration_legacy_cms_sync_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionalEmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("to_email", models.CharField(help_text="Recipient(s); comma-joined when multiple.", max_length=254)),
                ("subject", models.CharField(help_text="Email subject line.", max_length=500)),
                (
                    "trigger_kind",
                    models.CharField(help_text="Which workflow sent it, e.g. 'billing.receipt'.", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], help_text="Send outcome.", max_length=10
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Exception text when status=failed."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="core_transa_created_969736_idx"),
                    models.Index(fields=["status", "-created_at"], name="core_transa_status_66442e_idx"),
                ],
            },
        ),
    ]
