# Generated by Django 6.0.3 on 2026-06-08 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0021_transactionalemaillog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Logged in"),
                            ("logout", "Logged out"),
                            ("profile_updated", "Updated profile"),
                            ("vote_submitted", "Submitted vote"),
                            ("vote_changed", "Changed vote"),
                            ("tab_charged", "Tab charged"),
                            ("tab_charge_failed", "Tab charge failed"),
                            ("tab_entry_added", "Tab entry added"),
                            ("class_registered", "Registered for class"),
                            ("class_registration_cancelled", "Cancelled registration"),
                            ("class_waitlist_joined", "Joined waitlist"),
                            ("class_published", "Class published"),
                            ("class_submitted", "Class submitted"),
                            ("class_approved", "Class approved"),
                            ("class_cancelled", "Class cancelled"),
                            ("refund_issued", "Refund issued"),
                            ("funding_snapshot_taken", "Funding snapshot taken"),
                            ("member_invited", "Member invited"),
                            ("invite_accepted", "Invite accepted"),
                            ("member_signup", "Member signed up"),
                            ("guild_announcement", "Guild announcement"),
                            ("lease_activated", "Lease activated"),
                            ("site_announcement", "Site announcement"),
                        ],
                        help_text="What happened.",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(blank=True, help_text="PK of the related object.", null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict, help_text="Free-form per-kind detail.")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this. Null for system events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="The email this event sent, if any. Source of the ✉ badge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="core.transactionalemaillog",
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the related object, when applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="core_siteac_created_387886_idx"),
                    models.Index(fields=["kind", "-created_at"], name="core_siteac_kind_fed3c8_idx"),
                    models.Index(fields=["actor", "-created_at"], name="core_siteac_actor_i_f68b2e_idx"),
                ],
            },
        ),
    ]
