# Generated by Django 6.0.3 on 2026-06-09 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_siteactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.CharField(help_text="Trigger key from core.triggers.", max_length=40)),
                ("title", models.CharField(help_text="Bold headline shown in the bell.", max_length=200)),
                ("body", models.CharField(help_text="One-line detail.", max_length=500)),
                (
                    "url",
                    models.CharField(blank=True, default="", help_text="Where clicking navigates.", max_length=500),
                ),
                ("read_at", models.DateTimeField(blank=True, help_text="Set when the user reads it.", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "read_at"], name="core_notifi_user_id_bd2d4b_idx"),
                    models.Index(fields=["user", "-created_at"], name="core_notifi_user_id_1cc5b6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.CharField(help_text="Trigger key from core.triggers.", max_length=40)),
                ("push_enabled", models.BooleanField(default=False, help_text="Send browser push for this trigger.")),
                ("email_enabled", models.BooleanField(default=False, help_text="Send email for this trigger.")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "trigger"), name="uq_notificationpreference_user_trigger")
                ],
            },
        ),
    ]
