# Generated by Django 6.0.3 on 2026-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_notification_notificationpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledNotificationMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(help_text="Stable per-notification idempotency key.", max_length=120, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
