# Generated by Django 6.0.6 on 2026-06-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_siteconfiguration_classes_calendar_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="legacy_cms_last_sync_duration",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Wall-clock seconds the last successful legacy CMS sync took. Used to estimate progress.",
                null=True,
                verbose_name="Legacy CMS last sync duration (seconds)",
            ),
        ),
    ]
