# Generated by Django 6.0.6 on 2026-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_siteconfiguration_legacy_cms_last_sync_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_question_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Remembered answers to the CMS registration questions, keyed by question id (as a string).",
            ),
        ),
    ]
