# Generated by Django 6.0.6 on 2026-06-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(help_text="The EventType key that was delivered.", max_length=60)),
                (
                    "target_ref",
                    models.CharField(
                        help_text="Stable string identifying who/what this delivery was for (e.g. 'user:42', 'booking:7').",
                        max_length=120,
                    ),
                ),
                ("channel", models.CharField(help_text="The channel key the event was delivered on.", max_length=20)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dedupe window bucket — empty for one-shot, else e.g. '2026-06' for monthly.",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [models.Index(fields=["event_key", "period"], name="idx_eventdelivery_event_period")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_key", "target_ref", "channel", "period"),
                        name="uq_eventdelivery_event_target_channel_period",
                    )
                ],
            },
        ),
    ]
