# Generated by Django 6.0.6 on 2026-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_eventdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdelivery",
            name="body",
            field=models.TextField(blank=True, default="", help_text="Buffered message body (digest rows only)."),
        ),
        migrations.AddField(
            model_name="eventdelivery",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("pending", "Pending (buffered for digest)")],
                default="sent",
                help_text="SENT once delivered; PENDING while buffered for a later digest flush.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eventdelivery",
            name="title",
            field=models.CharField(
                blank=True, default="", help_text="Buffered message title (digest rows only).", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="eventdelivery",
            name="url",
            field=models.CharField(
                blank=True, default="", help_text="Buffered click-through URL (digest rows only).", max_length=500
            ),
        ),
        migrations.AddIndex(
            model_name="eventdelivery",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["status", "target_ref"],
                name="idx_eventdelivery_pending",
            ),
        ),
    ]
