# Generated by Django 6.0.6 on 2026-06-25 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_eventdelivery_body_eventdelivery_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordWebhookRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_key",
                    models.CharField(
                        help_text="The EventType key this route applies to (one route per event).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The Discord webhook this event posts to. Blank = Discord disabled for this event.",
                        max_length=500,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When off, this route is ignored and the event falls back to the global webhook.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this route was last written.")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last edited this route.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_discord_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_key"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(help_text="The EventType key this copy belongs to.", max_length=60)),
                (
                    "channel",
                    models.CharField(
                        help_text="The channel key this copy is rendered for (email, in_app, …).", max_length=20
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The subject / title line, with {{ merge_field }} placeholders.",
                        max_length=255,
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True, default="", help_text="The plain-text body, with {{ merge_field }} placeholders."
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The HTML body, with {{ merge_field }} placeholders (autoescaped on render).",
                    ),
                ),
                (
                    "is_overridden",
                    models.BooleanField(
                        default=False,
                        help_text="True once the copy team has edited this row; the seed command then preserves it.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this copy was last written.")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last edited this copy (null for seeded rows).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_notification_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_key", "channel"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplateVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", help_text="Subject as it was at snapshot time.", max_length=255
                    ),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, default="", help_text="Text body as it was at snapshot time."),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, default="", help_text="HTML body as it was at snapshot time."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose edit this snapshot captures (null for seeded copy).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this snapshot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("event_key", "channel"), name="uq_notificationtemplate_event_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplateversion",
            index=models.Index(fields=["template", "-created_at"], name="core_notifi_templat_922a6d_idx"),
        ),
    ]
