# Generated by Django 6.0.6 on 2026-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_delete_schedulednotificationmarker"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="last_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invite email was most recently sent. Resending updates this; expiry is measured from it.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siteactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("logout", "Logged out"),
                    ("profile_updated", "Updated profile"),
                    ("vote_submitted", "Submitted vote"),
                    ("vote_changed", "Changed vote"),
                    ("tab_charged", "Tab charged"),
                    ("tab_charge_failed", "Tab charge failed"),
                    ("tab_entry_added", "Tab entry added"),
                    ("class_registered", "Registered for class"),
                    ("class_registration_cancelled", "Cancelled registration"),
                    ("class_waitlist_joined", "Joined waitlist"),
                    ("class_published", "Class published"),
                    ("class_submitted", "Class submitted"),
                    ("class_approved", "Class approved"),
                    ("class_cancelled", "Class cancelled"),
                    ("refund_issued", "Refund issued"),
                    ("funding_snapshot_taken", "Funding snapshot taken"),
                    ("member_invited", "Member invited"),
                    ("member_invite_revoked", "Member invite revoked"),
                    ("invite_accepted", "Invite accepted"),
                    ("member_signup", "Member signed up"),
                    ("guild_announcement", "Guild announcement"),
                    ("orientation_requested", "Orientation requested"),
                    ("orientation_confirmed", "Orientation confirmed"),
                    ("orientation_declined", "Orientation declined"),
                    ("orientation_cancelled", "Orientation cancelled"),
                    ("orientation_completed", "Orientation completed"),
                    ("guild_joined", "Joined a guild"),
                    ("lease_activated", "Lease activated"),
                    ("site_announcement", "Site announcement"),
                ],
                help_text="What happened.",
                max_length=50,
            ),
        ),
    ]
