# Generated by Django 6.0.6 on 2026-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_rename_voting_closing_event_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knownloginsignature",
            name="signature",
            field=models.CharField(help_text="Hash of the browser/device user-agent.", max_length=64),
        ),
    ]
