# Generated by Django 6.0.6 on 2026-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_knownloginsignature_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="class_registration_disabled_note",
            field=models.TextField(
                blank=True,
                default="Online registration is paused right now. Email info@pastlives.space and we'll help you sign up.",
                help_text="Shown under the disabled Register button when class registration is off.",
                verbose_name="Registration-off message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="class_registration_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, the public Register button is disabled (with the note below) and the registration form refuses sign-ups.",
                verbose_name="Allow class registration",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tab_payments_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, hides My Tab, the balance pill, the Buyables tab on guild pages, and the admin Payments/Reports nav. Members visiting the Tab pages are redirected.",
                verbose_name="Enable My Tab & Payments",
            ),
        ),
    ]
