# Generated by Django 6.0.6 on 2026-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_siteconfiguration_class_registration_disabled_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="general_google_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Calendar ID for site-wide community events (Calendar Settings → Integrate calendar → Calendar ID — NOT the iCal URL). Blank keeps site-wide events in FOG only.",
                max_length=255,
                verbose_name="General Google Calendar ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_calendar_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the Google service account is configured), publishing/editing/deleting an event updates the linked Google Calendar.",
                verbose_name="Push events to Google Calendar",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="member_event_policy",
            field=models.CharField(
                choices=[
                    ("approval", "Members can propose (needs review)"),
                    ("open", "Members can post directly"),
                    ("disabled", "Only leads and admins can post"),
                ],
                default="approval",
                help_text="Who can create Community Calendar events, and whether a member's event needs review before it's published. Leads, staff, and admins always post directly.",
                max_length=20,
            ),
        ),
    ]
