# Generated by Django 6.0.6 on 2026-07-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_siteconfiguration_class_registration_disabled_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_general_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Discord webhook for #general-chat. Guild leads can post announcements here. Blank = the option is hidden from the picker.",
                max_length=500,
                verbose_name="#general-chat Discord webhook",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_leadership_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Discord webhook for #leadership. Blank = the option is hidden from the picker.",
                max_length=500,
                verbose_name="#leadership Discord webhook",
            ),
        ),
    ]
