# Generated by Django 6.0.6 on 2026-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_siteconfiguration_general_google_calendar_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_alert_active",
            field=models.BooleanField(
                default=False,
                help_text="EMERGENCY: when on, every screen shows ONLY the alert below until you turn it off.",
                verbose_name="Emergency alert active",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_alert_heading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Big alert headline, e.g. 'Building Closed'.",
                max_length=120,
                verbose_name="Alert heading",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_alert_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Alert details shown under the headline.",
                verbose_name="Alert message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_default_slide_seconds",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Default seconds each slide shows, unless a slide overrides it.",
                verbose_name="Default slide duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_event_days_ahead",
            field=models.PositiveIntegerField(
                default=30,
                help_text="How many days ahead to pull upcoming events for the slideshow.",
                verbose_name="Event look-ahead (days)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_event_qr",
            field=models.BooleanField(
                default=False,
                help_text="Add a QR code to the community calendar on auto event slides.",
                verbose_name="Add a QR to event slides",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_events",
            field=models.BooleanField(
                default=True,
                help_text="Automatically add slides for upcoming site-wide events.",
                verbose_name="Show upcoming events on screens",
            ),
        ),
    ]
