# Generated by Django 6.0.7 on 2026-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_delete_knownloginsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_officers_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Discord webhook for #guild-officers. Blank = the option is hidden from the picker.",
                max_length=500,
                verbose_name="#guild-officers Discord webhook",
            ),
        ),
    ]
