# Generated by Django 6.0.7 on 2026-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_siteconfiguration_discord_officers_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_role_message_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The channel id of the reaction-role message members react on. Blank disables the inbound reaction sync.",
                max_length=32,
                verbose_name="Reaction-role channel id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_role_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The id of the reaction-role message — update if it's reposted. Blank disables the inbound reaction sync.",
                max_length=32,
                verbose_name="Reaction-role message id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_server_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Discord server id used for role assignment (outbound guild sync). Blank disables the whole two-way guild sync.",
                max_length=32,
                verbose_name="Discord server (guild) id",
            ),
        ),
    ]
