# Generated by Django 6.0.7 on 2026-07-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_siteconfiguration_discord_role_message_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdelivery",
            name="period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dedupe window bucket — empty for one-shot, else e.g. '2026-06' for monthly, or a per-object token like 'event:1234:submitted:1752345678.123456'. Wide enough for the timestamp-suffixed periods (~42+ chars) that resubmission/reminder emits build.",
                max_length=120,
            ),
        ),
    ]
