# Generated by Django 6.0.6 on 2026-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_eventdelivery_period"),
    ]

    operations = [
        # Rename (not drop+add) so any Calendar ID already entered on prod is preserved.
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="general_google_calendar_id",
            new_name="member_google_calendar_id",
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="member_google_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Calendar ID for the members-only makerspace calendar — where events set to the 'Member' calendar sync to (Calendar Settings → Integrate calendar → Calendar ID, NOT the iCal URL). Blank keeps 'Member' events in FOG only.",
                max_length=255,
                verbose_name="Member Google Calendar ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="public_google_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Calendar ID for the outward-facing public calendar — where events set to the 'Public' calendar sync to (Calendar Settings → Integrate calendar → Calendar ID, NOT the iCal URL). Blank keeps 'Public' events in FOG only.",
                max_length=255,
                verbose_name="Public Google Calendar ID",
            ),
        ),
    ]
