# Generated by Django 6.0.7 on 2026-07-16 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_rename_general_to_member_google_calendar_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJobState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_key",
                    models.CharField(
                        help_text="Registry key of the job this state controls.", max_length=64, unique=True
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When off, the dispatcher skips this job. Absence of a row also means enabled.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this state was last changed.")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who last flipped this job on or off.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["task_key"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTaskRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_key",
                    models.CharField(
                        db_index=True, help_text="Registry key of the job this run belongs to.", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("ok", "OK"), ("failed", "Failed")],
                        default="running",
                        help_text="Where the run got to: still running, finished OK, or failed.",
                        max_length=16,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("manual", "Run now")],
                        default="scheduled",
                        help_text="Whether the cron dispatched this run or an admin clicked Run now.",
                        max_length=16,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, help_text="When the run began."
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the run finished; null while running or if the process died mid-run.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", help_text="Exception text captured when the run failed."),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who clicked Run now; null for scheduled runs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [models.Index(fields=["task_key", "-started_at"], name="idx_taskrun_key_recent")],
            },
        ),
    ]
