# Generated by Django 6.0.7 on 2026-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_scheduled_task_infra"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_events_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the Discord bot is configured with Manage Events), publishing/editing/deleting a community event creates/updates/removes it in the Discord server's Events. Studio hours and classes are never pushed.",
                verbose_name="Publish events to Discord",
            ),
        ),
    ]
