# Generated by Django 6.0.6 on 2026-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_siteconfig_discord_events_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_calendar_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The channel id of #public-calendar — where the weekly digest and new-event posts go. Blank disables both posts.",
                max_length=30,
                verbose_name="Discord calendar channel id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_calendar_posts_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the calendar channel id is set), FOG posts a weekly what's-coming-up digest to #public-calendar every Monday morning, plus a short post whenever a new event or class lands on the Community Calendar.",
                verbose_name="Post calendar updates to Discord",
            ),
        ),
    ]
