# Generated by Django 6.0.6 on 2026-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_siteconfig_discord_calendar_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_info_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The channel id of #important-info — where the bot's pinned links post lives. Blank disables syncing the post.",
                max_length=30,
                verbose_name="Discord info channel id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_info_links_content",
            field=models.TextField(
                blank=True,
                default="**🎨 Classes**\nBrowse and sign up for upcoming classes and workshops:\nhttps://classes.pastlives.space/\n\n**🗓️ Community Calendar**\nEverything happening at the makerspace — events, guild meetings, studio hours:\nhttps://calendar.pastlives.space\n\n**🤝 Code of Conduct**\nThe community agreements every member signs on to:\nhttps://docs.google.com/document/d/1avWCAnbwDbO79k-n-_QpUc0P2Dz-s6f4/edit\n\n**📱 Past Lives App (FOG)**\nYour member hub — profile, guilds, calendar, and more:\nhttps://pastlives.app",
                help_text="Discord-flavored markdown for the '📌 Past Lives — Important Links' embed in #important-info. Saving updates the pinned Discord post immediately.",
                verbose_name="Important links content",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_info_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The id of the bot's pinned message in #important-info. FOG edits this message in place (it keeps its pin) — update only if the post is ever reposted. Blank disables syncing.",
                max_length=30,
                verbose_name="Discord info message id",
            ),
        ),
    ]
