# Generated by Django 6.0.6 on 2026-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_siteconfig_discord_info_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_classes_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The channel id of #classes — where the weekly classes digest and new-class posts go. Blank disables both posts.",
                max_length=30,
                verbose_name="Discord classes channel id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_classes_posts_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the classes channel id is set), FOG posts a weekly what's-teaching digest to #classes every Monday morning, plus a short post whenever a new class is published.",
                verbose_name="Post class updates to Discord",
            ),
        ),
    ]
