# Generated by Django 6.0.6 on 2026-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_siteconfig_discord_classes_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="member_directory_public",
            field=models.BooleanField(
                default=False,
                help_text="When on, the member directory at /members/ is viewable without signing in (the original public-directory behavior). When off, visitors must sign in before the directory shows anything.",
                verbose_name="Public member directory",
            ),
        ),
    ]
