# Generated by Django 6.0.7 on 2026-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="help_page_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, the Help link is hidden from the sidebar and the /help/ page redirects to the home page.",
                verbose_name="Show Help in the sidebar",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="wiki_link_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, the Wiki link to the makerspace wiki is hidden from the sidebar.",
                verbose_name="Show Wiki link in the sidebar",
            ),
        ),
    ]
