# Generated by Django 6.0.7 on 2026-07-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_siteconfig_help_wiki_toggles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyReviewComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable slug of the gallery section this comment belongs to (surface--label).",
                        max_length=200,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Free-text name the commenter attributed the comment to. Not a user account.",
                        max_length=80,
                    ),
                ),
                ("body", models.TextField(help_text="The comment text (max 2000 chars, enforced by the form).")),
                (
                    "edit_token",
                    models.CharField(
                        help_text="Secret returned once on create; required to edit or delete this comment.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the comment was posted.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the comment was last edited.")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Set when the commenter soft-deletes the comment.", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
