# Generated by Django 6.0.8 on 2026-08-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_copyreviewcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="google_analytics_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="GA4 measurement ID (e.g. G-XXXXXXX) — injected on every page, this admin included. Leave blank to disable.",
                max_length=50,
                verbose_name="Google Analytics measurement ID",
            ),
        ),
    ]
