# Generated by Django 6.0.7 on 2026-08-11 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_siteconfiguration_google_analytics_measurement_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tour_key", models.CharField(help_text="Tour key from core.tours.TOURS.", max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[("offered", "Offered"), ("completed", "Completed"), ("dismissed", "Dismissed")],
                        default="offered",
                        help_text="Where this user is with this tour.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the tour was first offered to this user."),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the status last changed.")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this tour state belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "tour_key"), name="uq_tourstate_user_tour_key")
                ],
            },
        ),
    ]
