# Generated by Django 6.0.7 on 2026-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_joiner_nudge_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When on (and the guild-role sync connection above is configured), Fog Bot sends each NEW server joiner one welcome DM prompting them to create their member portal account and link Discord. Each person is ever DMed once. Turning this off also disables the manual sweep command.",
                verbose_name="DM new Discord joiners",
            ),
        ),
    ]
