# Generated by Django 6.0.7 on 2026-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_fcmdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instructor_discount_codes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When off, instructors can no longer create, edit, or approve their own discount codes from the Teaching portal — the Discount Codes tile is hidden and the pages redirect. Admins can always create and approve discount codes from Classes admin, either way. Default off: only admins create discount codes.",
                verbose_name="Allow instructors to manage their own discount codes",
            ),
        ),
    ]
