# Generated by Django 6.0.7 on 2026-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="display_demo_classes",
            field=models.BooleanField(
                default=False,
                help_text="When on, classes seeded by the demo_data command (a demo- slug) appear in the public catalog, calendar, and class pages. Off hides them from members while admins and instructors still see and manage them. Turn on only for a live demo.",
                verbose_name="Display demo classes",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="display_demo_guild",
            field=models.BooleanField(
                default=False,
                help_text="When on, the example Cartographers guild appears in the guild directory and sidebar. Off keeps it reachable only by its direct link, and it never enters voting or funding either way. Turn on only for a live demo.",
                verbose_name="Display demo guild",
            ),
        ),
    ]
