# Generated by Django 6.0.7 on 2026-09-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_siteconfiguration_display_demo_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="guild_welcome_email_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, no guild welcome email is sent when a member joins a guild (the Join button or the Discord /join-guild command), the join popup's email opt-in is hidden, and the Welcome Email tab is hidden from the guild editor. Per-guild settings are kept and take effect again when this is turned back on.",
                verbose_name="Send guild welcome emails",
            ),
        ),
    ]
