# Generated by Django 6.0.7 on 2026-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_siteconfiguration_guild_welcome_email_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("logout", "Logged out"),
                    ("profile_updated", "Updated profile"),
                    ("vote_submitted", "Submitted vote"),
                    ("vote_changed", "Changed vote"),
                    ("tab_charged", "Tab charged"),
                    ("tab_charge_failed", "Tab charge failed"),
                    ("tab_entry_added", "Tab entry added"),
                    ("class_registered", "Registered for class"),
                    ("class_registration_cancelled", "Cancelled registration"),
                    ("class_waitlist_joined", "Joined waitlist"),
                    ("class_published", "Class published"),
                    ("class_submitted", "Class submitted"),
                    ("class_approved", "Class approved"),
                    ("class_cancelled", "Class cancelled"),
                    ("refund_issued", "Refund issued"),
                    ("funding_snapshot_taken", "Funding snapshot taken"),
                    ("member_invited", "Member invited"),
                    ("member_invite_revoked", "Member invite revoked"),
                    ("invite_accepted", "Invite accepted"),
                    ("member_signup", "Member signed up"),
                    ("guild_announcement", "Guild announcement"),
                    ("orientation_requested", "Orientation requested"),
                    ("orientation_confirmed", "Orientation confirmed"),
                    ("orientation_declined", "Orientation declined"),
                    ("orientation_cancelled", "Orientation cancelled"),
                    ("orientation_completed", "Orientation completed"),
                    ("instructor_oriented", "Completed instructor orientation"),
                    ("teaching_granted", "Teaching access granted"),
                    ("teaching_revoked", "Teaching access revoked"),
                    ("guild_joined", "Joined a guild"),
                    ("lease_activated", "Space agreement activated"),
                    ("space_request", "Space request"),
                    ("site_announcement", "Site announcement"),
                    ("meeting_approved", "Meeting minutes approved"),
                    ("meeting_unlocked", "Meeting minutes unlocked"),
                    ("meeting_unpublished", "Meeting agenda unpublished"),
                    ("account_deleted", "Deleted account"),
                    ("reconciliation_snapshot_taken", "Reconciliation snapshot taken"),
                    ("reconciliation_snapshot_deleted", "Reconciliation snapshot deleted"),
                ],
                help_text="What happened.",
                max_length=50,
            ),
        ),
    ]
