# Generated by Django 6.0.7 on 2026-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="equipment_page_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show the Equipment page in the sidebar and allow reservations.",
                verbose_name="Equipment page",
            ),
        ),
    ]
