# Generated by Django 6.0.7 on 2026-09-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_siteconfiguration_equipment_page_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="discord_reservations_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Discord webhook for #reservations. New equipment reservations post here automatically. Blank = reservations are not posted to Discord.",
                max_length=500,
                verbose_name="#reservations Discord webhook",
            ),
        ),
    ]
