# Generated by Django 6.0.7 on 2026-09-04 21:19

from django.db import migrations, models

_OLD_HEADING = "**🗓️ Community Calendar**"
_NEW_HEADING = "**🗓️ Calendar**"


def _rename_info_links_heading(apps, schema_editor) -> None:
    """Rename the Calendar heading inside the stored #important-info links content."""
    site_configuration = apps.get_model("core", "SiteConfiguration")
    for config in site_configuration.objects.all():
        if _OLD_HEADING in config.discord_info_links_content:
            config.discord_info_links_content = config.discord_info_links_content.replace(_OLD_HEADING, _NEW_HEADING)
            config.save(update_fields=["discord_info_links_content"])


def _restore_info_links_heading(apps, schema_editor) -> None:
    """Reverse: put the old Community Calendar heading back."""
    site_configuration = apps.get_model("core", "SiteConfiguration")
    for config in site_configuration.objects.all():
        if _NEW_HEADING in config.discord_info_links_content:
            config.discord_info_links_content = config.discord_info_links_content.replace(_NEW_HEADING, _OLD_HEADING)
            config.save(update_fields=["discord_info_links_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_siteconfiguration_discord_reservations_webhook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarfeed",
            name="color",
            field=models.CharField(
                default="#EEB44B",
                help_text="Hex color for this feed's events on the Calendar (e.g. #EEB44B).",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="calendarfeed",
            name="name",
            field=models.CharField(
                help_text="Display name shown on the Calendar legend (e.g. 'General Calendar', 'Workshops').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="classes_calendar_color",
            field=models.CharField(
                blank=True,
                default="#7C5CBF",
                help_text="Hex color for class events on the Calendar (e.g. #7C5CBF).",
                max_length=7,
                verbose_name="Classes Calendar Color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="classes_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When class events were last refreshed onto the Calendar. Set by the calendar service.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="discord_calendar_posts_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the calendar channel id is set), FOG posts a weekly what's-coming-up digest to #calendar every Monday morning, plus a short post whenever a new event or class lands on the Calendar.",
                verbose_name="Post calendar updates to Discord",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="discord_info_links_content",
            field=models.TextField(
                blank=True,
                default="**🎨 Classes**\nBrowse and sign up for upcoming classes and workshops:\nhttps://classes.pastlives.space/\n\n**🗓️ Calendar**\nEverything happening at the makerspace — events, guild meetings, studio hours:\nhttps://calendar.pastlives.space\n\n**🤝 Code of Conduct**\nThe community agreements every member signs on to:\nhttps://docs.google.com/document/d/1avWCAnbwDbO79k-n-_QpUc0P2Dz-s6f4/edit\n\n**📱 Past Lives App (FOG)**\nYour member hub — profile, guilds, calendar, and more:\nhttps://pastlives.app",
                help_text="Discord-flavored markdown for the '📌 Past Lives — Important Links' embed in #important-info. Saving updates the pinned Discord post immediately.",
                verbose_name="Important links content",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="general_calendar_color",
            field=models.CharField(
                blank=True,
                default="#EEB44B",
                help_text="Hex color for general makerspace events on the Calendar (e.g. #EEB44B).",
                max_length=7,
                verbose_name="General Calendar Color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="member_event_policy",
            field=models.CharField(
                choices=[
                    ("approval", "Members can propose (needs review)"),
                    ("open", "Members can post directly"),
                    ("disabled", "Only leads and admins can post"),
                ],
                default="approval",
                help_text="Who can create Calendar events, and whether a member's event needs review before it's published. Leads, staff, and admins always post directly.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sync_classes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, upcoming classes from our catalog appear on the Calendar, each linking to its class page.",
                verbose_name="Show class catalog on the Calendar",
            ),
        ),
        migrations.RunPython(_rename_info_links_heading, _restore_info_links_heading),
    ]
