# Generated by Django 6.0.7 on 2026-09-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_alter_calendarfeed_color_alter_calendarfeed_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "secret_hash",
                    models.CharField(
                        help_text="SHA-256 hex of the live secret. The raw secret is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "previous_secret_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hex of the secret this one replaced. Used to tell a dropped reply from a replay.",
                        max_length=64,
                    ),
                ),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the previous secret was superseded. Starts the 60 second grace window.",
                        null=True,
                    ),
                ),
                (
                    "device_label",
                    models.CharField(
                        help_text="Member-visible name for the device, e.g. 'iPhone'. Client supplied, so untrusted.",
                        max_length=120,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        default="android",
                        help_text="Native platform the credential was enrolled from.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the device enrolled.")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When this credential last signed the member in.", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the credential stops working. Pushed forward on every use."),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the member, an admin, or a detected replay killed this credential.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The member this credential signs in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
