# Generated by Django 6.0.7 on 2026-09-07 16:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_biometriccredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_legal_name",
            field=models.CharField(
                blank=True,
                default="Past Lives Makerspace LLC",
                help_text="Your registered legal entity, for receipts and legal notices. Blank uses the organization name.",
                max_length=200,
                verbose_name="Legal name",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_logo",
            field=models.ImageField(
                blank=True,
                help_text="Square logo shown in the sidebar, the public topbar, and the browser tab. Blank uses the built in mark.",
                upload_to="brand/logo/",
                validators=[core.validators.validate_image_size],
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_name",
            field=models.CharField(
                default="Past Lives Makerspace",
                help_text="Your organization's full name. Shown in page titles, the privacy policy, and public page descriptions.",
                max_length=200,
                verbose_name="Organization name",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_primary_color",
            field=models.CharField(
                blank=True,
                default="#092E4C",
                help_text="Your main brand color as a hex code, e.g. #092E4C. Sets the browser and mobile app chrome color.",
                max_length=7,
                validators=[core.validators.validate_hex_color],
                verbose_name="Primary brand color",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_short_name",
            field=models.CharField(
                blank=True,
                default="Past Lives",
                help_text="The compact wordmark used in the sidebar, the public topbar, and browser tab titles. Blank uses the full name.",
                max_length=60,
                verbose_name="Short name",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_support_email",
            field=models.EmailField(
                blank=True,
                default="info@pastlives.space",
                help_text="The address members are told to write to for help. Shown in the privacy policy.",
                max_length=254,
                verbose_name="Support email",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="org_website_url",
            field=models.URLField(
                blank=True,
                default="https://pastlives.space",
                help_text="Your main marketing website, with no trailing slash. The public topbar's Home, Guilds, Membership, and Contact links and the sidebar globe icon are built from it.",
                verbose_name="Public website",
            ),
        ),
    ]
