# Generated by Django 6.0.7 on 2026-09-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_siteconfiguration_org_legal_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="trigger",
            field=models.CharField(help_text="Trigger key from core.triggers.", max_length=100),
        ),
    ]
