# Generated by Django 6.0.7 on 2026-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_siteconfiguration_org_legal_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="wiki_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the Wiki in the sidebar and let members read and write wiki pages. When off, every /wiki/ page and the QR sticker links answer 404.",
                verbose_name="Member wiki",
            ),
        ),
        migrations.AlterField(
            model_name="siteactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("logout", "Logged out"),
                    ("profile_updated", "Updated profile"),
                    ("vote_submitted", "Submitted vote"),
                    ("vote_changed", "Changed vote"),
                    ("tab_charged", "Tab charged"),
                    ("tab_charge_failed", "Tab charge failed"),
                    ("tab_entry_added", "Tab entry added"),
                    ("class_registered", "Registered for class"),
                    ("class_registration_cancelled", "Cancelled registration"),
                    ("class_waitlist_joined", "Joined waitlist"),
                    ("class_published", "Class published"),
                    ("class_submitted", "Class submitted"),
                    ("class_approved", "Class approved"),
                    ("class_cancelled", "Class cancelled"),
                    ("refund_issued", "Refund issued"),
                    ("funding_snapshot_taken", "Funding snapshot taken"),
                    ("member_invited", "Member invited"),
                    ("member_invite_revoked", "Member invite revoked"),
                    ("invite_accepted", "Invite accepted"),
                    ("member_signup", "Member signed up"),
                    ("guild_announcement", "Guild announcement"),
                    ("orientation_requested", "Orientation requested"),
                    ("orientation_confirmed", "Orientation confirmed"),
                    ("orientation_declined", "Orientation declined"),
                    ("orientation_cancelled", "Orientation cancelled"),
                    ("orientation_completed", "Orientation completed"),
                    ("instructor_oriented", "Completed instructor orientation"),
                    ("teaching_granted", "Teaching access granted"),
                    ("teaching_revoked", "Teaching access revoked"),
                    ("guild_joined", "Joined a guild"),
                    ("lease_activated", "Space agreement activated"),
                    ("space_request", "Space request"),
                    ("site_announcement", "Site announcement"),
                    ("meeting_approved", "Meeting minutes approved"),
                    ("meeting_unlocked", "Meeting minutes unlocked"),
                    ("meeting_unpublished", "Meeting agenda unpublished"),
                    ("account_deleted", "Deleted account"),
                    ("reconciliation_snapshot_taken", "Reconciliation snapshot taken"),
                    ("reconciliation_snapshot_deleted", "Reconciliation snapshot deleted"),
                    ("wiki_page_created", "Wiki page created"),
                    ("wiki_page_edited", "Wiki page edited"),
                    ("wiki_page_verified", "Wiki page verified"),
                    ("wiki_page_reported", "Wiki page reported"),
                    ("wiki_page_archived", "Wiki page archived"),
                    ("wiki_page_reverted", "Wiki page reverted"),
                ],
                help_text="What happened.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="wiki_link_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show a link to the old MediaWiki at the bottom of the Wiki home. Turn this off once the old wiki is retired.",
                verbose_name="Show old wiki link",
            ),
        ),
    ]
