# Generated by Django 6.0.7 on 2026-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_wiki_page_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledjobstate",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, the dispatcher skips this job. With no row at all the job's own default applies, which is off for jobs that ship disabled.",
            ),
        ),
    ]
