# Generated by Django 6.0.7 on 2026-09-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_calendar",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide with this month's calendar, marking the days that have something on.",
                verbose_name="Show the month calendar",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_classes",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide for each class or workshop happening in the next seven days.",
                verbose_name="Show this week's classes",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_directory",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide with a QR that opens the member directory.",
                verbose_name="Show the member directory",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_guilds",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide listing every guild in the space, with a QR to the guild directory.",
                verbose_name="Show the guilds",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_teach",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide inviting members to run their own workshop or class.",
                verbose_name="Show Host a Workshop",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_voting",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide about the monthly guild funding vote and when it closes.",
                verbose_name="Show the funding vote",
            ),
        ),
    ]
