# Generated by Django 6.0.7 on 2026-09-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_siteconfiguration_signage_show_calendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_show_tour",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide inviting visitors to book a walkthrough of the space, with a QR to the booking page.",
                verbose_name="Show Book a Tour",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="signage_tour_url",
            field=models.URLField(
                blank=True,
                default="https://www.pastlives.space/tours",
                help_text="Where the Book a Tour QR sends people. Blank leaves the tour slide off the screens.",
                verbose_name="Tour booking link",
            ),
        ),
    ]
