# Generated by Django 6.0.7 on 2026-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_siteconfiguration_signage_show_tour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="signage_show_calendar",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide naming what is still to come this month, soonest first.",
                verbose_name="Show what's on this month",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="signage_show_guilds",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide for each guild, naming its next meeting or class. A guild with nothing coming up shows its About text instead. Guild meetings on a screen are readable by anyone in the building, not only that guild's members.",
                verbose_name="Show the guilds",
            ),
        ),
    ]
