# Generated by Django 6.0.7 on 2026-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_alter_siteconfiguration_signage_show_calendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="host_a_workshop_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show the Host a Workshop entry — the invitation to start teaching — to members who cannot teach yet. Turn it off to stop recruiting instructors for a while. Instructors keep their Teaching entry either way, so the teaching portal is never locked. The page itself stays live at its own link, and its copy is still edited under Classes admin → Settings → Teaching Marketing Page.",
                verbose_name="Show Host a Workshop in the sidebar",
            ),
        ),
    ]
