# Generated by Django 6.0.7 on 2026-09-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_siteconfiguration_host_a_workshop_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureSwitch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "feature_key",
                    models.CharField(
                        help_text="Registry key of the feature this state controls.", max_length=64, unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("on", "On"), ("soon", "Coming soon"), ("hidden", "Hidden")],
                        default="on",
                        help_text="On is normal behaviour. Coming soon leaves the nav entry visible but inert, with the message below on hover. Hidden removes the entry. Both off states answer 404 on every page in the feature, for everyone including admins.",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="The hover text on a Coming soon entry, e.g. 'Launching Sept 30th!'. Blank shows 'Coming soon!'. Ignored unless the state is Coming soon.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this state was last changed.")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who last changed this feature's state.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["feature_key"],
            },
        ),
    ]
