# Generated by Django 6.0.7 on 2026-09-17 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_seed_feature_switches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="equipment_page_enabled",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="host_a_workshop_enabled",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="wiki_enabled",
        ),
    ]
