# Generated by Django 6.0.7 on 2026-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_remove_siteconfiguration_equipment_page_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="member_directory_public",
            field=models.BooleanField(
                default=False,
                help_text="When on, the member directory at /members/ is viewable without signing in (the original public-directory behavior). When off, visitors must sign in before the directory shows anything. This is NOT the on/off switch for the directory itself — that is Member Directory in the feature list above, and a directory set to Hidden or Coming soon there is gone for everyone regardless of this setting. Two switches, two jobs: that one decides whether the feature exists, this one decides whether signed-out visitors can see it.",
                verbose_name="Public member directory",
            ),
        ),
    ]
