# Generated by Django 6.0.7 on 2026-09-17 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_alter_siteconfiguration_member_directory_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="wiki_link_enabled",
        ),
    ]
