# Generated by Django 6.0.7 on 2026-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_remove_siteconfiguration_wiki_link_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="member_directory_public",
            field=models.BooleanField(
                default=False,
                help_text="When on, the member directory at /members/ is viewable without signing in (the original public-directory behavior). When off, visitors must sign in before the directory shows anything. This is the real access switch for the directory. Member Directory in the feature list above is cosmetic: it only decides whether the entry shows in the sidebar, and the page stays reachable by its own link either way. Two switches, two jobs — that one tidies the sidebar, this one decides whether signed-out visitors can read the directory.",
                verbose_name="Public member directory",
            ),
        ),
    ]
