# Generated by Django 6.0.7 on 2026-09-19 05:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_alter_siteconfiguration_member_directory_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="equipment_late_cancel_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Dollars added to a member's tab when they cancel an equipment reservation with less notice than the hours below. 0 means no fee: nobody is ever charged.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Equipment late cancellation fee",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="equipment_late_cancel_notice_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="How many hours before a reservation starts a member can still cancel for free. Cancelling with less notice than this adds the fee above to their tab.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Equipment cancellation notice (hours)",
            ),
        ),
    ]
