# Generated by Django 6.0.7 on 2026-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_siteconfiguration_member_agreement_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="guided_tours_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, the guided tour offer never pops up for anyone. Each member's own tour setting is kept, and a tour can still be started from its Show me around link.",
                verbose_name="Offer guided tours",
            ),
        ),
    ]
