# Generated by Django 6.0.8 on 2026-09-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_siteconfiguration_guided_tours_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='member_agreement_version',
            field=models.CharField(blank=True, default='', help_text="The released version members must have accepted, e.g. '2.0.0'. Leave blank to keep the one-time behaviour: anyone who has ever accepted is never asked again. Setting a version here re-prompts every member who accepted a different one, so change it only for a release that people genuinely need to re-read.", max_length=40, verbose_name='Member Agreement version'),
        ),
    ]
