# Generated by Django 6.0.7 on 2026-09-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_siteconfiguration_guided_tours_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionalemaillog",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Exception text when status=failed; the policy reason when status=suppressed.",
            ),
        ),
        migrations.AlterField(
            model_name="transactionalemaillog",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("failed", "Failed"), ("suppressed", "Suppressed")],
                help_text="Send outcome.",
                max_length=10,
            ),
        ),
    ]
