# Generated by Django 6.0.7 on 2026-09-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_transactionalemaillog_suppressed"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instructor_discount_codes_need_approval",
            field=models.BooleanField(
                default=True,
                help_text="When on, instructors ask for a discount code and an admin approves or declines it; the code exists only once approved. When off, instructors create, edit and delete their own codes directly, and each new code waits for approval as before. This only matters while the setting above is on.",
                verbose_name="Instructors request discount codes and an admin approves them",
            ),
        ),
    ]
