# Generated by Django 6.0.7 on 2026-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="discord_events_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on (and the Discord bot is configured with Manage Events), publishing/editing/deleting a an event creates/updates/removes it in the Discord server's Events. Studio hours and classes are never pushed.",
                verbose_name="Publish events to Discord",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="signage_event_qr",
            field=models.BooleanField(
                default=False,
                help_text="Add a QR code to the Calendar on auto event slides.",
                verbose_name="Add a QR to event slides",
            ),
        ),
    ]
