# Generated by Django 6.0.7 on 2026-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_alter_siteactivity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="late_cancel_fees_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on, guilds and equipment can set a fee for cancelling an orientation or reservation inside the notice window. Off means nothing charges anywhere.",
                verbose_name="Charge late cancellation fees",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="late_cancel_grace_hours",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Not shown to members. A cancel this close to the notice line is still free.",
                verbose_name="Grace period (hours)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="late_cancel_notice_hours",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="How far ahead members are told to cancel. Shown wherever a fee applies.",
                verbose_name="Cancellation notice (hours)",
            ),
        ),
    ]
