# Generated by Django 6.0.7 on 2026-09-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_fold_my_tab_into_feature_switches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="my_tab_enabled",
        ),
        migrations.AlterField(
            model_name="featureswitch",
            name="state",
            field=models.CharField(
                choices=[("on", "On"), ("soon", "Coming soon"), ("hidden", "Hidden")],
                default="on",
                help_text="On is normal behaviour. Coming soon leaves the sidebar entry visible but inert, showing the message below on hover and on keyboard focus. Hidden removes the entry. For every feature but My Tab, both off states change the sidebar only: every page in the feature stays reachable by its own link, for everyone. My Tab is the exception: both off states turn tab billing off.",
                max_length=10,
            ),
        ),
    ]
