# Generated by Django 6.0.7 on 2026-09-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_drop_my_tab_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="former_member_signin_message",
            field=models.TextField(
                blank=True,
                default="Your membership is no longer active, so this account can no longer sign in to the member site.",
                help_text="Shown when a former member tries to sign in to the member site. The support email is shown under it. Blank uses the built in sentence.",
                verbose_name="Former member sign in message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="suspended_member_signin_message",
            field=models.TextField(
                blank=True,
                default="Your membership is paused right now, so this account cannot sign in to the member site.",
                help_text="Shown when a suspended member tries to sign in while suspended members are locked out. The support email is shown under it. Blank uses the built in sentence.",
                verbose_name="Suspended member sign in message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="suspended_members_locked_out",
            field=models.BooleanField(
                default=True,
                help_text="When on, a suspended member cannot sign in to the member site and sees the message below. Former members are always locked out.",
                verbose_name="Lock out suspended members",
            ),
        ),
    ]
