# Generated by Django 6.0.8 on 2026-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_siteconfiguration_member_agreement_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarfeed",
            name="name",
            field=models.CharField(
                help_text="Display name shown on the Calendar legend (e.g. 'General Calendar', 'Classes').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="discord_info_links_content",
            field=models.TextField(
                blank=True,
                default="**🎨 Classes**\nBrowse and sign up for upcoming classes:\nhttps://classes.pastlives.space/\n\n**🗓️ Calendar**\nEverything happening at the makerspace — events, guild meetings, studio hours:\nhttps://calendar.pastlives.space\n\n**🤝 Code of Conduct**\nThe community agreements every member signs on to:\nhttps://docs.google.com/document/d/1avWCAnbwDbO79k-n-_QpUc0P2Dz-s6f4/edit\n\n**📱 Past Lives App (FOG)**\nYour member hub — profile, guilds, calendar, and more:\nhttps://pastlives.app",
                help_text="Discord-flavored markdown for the '📌 Past Lives — Important Links' embed in #important-info. Saving updates the pinned Discord post immediately.",
                verbose_name="Important links content",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="signage_show_classes",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide for each class happening in the next seven days.",
                verbose_name="Show this week's classes",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="signage_show_teach",
            field=models.BooleanField(
                default=True,
                help_text="Add a slide inviting members to run their own class.",
                verbose_name="Show Host a Class",
            ),
        ),
    ]
