# Generated by Django 6.0.8 on 2026-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_info_links_class_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="guest_member_signin_message",
            field=models.TextField(
                blank=True,
                default="This account is for booking classes. Membership is separate: email us to become a member.",
                help_text="Shown when a guest account (made when booking a class) tries to sign in to the member site. The support email is shown under it. Blank uses the built in sentence.",
                verbose_name="Guest sign in message",
            ),
        ),
    ]
