# Generated by Django 6.0.8 on 2026-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_siteconfiguration_guest_member_signin_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="eventbrite_sync_enabled",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="When on (and the Eventbrite credentials are set), a published class whose instructor ticked Also sell on Eventbrite is listed there, kept up to date, and taken down when it ends.",
                verbose_name="Sell classes on Eventbrite",
            ),
        ),
    ]
