# Generated by Django 6.0.8 on 2026-10-08 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_siteconfiguration_eventbrite_sync_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("feedback", "General Feedback"),
                        ],
                        help_text="What kind of request the sender picked on the Feedback page.",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="The sender's one-line summary.", max_length=200),
                ),
                ("message", models.TextField(help_text="The sender's full message.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("planned", "Planned"),
                            ("building", "Building"),
                            ("live", "Live"),
                            ("not_planned", "Not planned"),
                        ],
                        default="received",
                        help_text="Where the request stands. The sender sees it on the Feedback page.",
                        max_length=12,
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A note to the sender, shown with the request. Required for Not planned.",
                    ),
                ),
                (
                    "github_issue_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The GitHub issue tracking the work. Only admins see it.",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the status last changed; the sender sees this date.",
                    ),
                ),
                (
                    "live_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the sender was last told this is live, so the automatic live notice never repeats it.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the sender sent it."),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who sent it. Any signed-in account, with or without a membership.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRequestPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The uploaded photo, on the default storage.",
                        upload_to="feedback/%Y/%m/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When it was uploaded."),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="The request this photo was sent with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.feedbackrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(fields=["status", "-created_at"], name="fbreq_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(fields=["user", "-created_at"], name="fbreq_user_created_idx"),
        ),
    ]
