# Generated by Django 6.0.8 on 2026-10-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_siteconfiguration_eventbrite_sync_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="kiln_tickets_open",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="When on, every member and every guest account can file kiln tickets, and guests can sign in to the member site for that alone. When off, only the Ceramics Guild lead and staff can open Kiln Tickets, and guest accounts stay locked out of the member site.",
                verbose_name="Open kiln tickets to everyone",
            ),
        ),
    ]
