# Generated by Django 6.0.8 on 2026-10-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_siteconfiguration_kiln_tickets_open"),
        ("membership", "0215_member_teaching_inquiry_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="backlog_url",
            field=models.URLField(
                blank=True,
                db_default="https://github.com/orgs/Past-Lives-Makerspace/projects/1",
                default="https://github.com/orgs/Past-Lives-Makerspace/projects/1",
                help_text="The public board of planned work. Blank hides the link.",
                verbose_name="Backlog link",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="being_built_now",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Shown to every member. Leave empty to hide the list. One item per line, in plain words.",
                verbose_name="Being built now",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="feature_meeting_event",
            field=models.ForeignKey(
                blank=True,
                help_text="The recurring meeting where members see what's new and say what to build.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.communityevent",
                verbose_name="Feature Meeting event",
            ),
        ),
    ]
