# Generated by Django 6.0.8 on 2026-10-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_siteconfiguration_kiln_tickets_open"),
        ("membership", "0215_member_teaching_inquiry_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="spotlight_first_line",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Empty uses this week's poll question.",
                max_length=120,
                verbose_name="Minimized first line",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="spotlight_meeting_event",
            field=models.ForeignKey(
                blank=True,
                help_text="The Spotlight always shows this event's next date, so a monthly event rolls on by itself.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.communityevent",
                verbose_name="Feature Request Meeting event",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="spotlight_second_line",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Empty uses Feature Request Meeting. The date and time pill always follows it.",
                max_length=120,
                verbose_name="Minimized second line",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="spotlight_text_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When either Spotlight line last changed; members see the Spotlight's dot until they open it.",
                null=True,
            ),
        ),
    ]
