# Generated by Django 6.0.8 on 2026-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_siteconfiguration_spotlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="spotlight_show_when_empty",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="On: members see the latest update and Details. Off: the corner goes back to the logo and version number.",
                verbose_name="Show the Spotlight when there is no poll and no meeting",
            ),
        ),
    ]
