# Generated by Django 6.0.3 on 2026-03-06 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0006_guild_voting_system"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GuildMembership",
        ),
    ]
