# Generated by Django 6.0.3 on 2026-05-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_calendarfeed"),
        ("membership", "0029_member_directory_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                help_text="The named general-calendar feed this event came from. Null for guild and classes events.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="core.calendarfeed",
            ),
        ),
    ]
