# Generated by Django 6.0.3 on 2026-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_backfill_general_calendar_feed"),
        ("membership", "0030_calendarevent_feed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="calendarevent",
            name="uq_calendarevent_guild_uid",
        ),
        migrations.AddConstraint(
            model_name="calendarevent",
            constraint=models.UniqueConstraint(fields=("guild", "feed", "uid"), name="uq_calendarevent_guild_feed_uid"),
        ),
    ]
