# Generated by Django 6.0.3 on 2026-06-08 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0032_member_instructor_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("instructor_slug", ""), _negated=True),
                fields=("instructor_slug",),
                name="uq_member_instructor_slug",
            ),
        ),
    ]
