# Generated by Django 6.0.3 on 2026-06-09 03:09

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0033_member_instructor_slug_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        help_text="Gallery photo.",
                        upload_to="guilds/images/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, help_text="Accessibility description.", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
