# Generated by Django 6.0.3 on 2026-06-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0034_guildimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildFAQItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(help_text="The question.", max_length=500)),
                ("answer", models.TextField(help_text="The answer.")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="GuildLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="Display text, e.g. 'Discord'.", max_length=100)),
                ("url", models.URLField(help_text="Destination URL.")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
