# Generated by Django 6.0.3 on 2026-06-09 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0036_guildannouncement"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="The guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="membership.guild",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_memberships",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("guild", "member"), name="uq_guildmembership_guild_member")
                ],
            },
        ),
    ]
