# Generated by Django 6.0.3 on 2026-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0037_guildmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", help_text="Optional guild contact email shown on the page.", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="meeting_schedule",
            field=models.TextField(
                blank=True, default="", help_text="When/where the guild meets, e.g. 'Tuesdays 6pm, Studio B'."
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="show_members",
            field=models.BooleanField(
                default=False, help_text="Show the opt-in members roster on the public guild page."
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="youtube_url",
            field=models.URLField(blank=True, default="", help_text="Optional YouTube video shown on the guild page."),
        ),
    ]
