# Generated by Django 6.0.3 on 2026-06-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0039_classoffering_welcome_email_body_and_more"),
        ("membership", "0041_guild_meeting_cadence_guild_meeting_is_tba_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="featured_class",
            field=models.ForeignKey(
                blank=True,
                help_text="A class to spotlight at the top of the guild page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="classes.classoffering",
            ),
        ),
    ]
