# Generated by Django 6.0.6 on 2026-06-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0042_guild_featured_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildOrientationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_enabled",
                    models.BooleanField(default=False, help_text="Offer orientation booking on this guild's page."),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Orientation info shown to members before they book (plain text).",
                    ),
                ),
                (
                    "default_seats",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Default capacity for new orientation slots."
                    ),
                ),
                (
                    "default_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default place orientations happen, e.g. 'Front desk'.",
                        max_length=200,
                    ),
                ),
                (
                    "default_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Length of a slot generated from a recurring rule, in minutes."
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, help_text="Temporarily stop taking orientation bookings."),
                ),
                (
                    "closed_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shown while closed, e.g. 'On vacation till Sept 8'.",
                        max_length=300,
                    ),
                ),
                (
                    "thankyou_email_enabled",
                    models.BooleanField(
                        default=False, help_text="Send a thank-you / next-steps email once an orientation is completed."
                    ),
                ),
                (
                    "thankyou_email_subject",
                    models.CharField(
                        blank=True, default="", help_text="Subject line of the thank-you email.", max_length=200
                    ),
                ),
                (
                    "thankyou_email_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Body of the thank-you email (plain text, line breaks preserved).",
                    ),
                ),
                (
                    "thankyou_email_updated_at",
                    models.DateTimeField(blank=True, help_text="When the thank-you email was last edited.", null=True),
                ),
                (
                    "join_email_enabled",
                    models.BooleanField(
                        default=False, help_text="Send a welcome email when a member joins this guild."
                    ),
                ),
                (
                    "join_email_subject",
                    models.CharField(
                        blank=True, default="", help_text="Subject line of the welcome email.", max_length=200
                    ),
                ),
                (
                    "join_email_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Body of the welcome email (plain text, line breaks preserved).",
                    ),
                ),
                (
                    "join_email_updated_at",
                    models.DateTimeField(blank=True, help_text="When the welcome email was last edited.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.OneToOneField(
                        help_text="The guild these orientation settings belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_settings",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild orientation settings",
                "verbose_name_plural": "Guild orientation settings",
            },
        ),
        migrations.CreateModel(
            name="OrientationAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week this rule recurs on (0=Mon … 6=Sun).",
                    ),
                ),
                ("start_time", models.TimeField(help_text="When the orientation window starts.")),
                ("end_time", models.TimeField(help_text="When the orientation window ends.")),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Capacity for slots generated from this rule."
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Overrides the guild's default location for these slots.",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Generate slots from this rule.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_rules",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="OrientationSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Added manually"), ("generated", "From a recurring rule")],
                        default="manual",
                        help_text="How this slot was created.",
                        max_length=10,
                    ),
                ),
                ("starts_at", models.DateTimeField(help_text="When the orientation starts.")),
                ("ends_at", models.DateTimeField(help_text="When the orientation ends.")),
                ("seats", models.PositiveSmallIntegerField(default=4, help_text="Total capacity.")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", help_text="Where the orientation happens.", max_length=200
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False, help_text="Set when the slot is called off.")),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, default="", help_text="Why the slot was cancelled.", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "availability",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recurring rule that generated this slot, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="membership.orientationavailability",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_slots",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="OrientationBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        help_text="Request lifecycle state.",
                        max_length=10,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the orientation actually happened. Auto-set after the slot ends; editable by leads.",
                    ),
                ),
                (
                    "member_note",
                    models.TextField(
                        blank=True, default="", help_text="Optional note from the member when requesting."
                    ),
                ),
                (
                    "lead_note",
                    models.TextField(
                        blank=True, default="", help_text="Note from the lead when declining or following up."
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Denormalized from the slot for cheap filtering and scoping.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_bookings",
                        to="membership.guild",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who's getting oriented.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_bookings",
                        to="membership.member",
                    ),
                ),
                (
                    "oriented_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who gave the orientation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orientations_given",
                        to="membership.member",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        help_text="The slot booked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="membership.orientationslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="orientationavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="ck_orientationavailability_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("availability__isnull", False)),
                fields=("availability", "starts_at"),
                name="uq_orientationslot_rule_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationbooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["requested", "confirmed"])),
                fields=("guild", "member"),
                name="uq_orientationbooking_active_per_guild",
            ),
        ),
    ]
