# Generated by Django 6.0.6 on 2026-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0043_guildorientationsettings_orientationavailability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_url",
            field=models.URLField(
                blank=True, default="", help_text="Link to the guild's Discord channel, shown as a button on the page."
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="website_url",
            field=models.URLField(
                blank=True, default="", help_text="Link to the guild's external website, shown as a button on the page."
            ),
        ),
    ]
