# Generated by Django 6.0.6 on 2026-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0044_guild_discord_url_guild_website_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="meeting_cadence",
            field=models.CharField(
                choices=[
                    ("none", "No regular meeting"),
                    ("monthly", "Monthly"),
                    ("every_2_months", "Every 2 months"),
                    ("every_3_months", "Every 3 months"),
                ],
                default="none",
                help_text="How often the guild meets — drives the auto-computed next-meeting date.",
                max_length=20,
            ),
        ),
    ]
