# Generated by Django 6.0.6 on 2026-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0045_alter_guild_meeting_cadence"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildorientationsettings",
            name="allow_custom_requests",
            field=models.BooleanField(
                default=True,
                help_text="Let members propose their own orientation time instead of only picking a posted slot.",
            ),
        ),
    ]
