# Generated by Django 6.0.6 on 2026-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0046_guildorientationsettings_allow_custom_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="orienters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Members trusted to run this guild's orientations — confirm bookings, sign members off, and manage availability. They cannot edit the guild page, manage classes, or add other orienters; only the guild lead or an admin can.",
                related_name="orienting_guilds",
                to="membership.member",
            ),
        ),
    ]
