# Generated by Django 6.0.6 on 2026-06-24 18:44

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0049_migrate_orienters_to_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildMeetingNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meeting_date", models.DateField(help_text="The date this meeting took place (or is scheduled for).")),
                ("title", models.CharField(help_text="Short headline, e.g. 'June general meeting'.", max_length=300)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional written notes. Supports Markdown — bold, lists, links.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who posted these notes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_notes",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildMeetingNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What to call this — e.g. 'Agenda PDF'. Defaults to the file name or link.",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a document (PDF, Word, slides, spreadsheet…). Leave blank if you're adding a link instead.",
                        upload_to="guilds/meeting_notes/",
                        validators=[core.validators.validate_document],
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to an external doc (e.g. a Google Doc). Leave blank if you uploaded a file instead.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        help_text="Parent meeting note.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="membership.guildmeetingnote",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("file", ""), models.Q(("url", ""), _negated=True)),
                            models.Q(models.Q(("file", ""), _negated=True), ("url", "")),
                            _connector="OR",
                        ),
                        name="ck_meetingnoteattachment_file_xor_url",
                    )
                ],
            },
        ),
    ]
