# Generated by Django 6.0.6 on 2026-06-26 14:45

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0050_guildmeetingnote_guildmeetingnoteattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reminder_lead_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How many days before close to send the 'Polls closing soon!' reminder (minimum 1).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "minimum_pool_floor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Dollar floor for the funding pool. The pool is the larger of (paying voters × $10) and this.",
                        max_digits=10,
                    ),
                ),
                (
                    "reminders_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for the 'Polls closing soon!' reminder to members who have voted.",
                    ),
                ),
                (
                    "send_vote_soon_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for the 'Vote soon!' nudge to members who've signed in but never voted.",
                    ),
                ),
                (
                    "auto_snapshot_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for the automated cycle-end snapshot (it never auto-emails members).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voting Settings",
                "verbose_name_plural": "Voting Settings",
            },
        ),
    ]
