# Generated by Django 6.0.6 on 2026-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0053_backfill_funding_results_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_post_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Also post this guild's announcements to your own Discord channel (in addition to the makerspace-wide channel).",
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="A Discord webhook for THIS guild's own channel. Guild announcements also post here. Blank = nothing posts to your channel.",
                max_length=500,
            ),
        ),
    ]
