# Generated by Django 6.0.6 on 2026-06-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0054_guild_discord_post_enabled_guild_discord_webhook_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Event name shown on the calendar — e.g. 'Monthly Potluck'.", max_length=200
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("guild_meeting", "Guild meeting / event"),
                            ("lead_meeting", "Guild Lead Meeting"),
                            ("community", "Community event"),
                        ],
                        default="guild_meeting",
                        help_text="What kind of event this is.",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(help_text="When the event starts.")),
                ("ends_at", models.DateTimeField(help_text="When the event ends.")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where it happens — a room name, address, or a video link. Optional.",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, default="", help_text="Optional details for members.")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[("none", "Does not repeat"), ("monthly", "Repeats monthly")],
                        default="none",
                        help_text="Whether this event repeats. 'Repeats monthly' recurs on the same weekday-of-month as the start (e.g. the 2nd Saturday).",
                        max_length=12,
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reserved for a future Google Calendar sync. Not used yet.",
                        max_length=1024,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created this event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this belongs to. Leave blank for a site-wide community or leadership event.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "indexes": [models.Index(fields=["starts_at"], name="idx_communityevent_starts")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="ck_communityevent_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("event_type", "guild_meeting"), ("guild__isnull", False)),
                            models.Q(models.Q(("event_type", "guild_meeting"), _negated=True), ("guild__isnull", True)),
                            _connector="OR",
                        ),
                        name="ck_communityevent_guild_matches_type",
                    ),
                ],
            },
        ),
    ]
