# Generated by Django 6.0.6 on 2026-06-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0055_communityevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name of the category.", max_length=100, unique=True)),
                ("slug", models.SlugField(help_text="URL-safe identifier.", max_length=120, unique=True)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, help_text="Lower numbers sort first in pickers."),
                ),
            ],
            options={
                "verbose_name": "skill category",
                "verbose_name_plural": "skill categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="commission_note",
            field=models.CharField(
                blank=True,
                help_text="Short note on the kind of paid or commissioned work the member welcomes.",
                max_length=280,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="open_for_commissions",
            field=models.BooleanField(
                default=False,
                help_text="When on, the member shows an 'Open for commissions!' badge and appears in that filter.",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="directory_visibility",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field public/hidden flags for the member directory card. Keys: pronouns, phone, email, discord_handle, other_contact_info, about_me, profile_photo, skills. Missing key means public (default-on).",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Canonical skill name shown everywhere.", max_length=80, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier used for filtering.", max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("pending", "Pending review")],
                        default="approved",
                        help_text="Approved skills appear publicly; pending skills are member suggestions awaiting review.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the skill entered the vocabulary."),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member who proposed this skill, if it came from a suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_skills",
                        to="membership.member",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category this skill belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="membership.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MemberSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional years of experience, shown beside the skill when set.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the member added this skill.")),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who listed this skill.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="membership.member",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="The skill being claimed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_links",
                        to="membership.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill__category__sort_order", "skill__name"],
                "constraints": [
                    models.UniqueConstraint(fields=("member", "skill"), name="uq_memberskill_member_skill")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["status", "name"], name="idx_skill_status_name"),
        ),
    ]
