# Generated by Django 6.0.6 on 2026-06-27 03:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0057_seed_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildfaqitem",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Optional document (PDF, Word, slides, spreadsheet…) shown with this answer. Leave blank to link an external doc instead.",
                upload_to="guilds/faq/",
                validators=[core.validators.validate_document],
            ),
        ),
        migrations.AddField(
            model_name="guildfaqitem",
            name="document_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link to an external doc for this answer. Leave blank if you uploaded a file.",
            ),
        ),
        migrations.AddField(
            model_name="guildfaqitem",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional YouTube link shown with this answer (watch, youtu.be, embed, or shorts URL).",
            ),
        ),
        migrations.AddConstraint(
            model_name="guildfaqitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("document", ""), ("document_url", ""), _connector="OR"),
                name="ck_guildfaqitem_doc_not_both",
            ),
        ),
    ]
