# Generated by Django 6.0.6 on 2026-06-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0058_guildfaqitem_document_guildfaqitem_document_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityevent",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Does not repeat"),
                    ("semi_monthly", "Twice a month"),
                    ("monthly", "Every month"),
                    ("every_2_months", "Every 2 months"),
                    ("every_3_months", "Every 3 months"),
                    ("every_6_months", "Every 6 months"),
                    ("yearly", "Every year"),
                ],
                default="none",
                help_text="Whether and how often this event repeats. Every repeating option recurs on the same weekday-of-month as the start (e.g. the 2nd Saturday); 'Twice a month' adds the same weekday two weeks later.",
                max_length=20,
            ),
        ),
    ]
