# Generated by Django 6.0.6 on 2026-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0059_alter_communityevent_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="discord_linked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the member linked their Discord account for DM notifications (null = not linked).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="discord_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "The member's VERIFIED numeric Discord account id (snowflake), set when they link Discord via "
                    "OAuth. Used to DM them notifications through the FOG bot. Distinct from the unverified, "
                    "free-text discord_handle — never use that for delivery."
                ),
                max_length=32,
            ),
        ),
    ]
