# Generated by Django 6.0.6 on 2026-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0061_guild_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the guild is soft-deleted; hidden from voting, the directory, and every member-facing page.",
                null=True,
            ),
        ),
    ]
