# Generated by Django 6.0.6 on 2026-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0062_guild_deleted_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="guildstaffmembership",
            name="uq_guildstaff_guild_member_role",
        ),
        migrations.AddField(
            model_name="guildstaffmembership",
            name="custom_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A free-text officer title (e.g. 'Studio Technician') used instead of a preset role.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="guildstaffmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("co_lead", "Co-Guild Lead"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("orienter", "Orienter"),
                ],
                default="",
                help_text="A preset officer role. Leave blank when this entry uses a custom title instead.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="guildstaffmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", ""), models.Q(("custom_title", ""), _negated=True)),
                    models.Q(models.Q(("role", ""), _negated=True), ("custom_title", "")),
                    _connector="OR",
                ),
                name="ck_guildstaff_role_xor_custom_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="guildstaffmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", ""), _negated=True),
                fields=("guild", "member", "role"),
                name="uq_guildstaff_member_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="guildstaffmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_title", ""), _negated=True),
                fields=("guild", "member", "custom_title"),
                name="uq_guildstaff_member_custom_title",
            ),
        ),
    ]
