# Generated by Django 6.0.6 on 2026-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0063_remove_guildstaffmembership_uq_guildstaff_guild_member_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildannouncement",
            name="post_to_discord",
            field=models.BooleanField(
                default=True, help_text="Also post this announcement to the guild's own Discord channel."
            ),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="send_email",
            field=models.BooleanField(
                default=True, help_text="Also email this announcement to members who joined the guild."
            ),
        ),
    ]
