# Generated by Django 6.0.6 on 2026-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0064_guildannouncement_post_to_discord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="show_in_directory",
            field=models.BooleanField(
                default=True,
                help_text="Whether this member appears in the public member directory. New members are listed by default; they can opt out any time in profile settings.",
            ),
        ),
    ]
