# Generated by Django 6.0.6 on 2026-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0065_member_show_in_directory_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="welcome_dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When the member dismissed the first-login 'set up your profile' welcome modal "
                    "(null = not dismissed yet). Set once they act on it, so it never shows again."
                ),
                null=True,
            ),
        ),
    ]
