# Generated by Django 6.0.6 on 2026-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0066_member_welcome_dismissed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="faq_label",
            field=models.CharField(
                default="FAQ",
                help_text="Heading for this guild's FAQ / info section on the guild page — e.g. 'Ceramics Info'.",
                max_length=50,
            ),
        ),
    ]
