# Generated by Django 6.0.6 on 2026-07-03 13:55

import core.validators
import django.db.models.deletion
from django.db import migrations, models

# The two external Google Docs that lived in the sidebar footer (Member Guide + Code of
# Conduct). We fold them into the new Space & Org Info page so the footer links can be
# removed with zero content loss: the Code of Conduct becomes the page's external CoC
# link, and the Member Guide becomes an OrgLink in the page's Resources aside.
_CODE_OF_CONDUCT_URL = "https://docs.google.com/document/d/1avWCAnbwDbO79k-n-_QpUc0P2Dz-s6f4/edit"
_MEMBER_GUIDE_LABEL = "Member Guide"
_MEMBER_GUIDE_URL = "https://docs.google.com/document/d/1snMD2H2APfNR3MdwSmEuxTLIiTODHpefjJsLfb29HjQ/edit"


def seed_google_doc_links(apps, schema_editor):
    """Seed the singleton page with the two footer Google Docs so nothing is lost."""
    OrgInfoPage = apps.get_model("membership", "OrgInfoPage")
    OrgLink = apps.get_model("membership", "OrgLink")
    page, _created = OrgInfoPage.objects.get_or_create(pk=1)
    if not page.code_of_conduct_url:
        page.code_of_conduct_url = _CODE_OF_CONDUCT_URL
        page.save(update_fields=["code_of_conduct_url"])
    OrgLink.objects.get_or_create(
        page=page,
        label=_MEMBER_GUIDE_LABEL,
        url=_MEMBER_GUIDE_URL,
        defaults={"sort_order": 0},
    )


def unseed_google_doc_links(apps, schema_editor):
    """Reverse the seed: drop the Member Guide link and clear the seeded CoC URL."""
    OrgInfoPage = apps.get_model("membership", "OrgInfoPage")
    OrgLink = apps.get_model("membership", "OrgLink")
    OrgLink.objects.filter(label=_MEMBER_GUIDE_LABEL, url=_MEMBER_GUIDE_URL).delete()
    OrgInfoPage.objects.filter(pk=1, code_of_conduct_url=_CODE_OF_CONDUCT_URL).update(code_of_conduct_url="")


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0067_guild_faq_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgInfoPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hero_crop_x",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box left edge in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_y",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box top edge in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_w",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box width in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_h",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box height in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional hero banner across the top of the Space & Org Info page.",
                        upload_to="org/banner/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Welcome / overview blurb shown at the top of the page. Supports Markdown.",
                    ),
                ),
                (
                    "floorplan_image",
                    models.ImageField(
                        blank=True,
                        help_text="Annotated floor plan — guild locations, restrooms, emergency exits. Click-to-zoom on the page.",
                        upload_to="org/floorplan/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "floorplan_caption",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Caption shown under the map, e.g. 'Guild locations, restrooms, and emergency exits.'",
                        max_length=300,
                    ),
                ),
                (
                    "parking",
                    models.TextField(blank=True, default="", help_text="Parking & arrival info. Supports Markdown."),
                ),
                (
                    "who_to_contact",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Org structure / who's-who / who to contact for what. Supports Markdown (a list or headings).",
                    ),
                ),
                (
                    "code_of_conduct",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Code of conduct body. Supports Markdown. Leave blank to link out instead.",
                    ),
                ),
                (
                    "code_of_conduct_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional external Code of Conduct link, used only when the body above is blank.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this page was last edited.")),
            ],
            options={
                "verbose_name": "Space & Org Info Page",
                "verbose_name_plural": "Space & Org Info Page",
            },
        ),
        migrations.CreateModel(
            name="OrgLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="Display text, e.g. 'Member Guide'.", max_length=100)),
                ("url", models.URLField(help_text="Destination URL.")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Parent org-info page.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="membership.orginfopage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="OrgFAQItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(help_text="The question.", max_length=500)),
                ("answer", models.TextField(help_text="The answer.")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional YouTube link shown with this answer (watch, youtu.be, embed, or shorts URL).",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Optional document (PDF, Word, slides, spreadsheet…) shown with this answer. Leave blank to link an external doc instead.",
                        upload_to="org/faq/",
                        validators=[core.validators.validate_document],
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional link to an external doc for this answer. Leave blank if you uploaded a file.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Parent org-info page.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="membership.orginfopage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("document", ""), ("document_url", ""), _connector="OR"),
                        name="ck_orgfaqitem_doc_not_both",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_google_doc_links, unseed_google_doc_links),
    ]
