# Generated by Django 6.0.6 on 2026-07-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0070_guild_essential_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="When off, this guild's page is hidden from the public guilds site (guilds.pastlives.app) — members can still see it in the hub.",
            ),
        ),
    ]
