# Generated by Django 6.0.6 on 2026-07-04 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0071_guild_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guildannouncement",
            name="moderation_state",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("pending", "Pending review"),
                    ("changes_requested", "Changes requested"),
                    ("declined", "Declined"),
                ],
                default="published",
                help_text="Where this announcement is in the review flow. Leads/staff/admins post already Published; a member's proposal starts Pending until a lead or admin approves it.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="review_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The reviewer's note to the proposer (shown on a decline or a changes-requested).",
            ),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, help_text="When the review decision was recorded.", null=True),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The lead or admin who approved, declined, or requested changes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The member who proposed this announcement (for posts that went through review).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="When this announcement was last edited."),
        ),
    ]
