# Generated by Django 6.0.6 on 2026-07-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0072_guildannouncement_moderation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildannouncement",
            name="post_to_discord",
        ),
        migrations.AddField(
            model_name="guildannouncement",
            name="discord_channel",
            field=models.CharField(
                choices=[
                    ("guild", "Our Guild Channel"),
                    ("general", "#general-chat"),
                    ("leadership", "#leadership"),
                    ("none", "Don't post to Discord"),
                ],
                default="guild",
                help_text="Which Discord channel this announcement posted to (or 'none').",
                max_length=20,
            ),
        ),
    ]
