# Generated by Django 6.0.6 on 2026-07-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0073_remove_guildannouncement_post_to_discord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="onboarding_dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the member dismissed the home 'Get started' checklist card; null = never dismissed. Does NOT affect is_onboarded — only hides the card.",
                null=True,
            ),
        ),
    ]
