# Generated by Django 6.0.6 on 2026-07-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_events_published_idle(apps, schema_editor):
    """Belt-and-suspenders: mark every pre-existing event Published + not-yet-synced.

    The AddField defaults already stamp new columns with ``published`` / ``idle`` on
    every existing row, so this only re-affirms that state. ``idle`` (not ``pending``)
    matters: it keeps the retry job from ever mass-backfilling historical events to
    Google — a row opts into syncing only when it is next published or edited.
    """
    CommunityEvent = apps.get_model("membership", "CommunityEvent")
    CommunityEvent.objects.all().update(moderation_state="published", sync_state="idle")


def reverse_set_existing_events(apps, schema_editor):
    """Documented no-op reverse.

    There is nothing to restore: reversing this migration drops the very columns this
    data step wrote (``moderation_state`` / ``sync_state`` are removed by the AddField
    reversals below), so no prior value exists to put back. Written explicitly rather
    than using ``RunPython.noop`` so the intent is on the record.
    """
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0074_member_onboarding_dismissed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="google_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which Google calendar this event was pushed to (kept so a later edit/delete targets the right one).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="google_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Google Calendar event id returned when FOG pushed this event. Blank until pushed.",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="google_ical_uid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The pushed event's iCal UID (<id>@google.com), used to hide the echoed copy when the daily iCal read re-imports it.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="moderation_state",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("pending", "Pending review"),
                    ("changes_requested", "Changes requested"),
                    ("declined", "Declined"),
                ],
                default="published",
                help_text="Where this event is in the review flow. Leads/staff/admins create events already Published; member proposals start Pending.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="review_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The reviewer's note to the proposer (shown on a decline or a changes-requested).",
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, help_text="When the review decision was recorded.", null=True),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The lead or admin who approved, declined, or requested changes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The member who proposed this event (for events that went through review).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="sync_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why the last Google push failed (or why it's still pending, e.g. no calendar linked). Blank when synced.",
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="sync_state",
            field=models.CharField(
                choices=[("idle", "Not synced"), ("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                default="idle",
                help_text="Google Calendar sync status for this event.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="synced_at",
            field=models.DateTimeField(blank=True, help_text="When this event last synced to Google.", null=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="google_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This guild's Google Calendar ID for pushing FOG-created events out to Google (e.g. abc123@group.calendar.google.com). Find it in Google Calendar → Settings for that calendar → 'Integrate calendar' → Calendar ID. This is NOT the iCal URL above — leave blank to keep this guild's events in FOG only.",
                max_length=255,
            ),
        ),
        migrations.RunPython(set_existing_events_published_idle, reverse_set_existing_events),
    ]
