# Generated by Django 6.0.6 on 2026-07-11 02:34

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0075_communityevent_google_calendar_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideshowZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Where this screen lives, e.g. 'Woodshop' or 'Lobby'.", max_length=100),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the screen's URL: slideshow.pastlives.space/<slug>/. Point the monitor here once.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Turn a screen's URL on or off. A disabled zone's URL returns 404."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers sort first. The root URL redirects to the first enabled zone.",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SlideshowSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("custom", "Custom slide"), ("announcement", "Guild announcement")],
                        default="custom",
                        help_text="Custom = your own title/body/image. Guild announcement = mirror a published announcement.",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", help_text="Headline for a custom slide.", max_length=200),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Body text for a custom slide — a tip about the space, a reminder, etc.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional full-bleed image or flyer (JPG/PNG).",
                        null=True,
                        upload_to="signage/slides/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, default="", help_text="Optional link — shown as a QR code when 'Show QR' is on."
                    ),
                ),
                (
                    "show_qr",
                    models.BooleanField(default=False, help_text="Render a scannable QR of the link on this slide."),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long this slide shows. Leave blank to use the global default.",
                        null=True,
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, help_text="Optional: don't show before this date.", null=True),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, help_text="Optional: stop showing after this date.", null=True),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Turn this slide on or off without deleting it."),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Lower numbers show first in the rotation."),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The published announcement to mirror. Only used for 'Guild announcement' slides.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership.guildannouncement",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Show only on this screen. Leave blank to show on every screen.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="membership.slideshowzone",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
