# Generated by Django 6.0.7 on 2026-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0077_remove_slideshowslide_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="notify_happening_now",
            field=models.BooleanField(default=False, help_text="Ping members when it starts."),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When to announce this event. Leave blank to announce as soon as it's saved.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="remind_1d",
            field=models.BooleanField(default=False, help_text="Send members a reminder 1 day before it starts."),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="remind_3d",
            field=models.BooleanField(default=False, help_text="Send members a reminder 3 days before it starts."),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="remind_7d",
            field=models.BooleanField(default=False, help_text="Send members a reminder 7 days before it starts."),
        ),
        migrations.AlterField(
            model_name="communityevent",
            name="moderation_state",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending review"),
                    ("changes_requested", "Changes requested"),
                    ("declined", "Declined"),
                ],
                default="published",
                help_text="Where this event is in the review flow. Leads/staff/admins create events already Published; member proposals start Pending.",
                max_length=20,
            ),
        ),
    ]
