# Generated by Django 6.0.7 on 2026-07-12 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0078_communityevent_scheduling"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "audience",
                    models.CharField(
                        choices=[("site", "Everyone (site-wide)"), ("guild", "A specific guild")],
                        default="site",
                        help_text="Who hears it: everyone site-wide, or one guild's joined members.",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Subject / headline. Required even to save a draft (so the list row reads well).",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sanitized rich HTML. May be blank while drafting; required to send.",
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(
                        default=True,
                        help_text="Also send this announcement as a branded email (in-app bell fires regardless).",
                    ),
                ),
                (
                    "discord_channel",
                    models.CharField(
                        choices=[
                            ("guild", "Our Guild Channel"),
                            ("general", "#general-chat"),
                            ("leadership", "#leadership"),
                            ("none", "Don't post to Discord"),
                        ],
                        default="none",
                        help_text="Which Discord channel this echoes to (or 'none'). GUILD only for a guild audience.",
                        max_length=20,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        choices=[("none", "No ping"), ("here", "@here (online members)"), ("everyone", "@everyone")],
                        default="none",
                        help_text="Opt-in Discord ping — none, @here (online), or @everyone. Off by default.",
                        max_length=10,
                    ),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        help_text="Guild only: last day the materialized post shows. Blank = never; ignored for a site send.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the draft was first created.")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last edit — drives the resume-list ordering."),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on send. NULL = a resumable draft; non-null = an immutable sent record.",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Whose draft this is — drives the resume list and the send actor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target guild — set only when the audience is a specific guild.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_drafts",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["author", "sent_at"], name="idx_announcementdraft_author_sent")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("audience", "guild"), _negated=True), ("guild__isnull", False), _connector="OR"
                        ),
                        name="ck_announcementdraft_guild_audience",
                    )
                ],
            },
        ),
    ]
