# Generated by Django 6.0.7 on 2026-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0079_announcementdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementdraft",
            name="discord_channel",
            field=models.CharField(
                choices=[
                    ("guild", "Our Guild Channel"),
                    ("general", "#general-chat"),
                    ("leadership", "#leadership"),
                    ("officers", "#guild-officers"),
                    ("none", "Don't post to Discord"),
                ],
                default="none",
                help_text="Which Discord channel this echoes to (or 'none'). GUILD only for a guild audience.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="guildannouncement",
            name="discord_channel",
            field=models.CharField(
                choices=[
                    ("guild", "Our Guild Channel"),
                    ("general", "#general-chat"),
                    ("leadership", "#leadership"),
                    ("officers", "#guild-officers"),
                    ("none", "Don't post to Discord"),
                ],
                default="guild",
                help_text="Which Discord channel this announcement posted to (or 'none').",
                max_length=20,
            ),
        ),
    ]
