# Generated by Django 6.0.7 on 2026-07-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0080_alter_announcementdraft_discord_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Discord role id(s) assigned AND removed together when a member joins or leaves this guild in the app (outbound sync). A list of role-id strings — most guilds have one; a collapsed guild (e.g. Glass) keeps two roles in lockstep. Empty disables outbound role sync for this guild. Asymmetry to note: outbound assigns EVERY id listed here, while inbound (a member's Discord reaction) accepts ANY emoji mapped to the guild.",
            ),
        ),
        migrations.AddField(
            model_name="guildmembership",
            name="source",
            field=models.CharField(
                choices=[("app", "In-app join"), ("discord", "Discord reaction")],
                default="app",
                help_text="How this membership was created: an in-app join (app) or a Discord-reaction mirror (discord). Inbound reaction sync only ever adds/removes 'discord' rows and never touches 'app' rows — this is what keeps the two directions from fighting.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DiscordGuildEmoji",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "emoji",
                    models.CharField(
                        help_text="The reaction emoji on the Discord role message: a unicode character (e.g. 🔥) or a custom emoji as name:id (e.g. PrisonOutreach:123456789). A member who reacts with this joins the guild below. Many emojis may point at one guild (collapsed guilds).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="The guild a reaction with this emoji joins the member to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_emojis",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["guild__name", "emoji"],
                "constraints": [models.UniqueConstraint(fields=("emoji",), name="uq_discordguildemoji_emoji")],
            },
        ),
    ]
