# Generated by Django 6.0.7 on 2026-07-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0081_guild_discord_role_ids_guildmembership_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguildemoji",
            name="emoji",
            field=models.CharField(
                help_text="The reaction emoji on the Discord role message: a unicode character (e.g. 🔥) or a custom emoji as name:id (e.g. PrisonOutreach:123456789). A member who reacts with this joins the guild below. Many emojis may point at one guild (collapsed guilds).",
                max_length=64,
            ),
        ),
    ]
