# Generated by Django 6.0.6 on 2026-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_rename_general_to_member_google_calendar_id"),
        ("membership", "0082_alter_discordguildemoji_emoji"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="calendarevent",
            name="uq_calendarevent_guild_feed_uid",
        ),
        migrations.RemoveField(
            model_name="guild",
            name="google_calendar_id",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Occurrence start (ISO) for one instance of a recurring feed event, so each repeat is its own row. Blank for a one-off event.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="google_calendar_target",
            field=models.CharField(
                choices=[("member", "Member calendar"), ("public", "Public calendar")],
                default="member",
                help_text="Which Google calendar this event syncs to when Google sync is on — the members-only or the public one.",
                max_length=10,
                verbose_name="Which calendar",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarevent",
            constraint=models.UniqueConstraint(
                fields=("guild", "feed", "uid", "recurrence_id"), name="uq_calendarevent_guild_feed_uid"
            ),
        ),
    ]
