# Generated by Django 6.0.6 on 2026-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0083_calendar_recurrence_and_member_public_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildstaffmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("co_lead", "Guild Lead"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("orienter", "Orientator"),
                ],
                default="",
                help_text="A preset officer role. Leave blank when this entry uses a custom title instead.",
                max_length=20,
            ),
        ),
    ]
