# Generated by Django 6.0.7 on 2026-07-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0084_alter_guildstaffmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="instructor_bio",
            field=models.TextField(
                blank=True,
                help_text="Teaching bio shown on the public instructor page — separate from the member-directory bio.",
            ),
        ),
        migrations.CreateModel(
            name="MemberContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        help_text="What to call this contact, e.g. 'Website' or 'Instagram'.", max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The contact itself — an email, URL, handle, or free text.", max_length=255
                    ),
                ),
                (
                    "show_in_directory",
                    models.BooleanField(default=True, help_text="Show this contact on the member's directory card."),
                ),
                (
                    "show_on_instructor_page",
                    models.BooleanField(
                        default=False, help_text="Show this contact on the member's public instructor page."
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member this contact belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
