# Generated by Django 6.0.7 on 2026-07-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0086_fold_member_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="instructor_social_handle",
        ),
        migrations.RemoveField(
            model_name="member",
            name="instructor_website",
        ),
        migrations.RemoveField(
            model_name="member",
            name="other_contact_info",
        ),
        migrations.AlterField(
            model_name="member",
            name="directory_visibility",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field public/hidden flags for the member directory card. Keys: pronouns, phone, email, discord_handle, about_me, profile_photo, skills. Missing key means public (default-on).",
            ),
        ),
    ]
