# Generated by Django 6.0.7 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0087_remove_member_instructor_social_handle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="can_self_approve_discounts",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When on, this member may approve (activate) their own discount codes without waiting for "
                    "an admin. Granted per-member from the Manage Members page. Admins can approve anyone's codes."
                ),
            ),
        ),
    ]
