# Generated by Django 6.0.7 on 2026-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0088_member_can_self_approve_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This guild's Discord channel id (right-click the channel → Copy Channel ID with Developer Mode on). When a member runs a guild slash command in this channel, we know which guild they mean. This is NOT the webhook URL above — leave blank if you don't use channel auto-detection.",
                max_length=32,
            ),
        ),
    ]
