# Generated by Django 6.0.7 on 2026-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0090_studio_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="discord_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Discord Scheduled Event id returned when FOG pushed this event to the server's Events. Blank until pushed.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="discord_pushed_occurrence",
            field=models.DateTimeField(
                blank=True,
                help_text="For an unmappable-cadence event pushed to Discord as a single event, the start of the occurrence currently live there — so the nightly roll-forward knows when it has passed. Blank for one-off and natively-recurring events.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="discord_sync_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why the last Discord push failed (or why it's still pending, e.g. sync off). Blank when synced.",
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="discord_sync_state",
            field=models.CharField(
                choices=[("idle", "Not synced"), ("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                default="idle",
                help_text="Discord Events sync status for this event (independent of the Google sync state).",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="discord_synced_at",
            field=models.DateTimeField(blank=True, help_text="When this event last synced to Discord.", null=True),
        ),
    ]
