# Generated by Django 6.0.7 on 2026-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0092_remove_guild_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_welcome_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown to the member in Discord (their private confirmation) and posted in your guild's Discord channel when someone joins via /join-guild. This is separate from your guild Welcome email. Write it in your voice (a lead's welcome). Blank uses a generic welcome.",
            ),
        ),
    ]
