# Generated by Django 6.0.7 on 2026-07-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0093_guild_discord_welcome_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildMailingListEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="A non-member email address that also receives this guild's announcement emails.",
                        max_length=254,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional — who this is (e.g. 'Front desk', 'Partner org').",
                        max_length=100,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="The guild whose announcements this address receives.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_list_emails",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("guild", "email"), name="uq_guildmailinglistemail_guild_email")
                ],
            },
        ),
    ]
