# Generated by Django 6.0.7 on 2026-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0094_guildmailinglistemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="email_recipient_selection",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Which recipients get this announcement\'s email. Empty/absent = everyone (default). Shape: {"users": [pk, …], "custom": ["addr", …]}.',
            ),
        ),
    ]
