# Generated by Django 6.0.3 on 2026-07-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0095_announcementdraft_email_recipient_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="discord_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord Scheduled Event id mirroring this feed event; blank when not pushed.",
                max_length=32,
            ),
        ),
    ]
