# Generated by Django 6.0.6 on 2026-07-21 14:29
"""Add ``channel_announced_at`` to CalendarEvent + CommunityEvent, backfilled to *now* on
every existing row so the first enabled announcer run doesn't flood #public-calendar with
hundreds of historical events. Rows created after this migration start NULL and get
announced (or silently stamped) by the 15-minute ``announce_calendar_events`` job.
"""

from django.db import migrations, models
from django.utils import timezone


def mark_existing_rows_announced(apps, schema_editor):
    """Stamp every pre-existing event as already announced (migration-run time)."""
    now = timezone.now()
    CalendarEvent = apps.get_model("membership", "CalendarEvent")
    CommunityEvent = apps.get_model("membership", "CommunityEvent")
    CalendarEvent.objects.filter(channel_announced_at__isnull=True).update(channel_announced_at=now)
    CommunityEvent.objects.filter(channel_announced_at__isnull=True).update(channel_announced_at=now)


def unmark_existing_rows(apps, schema_editor):
    """Reverse: clear the stamp everywhere (the fields are dropped right after anyway)."""
    CalendarEvent = apps.get_model("membership", "CalendarEvent")
    CommunityEvent = apps.get_model("membership", "CommunityEvent")
    CalendarEvent.objects.update(channel_announced_at=None)
    CommunityEvent.objects.update(channel_announced_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0096_calendarevent_discord_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="channel_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this event was announced (or silently marked announced) in the Discord calendar "
                    "channel. NULL = not yet announced; the 15-minute announcer picks it up."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="channel_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this event was announced (or silently marked announced) in the Discord calendar "
                    "channel. NULL = not yet announced; the 15-minute announcer picks it up once published."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(mark_existing_rows_announced, unmark_existing_rows),
    ]
