# Generated by Django 6.0.7 on 2026-07-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0097_calendarevent_channel_announced_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordLinkNudge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "discord_user_id",
                    models.CharField(
                        help_text="The Discord account id (snowflake) of the reactor who was nudged to link their Past Lives account. One nudge ever per Discord user.",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the nudge DM was sent (or skipped because the user's DMs are closed).",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("discord_user_id",), name="uq_discordlinknudge_discord_user_id")
                ],
            },
        ),
    ]
