# Generated by Django 6.0.7 on 2026-07-23 02:49

import core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0098_discordlinknudge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Floorplan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Floor label shown on the map's floor switcher — e.g. 'Floor 1' or '2nd Floor'.",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="This floor's map image. Normalized to the hero long edge so annotations stay legible when zoomed.",
                        upload_to="org/floorplans/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ascending — lower numbers show first (left-most on the floor switcher)."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="When on, this floor appears on the public map. Draft floors are editor-only.",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", help_text="Optional line shown under this floor's map.", max_length=300
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this floor was added.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this floor was last edited.")),
            ],
            options={
                "verbose_name": "Floor plan",
                "verbose_name_plural": "Floor plans",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MapHotspot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "shape",
                    models.CharField(
                        choices=[("region", "Region (rectangle)"), ("pin", "Pin (labelled dot)")],
                        default="region",
                        help_text="A region is a clickable rectangle; a pin is a small labelled dot.",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("studio", "Studio (leasable)"),
                            ("cubby", "Cubby / shelf"),
                            ("facility", "Facility / shop"),
                            ("info", "Info marker"),
                            ("restroom", "Restroom"),
                            ("exit", "Emergency exit"),
                            ("meeting_room", "Meeting room"),
                            ("event_space", "Event space"),
                        ],
                        default="studio",
                        help_text="What this marker is — drives its colour and which action members see.",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Marker text for facility/info markers — e.g. 'Wood Shop'. Ignored when a space is linked.",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional blurb shown in this marker's detail panel."
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Horizontal position as a percent of the image width (region: left edge; pin: centre).",
                        max_digits=5,
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Vertical position as a percent of the image height (region: top edge; pin: centre).",
                        max_digits=5,
                    ),
                ),
                (
                    "w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Region width as a percent of the image width. Blank for pins.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Region height as a percent of the image height. Blank for pins.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ascending — orders the accessible list and breaks ties for stacking."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this marker was added.")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this marker was last edited or moved."),
                ),
                (
                    "floorplan",
                    models.ForeignKey(
                        help_text="The floor this marker sits on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspots",
                        to="membership.floorplan",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        help_text="The space this marker represents. Leave blank for facility/info markers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotspots",
                        to="membership.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Map marker",
                "verbose_name_plural": "Map markers",
                "ordering": ["floorplan__sort_order", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SpaceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("lease", "Studio lease"), ("cubby", "Cubby / shelf")],
                        default="lease",
                        help_text="Whether this is a studio lease ask or a cubby/shelf ask. Sets who reviews it.",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="Where this request is in review.",
                        max_length=12,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note from the member — shown to the reviewer and carried into the notification.",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, help_text="When the decision was recorded.", null=True),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, default="", help_text="The reviewer's reason. Required for a decline."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the member sent this request.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this request last changed.")),
                (
                    "hotspot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which map marker the member clicked. Provenance only — the space is the real target.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="membership.maphotspot",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="The member who asked for this space.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_requests",
                        to="membership.member",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved or declined this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        help_text="The space being requested. Price and owning guild are read from it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="membership.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Space request",
                "verbose_name_plural": "Space requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="maphotspot",
            index=models.Index(fields=["floorplan", "sort_order"], name="idx_maphotspot_floor_order"),
        ),
        migrations.AddIndex(
            model_name="maphotspot",
            index=models.Index(fields=["space"], name="idx_maphotspot_space"),
        ),
        migrations.AddConstraint(
            model_name="maphotspot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("shape", "region"), ("w__isnull", False), ("h__isnull", False)),
                    models.Q(("shape", "pin"), ("w__isnull", True), ("h__isnull", True)),
                    _connector="OR",
                ),
                name="ck_maphotspot_region_has_dims",
            ),
        ),
        migrations.AddIndex(
            model_name="spacerequest",
            index=models.Index(fields=["state", "created_at"], name="idx_spacerequest_state_created"),
        ),
        migrations.AddIndex(
            model_name="spacerequest",
            index=models.Index(fields=["space", "state"], name="idx_spacerequest_space_state"),
        ),
        migrations.AddConstraint(
            model_name="spacerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "pending")),
                fields=("requester", "space"),
                name="uq_spacerequest_one_pending_per_member_space",
            ),
        ),
    ]
