# Generated by Django 6.0.7 on 2026-07-23 05:35

import core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0099_floorplan_maphotspot_spacerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="aspect_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.50"),
                help_text="Shape of the drawn floor, width divided by height — 1.50 is half again as wide as it is tall.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.10")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional reference underlay shown faintly behind the drawn rooms — handy when tracing a scanned plan. The map renders perfectly well without one.",
                upload_to="org/floorplans/",
                validators=[core.validators.validate_image_size],
            ),
        ),
    ]
