# Generated by Django 6.0.7 on 2026-07-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0100_floorplan_aspect_ratio_alter_floorplan_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Guide heading, e.g. 'Guild voting'.", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL anchor for deep links. Auto-filled from the title when left blank.",
                        max_length=220,
                    ),
                ),
                ("body", models.TextField(help_text="The guide body. Supports Markdown.")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Order on the page; lower shows first."),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Uncheck to keep a draft off the public page while writing."
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Parent Wiki page (the singleton).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="membership.orginfopage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "constraints": [models.UniqueConstraint(fields=("page", "slug"), name="uq_wikiarticle_page_slug")],
            },
        ),
    ]
