# Generated by Django 6.0.7 on 2026-07-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0101_wikiarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="maphotspot",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link this marker to a guild's page (e.g. a shop that is a guild's home).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="maphotspot",
            name="kind",
            field=models.CharField(
                choices=[
                    ("studio", "Studio (leasable)"),
                    ("cubby", "Shelf"),
                    ("facility", "Facility / shop"),
                    ("info", "Info marker"),
                    ("restroom", "Restroom"),
                    ("exit", "Emergency exit"),
                    ("meeting_room", "Meeting room"),
                    ("event_space", "Event space"),
                ],
                default="studio",
                help_text="What this marker is — drives its colour and which action members see.",
                max_length=20,
            ),
        ),
    ]
