# Generated by Django 6.0.7 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0102_maphotspot_guild_alter_maphotspot_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maphotspot",
            name="kind",
            field=models.CharField(
                choices=[
                    ("studio", "Studio (leasable)"),
                    ("cubby", "Shelf"),
                    ("facility", "Facility / shop"),
                    ("info", "Info marker"),
                    ("restroom", "Restroom"),
                    ("exit", "Emergency exit"),
                    ("meeting_room", "Meeting room"),
                    ("event_space", "Event space"),
                    ("wall", "Wall"),
                ],
                default="studio",
                help_text="What this marker is — drives its colour and which action members see.",
                max_length=20,
            ),
        ),
    ]
