# Generated by Django 6.0.7 on 2026-07-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0104_seed_floor_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingsettings",
            name="send_officer_reminder_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch for the 'Officer heads-up' turnout reminder to guild leadership before close.",
            ),
        ),
    ]
