# Generated by Django 6.0.7 on 2026-08-10 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0105_votingsettings_send_officer_reminder_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Category name shown on the Help landing page, e.g. 'Running a guild'.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL segment (/help/<slug>/). Auto-filled from the name; stable once set.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("member", "Members"),
                            ("guild_lead", "Guild leads & staff"),
                            ("instructor", "Instructors"),
                            ("admin", "Admins"),
                        ],
                        default="member",
                        help_text="Who this category is for — groups it on the landing page and drives the badge.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One-liner under the name on the landing card.",
                        max_length=300,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order within its audience group; lower shows first."
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="wikiarticle",
            name="related_articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hand-picked guides shown under 'Related guides'. Same-category guides fill any remaining slots automatically.",
                related_name="related_to",
                to="membership.wikiarticle",
            ),
        ),
        migrations.AddField(
            model_name="wikiarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this guide lives in the help center. Uncategorized guides don't appear on the landing grid.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="membership.helpcategory",
            ),
        ),
    ]
