# Generated by Django 6.0.7 on 2026-08-11 19:19

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0105_votingsettings_send_officer_reminder_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_special",
                    models.BooleanField(
                        default=False,
                        help_text="Off = the regular Monthly meeting. On = a named special meeting (Emergency, Planning…).",
                    ),
                ),
                (
                    "special_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the special meeting, e.g. 'Emergency'. Blank shows as 'Special'.",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        help_text="Draft = editable workspace. Approved = locked minutes of record.",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True,
                        help_text="The day of the meeting. Blank until scheduled — a meeting can be drafted first.",
                        null=True,
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time. Always a half-hour value from the shared dropdown; blank = time TBD.",
                        null=True,
                    ),
                ),
                (
                    "video_call_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Video call link (Meet, Zoom…). Shown as a 'Join meeting' button wherever the meeting appears.",
                    ),
                ),
                (
                    "special_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sanitized HTML. The top-of-page notes box — context everyone should read before the meeting.",
                    ),
                ),
                (
                    "other_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sanitized HTML. Off-agenda discussion recorded at the bottom of the page.",
                    ),
                ),
                (
                    "event_occurrence",
                    models.DateField(
                        blank=True,
                        help_text="Which occurrence of a recurring event this meeting is — recurring events expand virtually, so the date pins it.",
                        null=True,
                    ),
                ),
                (
                    "owns_event",
                    models.BooleanField(
                        default=False,
                        help_text="On when the linked event was created from this workspace: it deletes with the meeting and follows date/time changes. Off for a pre-existing event that was merely linked.",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the minutes were approved. Re-approving after an admin unlock re-stamps this.",
                        null=True,
                    ),
                ),
                (
                    "legacy_note_id",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="PK of the GuildMeetingNote this row was migrated from; migration bookkeeping only.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved (locked) the minutes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created the meeting.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The calendar event this meeting rides for Google/Discord sync and reminders.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="membership.communityevent",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this meeting belongs to. Blank = the cross-guild council (guild leads) meeting.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAgendaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The topic. Blank right after '+ Add item' — fill it in place.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Plain text. What this item is about — the 'agenda' half."
                    ),
                ),
                (
                    "minutes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sanitized HTML (Quill). What was discussed/decided — the 'minutes' half.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position on the agenda; the up/down buttons swap these."
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="Parent meeting.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="membership.meeting",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member whose approved proposal created this item; shown as a credit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MeetingActionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The task, e.g. 'Order more 80-grit sandpaper'.",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("done", "Done"), ("dismissed", "Dismissed")],
                        default="open",
                        help_text="Open items carry over to the next meeting until done or dismissed.",
                        max_length=20,
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False, help_text="Red priority flag.")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, help_text="When it was completed or dismissed.", null=True),
                ),
                (
                    "closed_in",
                    models.ForeignKey(
                        blank=True,
                        help_text="The meeting whose carryover panel closed it (blank when closed in its own meeting).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.meeting",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The agenda topic this action came out of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="membership.meetingagendaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What to call this — e.g. 'Agenda PDF'. Defaults to the file name or link.",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a document (PDF, Word, slides, spreadsheet…). Leave blank if you're adding a link instead.",
                        upload_to="meetings/attachments/",
                        validators=[core.validators.validate_document],
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to an external doc (e.g. a Google Doc). Leave blank if you uploaded a file instead.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="Parent meeting.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="membership.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of a non-member guest. Blank when a roster member is picked.",
                        max_length=120,
                    ),
                ),
                ("present", models.BooleanField(default=True, help_text="Off = marked absent (shown struck through).")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="Parent meeting.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="membership.meeting",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="A roster member. Blank when this row is a free-text guest.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MeetingItemProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="The topic the member wants on the agenda.", max_length=200)),
                (
                    "why",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why it matters / what needs deciding. Becomes the item's description on approval.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="Pending until leadership decides.",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, help_text="When the decision was recorded.", null=True),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note back to the proposer (why declined, or what was tweaked).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_item",
                    models.OneToOneField(
                        blank=True,
                        help_text="The agenda item an approval created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_proposal",
                        to="membership.meetingagendaitem",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="The upcoming meeting this item is proposed for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="membership.meeting",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        help_text="Who proposed it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who decided.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["guild", "-scheduled_date"], name="idx_meeting_guild_date"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(condition=models.Q(("status", "draft")), fields=["status"], name="idx_meeting_draft"),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_special", True), ("special_title", ""), _connector="OR"),
                name="ck_meeting_special_title_only_when_special",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legacy_note_id__isnull", False)),
                fields=("legacy_note_id",),
                name="uq_meeting_legacy_note",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingactionitem",
            index=models.Index(
                condition=models.Q(("status", "open")), fields=["status"], name="idx_meetingactionitem_open"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("file", ""), models.Q(("url", ""), _negated=True)),
                    models.Q(models.Q(("file", ""), _negated=True), ("url", "")),
                    _connector="OR",
                ),
                name="ck_meetingattachment_file_xor_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingattendee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("member__isnull", False), ("guest_name", "")),
                    models.Q(("member__isnull", True), models.Q(("guest_name", ""), _negated=True)),
                    _connector="OR",
                ),
                name="ck_meetingattendee_member_xor_guest",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingattendee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", False)),
                fields=("meeting", "member"),
                name="uq_meetingattendee_meeting_member",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingitemproposal",
            index=models.Index(
                condition=models.Q(("state", "pending")), fields=["state"], name="idx_meetingproposal_pending"
            ),
        ),
    ]
