# Generated by Django 6.0.7 on 2026-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0106_helpcategory_wikiarticle_related_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingsettings",
            name="auto_snapshot_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch for the automated cycle-end snapshot, which also auto-emails the results (voters get their own ballot recap).",
            ),
        ),
    ]
