# Generated by Django 6.0.7 on 2026-08-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0107_alter_votingsettings_auto_snapshot_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="guided_tours_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, tours are never auto-offered. Manual starts from the Help page still work.",
            ),
        ),
    ]
