# Generated by Django 6.0.7 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0108_member_guided_tours_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="instructor_oriented_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the member completed the instructor orientation (or an admin granted teaching access); null = teaching portal locked. Cleared when an admin revokes access.",
                null=True,
            ),
        ),
    ]
