# Generated by Django 6.0.7 on 2026-08-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0112_migrate_meeting_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpcategory",
            name="audience",
            field=models.CharField(
                choices=[
                    ("member", "Members"),
                    ("developer", "Developers"),
                    ("guild_lead", "Guild leads & staff"),
                    ("instructor", "Instructors"),
                    ("admin", "Admins"),
                ],
                default="member",
                help_text="Who this category is for — groups it on the landing page and drives the badge.",
                max_length=20,
            ),
        ),
    ]
