# Generated by Django 6.0.7 on 2026-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0113_alter_helpcategory_audience"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordJoinWelcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "discord_user_id",
                    models.CharField(
                        help_text="The Discord account id (snowflake) of the server joiner who was sent the one-time welcome DM. One welcome ever per Discord user.",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the welcome DM was sent (or skipped because the user's DMs are closed).",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("discord_user_id",), name="uq_discordjoinwelcome_discord_user_id")
                ],
            },
        ),
    ]
