# Generated by Django 6.0.7 on 2026-08-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0114_meetingagendaitem_upvoters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("approved", "Approved")],
                default="draft",
                help_text="Draft = editable workspace. Published = agenda finalised, visible. Approved = locked minutes of record.",
                max_length=20,
            ),
        ),
    ]
