# Generated by Django 6.0.7 on 2026-08-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0115_add_meeting_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementdraft',
            name='mark_as_urgent',
            field=models.BooleanField(default=False, help_text='Sends the email as transactional, overriding user email preferences.'),
        ),
    ]
