# Generated by Django 6.0.7 on 2026-08-13 04:14

from django.db import migrations, models


def enable_thankyou_for_existing_guilds(apps, schema_editor):
    """Turn the thank-you email on for every existing guild (now on by default)."""
    GuildOrientationSettings = apps.get_model("membership", "GuildOrientationSettings")
    GuildOrientationSettings.objects.filter(thankyou_email_enabled=False).update(thankyou_email_enabled=True)


def disable_standard_thankyou(apps, schema_editor):
    """Reverse: turn the thank-you back off for guilds that never wrote their own copy.

    Guild-authored thank-yous (a custom subject or body present) are left enabled, so the
    reverse restores the pre-migration intent without discarding anyone's written email.
    """
    GuildOrientationSettings = apps.get_model("membership", "GuildOrientationSettings")
    GuildOrientationSettings.objects.filter(thankyou_email_subject="", thankyou_email_body="").update(
        thankyou_email_enabled=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0116_announcementdraft_mark_as_urgent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildorientationsettings",
            name="thankyou_email_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Send a thank-you / next-steps email once an orientation is completed. On by "
                    "default; leave the subject and body blank to send the standard thank-you, or "
                    "write your own."
                ),
            ),
        ),
        migrations.RunPython(enable_thankyou_for_existing_guilds, disable_standard_thankyou),
    ]
