# Generated by Django 6.0.7 on 2026-08-13 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The full set of capabilities, granted to every current admin on rollout so no
# admin silently loses a notification they used to receive as a blanket recipient.
_ALL_CAPABILITIES = (
    "class_approver",
    "space_approver",
    "discount_approver",
    "events_approver",
    "billing_approver",
)


def _backfill_admin_capabilities(apps, schema_editor):
    """Grant every current ``fog_role='admin'`` member every capability.

    Preserves the pre-rollout reality — where all-admin blasts reached every admin —
    so nobody loses a notification the day capability routing goes live. New admins
    added later are assigned capabilities deliberately in the member edit UI.
    """
    Member = apps.get_model("membership", "Member")
    AdminCapability = apps.get_model("membership", "AdminCapability")
    rows = [
        AdminCapability(member=member, capability=capability)
        for member in Member.objects.filter(fog_role="admin").iterator()
        for capability in _ALL_CAPABILITIES
    ]
    AdminCapability.objects.bulk_create(rows, ignore_conflicts=True)


def _remove_admin_capabilities(apps, schema_editor):
    """Reverse: drop every capability row (the table is fully backfill-seeded)."""
    AdminCapability = apps.get_model("membership", "AdminCapability")
    AdminCapability.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0117_thankyou_email_on_by_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCapability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("class_approver", "Class Administrator"),
                            ("space_approver", "Space & Cubby Administrator"),
                            ("discount_approver", "Discount Code Administrator"),
                            ("events_approver", "Calendar Administrator"),
                            ("billing_approver", "Billing Administrator"),
                        ],
                        help_text="Which scoped admin authority this grant confers.",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this capability was granted.")),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who granted this capability (audit; nulled if they're deleted).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member granted this capability.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_capabilities",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["member__full_legal_name", "capability"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "capability"), name="uq_admincapability_member_capability"
                    )
                ],
            },
        ),
        migrations.RunPython(_backfill_admin_capabilities, _remove_admin_capabilities),
    ]
