# Generated by Django 6.0.7 on 2026-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0118_admincapability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildstaffmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("co_lead", "Co-Lead"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("orienter", "Orientator"),
                ],
                default="",
                help_text="A preset officer role. Leave blank when this entry uses a custom title instead.",
                max_length=20,
            ),
        ),
    ]
