# Generated by Django 6.0.7 on 2026-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0119_alter_guildstaffmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="scheduled_end_time",
            field=models.TimeField(
                blank=True,
                help_text="End time. A half-hour value from the shared dropdown; blank = a default length on the calendar.",
                null=True,
            ),
        ),
    ]
