# Generated by Django 6.0.7 on 2026-08-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0120_meeting_scheduled_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="donate_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link where people can donate to this guild directly. Shown as a Donate button on the Wishlist tab.",
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="wishlist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Things this guild is hoping to receive as donations — tools, materials, equipment. Shown on a Wishlist tab on the guild page. Markdown is supported.",
            ),
        ),
    ]
