# Generated by Django 6.0.7 on 2026-08-15 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0121_guild_donate_url_guild_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingitemproposal",
            name="carried_to",
            field=models.OneToOneField(
                blank=True,
                help_text="The fresh proposal this was carried forward into, once the scope's next agenda exists.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carried_from",
                to="membership.meetingitemproposal",
            ),
        ),
        migrations.AlterField(
            model_name="meetingitemproposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("withdrawn", "Withdrawn"),
                    ("carried_over", "Carried Over"),
                    ("tabled", "Tabled"),
                ],
                default="pending",
                help_text="Pending until leadership decides.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="meetingitemproposal",
            index=models.Index(
                condition=models.Q(("state", "carried_over")), fields=["state"], name="idx_meetingproposal_carried_over"
            ),
        ),
    ]
