# Generated by Django 6.0.7 on 2026-08-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0122_meetingitemproposal_carried_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link members click to join this event online (e.g. a Google Meet, Zoom, or Jitsi URL). Paste a link you created under your own account so the meeting carries your own video-call features.",
                max_length=500,
            ),
        ),
    ]
