# Generated by Django 6.0.8 on 2026-08-18 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0052_update_cancellation_policy_copy'),
        ('membership', '0123_communityevent_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementdraft',
            name='class_offering',
            field=models.ForeignKey(blank=True, help_text='The target class — set only when the audience is a class you teach.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_drafts', to='classes.classoffering'),
        ),
        migrations.AlterField(
            model_name='announcementdraft',
            name='audience',
            field=models.CharField(choices=[('site', 'Everyone (site-wide)'), ('guild', 'A specific guild'), ('class', 'A class you teach')], default='site', help_text="Who hears it: everyone site-wide, or one guild's joined members.", max_length=10),
        ),
        migrations.AddConstraint(
            model_name='announcementdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'class'), _negated=True), ('class_offering__isnull', False), _connector='OR'), name='ck_announcementdraft_class_audience'),
        ),
    ]
