# Generated by Django 6.0.7 on 2026-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0126_alter_announcementdraft_mention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcementdraft",
            name="email_recipient_selection",
        ),
        migrations.AddField(
            model_name="announcementdraft",
            name="discord_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Also post this announcement to Discord (the channel is chosen on the preview step).",
            ),
        ),
        migrations.AddField(
            model_name="announcementdraft",
            name="push_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Also send this announcement as a phone push notification (in-app bell fires regardless).",
            ),
        ),
        migrations.AddField(
            model_name="announcementdraft",
            name="recipient_selection",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Which members get this announcement (in-app bell + push + email). Empty/absent = everyone in the audience (default). Shape: {"users": [pk, …], "custom": ["addr", …]}, where custom addresses are email-only extras (a guild mailing list).',
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="discord_channel_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The '#channel' name this guild's announcement webhook posts to, shown in the announcement composer's channel picker. Auto-filled by 'manage.py sync_guild_discord_channels' (fetched from Discord via the webhook); blank falls back to a generic label.",
                max_length=100,
            ),
        ),
    ]
