# Generated by Django 6.0.7 on 2026-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0127_remove_announcementdraft_email_recipient_selection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="show_sender",
            field=models.BooleanField(
                default=True, help_text="Show a 'From <sender>' line in the announcement email (never in push)."
            ),
        ),
    ]
