# Generated by Django 6.0.8 on 2026-08-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0128_announcementdraft_show_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="include_waitlist",
            field=models.BooleanField(
                default=False,
                help_text="Class announcements only: also notify waitlisted registrants, not just confirmed ones.",
            ),
        ),
    ]
