# Generated by Django 6.0.7 on 2026-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0129_announcementdraft_include_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="hide_from_directory",
            field=models.BooleanField(
                default=False,
                help_text="Ops-only override: never list this member in the member directory, even when their role (admin, officer, guild lead, instructor) would normally force-list them. Used for the Help Center's example/demo accounts. Set via shell/admin, not member-editable.",
            ),
        ),
    ]
