# Generated by Django 6.0.7 on 2026-08-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0130_member_hide_from_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercontact",
            name="kind",
            field=models.CharField(
                choices=[("website", "Website"), ("social", "Social"), ("other", "Other")],
                default="other",
                help_text="Which profile section this shows under: Website, Social, or Other (booking email, phone number, etc.).",
                max_length=20,
            ),
        ),
    ]
