# Generated by Django 6.0.7 on 2026-08-20 01:59

from django.db import migrations, models
from django.utils import timezone


def _mark_existing_members_welcomed(apps, schema_editor):
    """Stamp every pre-existing member as already-welcomed so the ``welcome_new_members``
    automation never emails the standing backlog when it is first switched on. Only members
    added after this migration (blank ``welcome_email_sent_at``) are eligible for the welcome
    email."""
    Member = apps.get_model("membership", "Member")
    Member.objects.filter(welcome_email_sent_at__isnull=True).update(welcome_email_sent_at=timezone.now())


def _unmark_members_welcomed(apps, schema_editor):
    """Reverse the backfill: clear the send stamp (returning to the pre-migration state where no
    member had been welcomed by this automation)."""
    Member = apps.get_model("membership", "Member")
    Member.objects.update(welcome_email_sent_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0130_member_hide_from_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="welcome_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the automated new-member welcome email was sent. Set once so the welcome automation never emails the same member twice; blank means not yet welcomed.",
                null=True,
            ),
        ),
        migrations.RunPython(_mark_existing_members_welcomed, _unmark_members_welcomed),
    ]
