# Generated by Django 6.0.7 on 2026-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0132_backfill_membercontact_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="Member said yes to being contacted about Past Lives marketing opportunities that highlight their art/business (Instagram, website, email newsletter, etc.). Private — never shown on the directory card.",
            ),
        ),
    ]
