# Generated by Django 6.0.7 on 2026-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0133_member_marketing_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the member self-service-deletes their account (anonymize + lock, never a hard delete). Distinct from status=FORMER, which an admin can set for many other reasons. Not filtered by the default manager (see PR rationale).",
                null=True,
            ),
        ),
    ]
