# Generated by Django 6.0.7 on 2026-08-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0134_member_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityEventDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="The event name, mirroring CommunityEvent.title.", max_length=200),
                ),
                (
                    "starts_at",
                    models.DateTimeField(help_text="Form-cleaned aware start (validated before the draft is written)."),
                ),
                (
                    "ends_at",
                    models.DateTimeField(help_text="Form-cleaned aware end (validated before the draft is written)."),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="", help_text="Where it happens, if given.", max_length=200),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, default="", help_text="Online join link, if given.", max_length=500),
                ),
                ("description", models.TextField(blank=True, default="", help_text="The details option's free text.")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Does not repeat"),
                            ("weekly", "Every week"),
                            ("semi_monthly", "Twice a month"),
                            ("monthly", "Every month"),
                            ("every_2_months", "Every 2 months"),
                            ("every_3_months", "Every 3 months"),
                            ("every_6_months", "Every 6 months"),
                            ("yearly", "Every year"),
                        ],
                        default="none",
                        help_text="Repeat cadence — the command exposes a subset, the column accepts all values.",
                        max_length=20,
                    ),
                ),
                (
                    "google_calendar_target",
                    models.CharField(
                        choices=[("member", "Member calendar"), ("public", "Public calendar")],
                        default="member",
                        help_text="Which Google calendar the published event posts to.",
                        max_length=10,
                    ),
                ),
                (
                    "email_choice",
                    models.CharField(
                        choices=[
                            ("none", "Don't email"),
                            ("guild_members", "This guild's members"),
                            ("all_active", "The whole membership"),
                        ],
                        default="none",
                        help_text="Whether publishing also emails an audience, and which one.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Drives the confirm-window expiry.")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The atomic claim stamp — set exactly once by the winning Confirm click.",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Whose preview this is — the claim filter and the create actor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_event_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The resolved target guild — NULL means a site-wide community event.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_event_drafts",
                        to="membership.guild",
                    ),
                ),
            ],
        ),
    ]
