# Generated by Django 6.0.7 on 2026-08-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0135_communityeventdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="discord_announce_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The channel the #public-calendar announcement message was posted to. Blank until announced (or for events announced before the RSVP embed shipped).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="discord_announce_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The announcement message id, so the hub can refresh its Attendees field and a cancel can strip its buttons. Blank until announced.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="EventRSVP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the RSVP was made (drives the display order)."
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The published event this RSVP is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="membership.communityevent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who is coming.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_rsvps",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [models.UniqueConstraint(fields=("event", "member"), name="uq_eventrsvp_event_member")],
            },
        ),
    ]
