# Generated by Django 6.0.7 on 2026-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0138_calendar_channel_rename_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="source",
            field=models.CharField(
                choices=[
                    ("button", "Discord RSVP button"),
                    ("hub", "Hub event page"),
                    ("interested", "Discord Interested sync"),
                ],
                default="button",
                help_text="Which door the RSVP came through; the Interested sync may only remove its own rows.",
                max_length=20,
            ),
        ),
    ]
