# Generated by Django 6.0.7 on 2026-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0139_eventrsvp_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admincapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("class_approver", "CMS Administrator"),
                    ("space_approver", "Space & Cubby Administrator"),
                    ("discount_approver", "Discount Code Administrator"),
                    ("events_approver", "Calendar Administrator"),
                    ("billing_approver", "Billing Administrator"),
                    ("refunds", "Refunds"),
                ],
                help_text="Which scoped admin authority this grant confers.",
                max_length=30,
            ),
        ),
    ]
