# Generated by Django 6.0.7 on 2026-08-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0141_member_guild_updates_prompt_answered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationavailability",
            name="orienter",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff member who personally gives orientations during this window. Empty means any orienter (legacy guild hours).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_availability_rules",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="orientationslot",
            name="orienter",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff member this slot is booked with. Empty means any orienter.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orientation_slots_offered",
                to="membership.member",
            ),
        ),
    ]
