# Generated by Django 6.0.7 on 2026-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0142_orienter_availability"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orientationbooking",
            name="uq_orientationbooking_active_per_guild",
        ),
        migrations.AddField(
            model_name="guildorientationsettings",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=0, help_text="Price to book an orientation, in cents. 0 = free (the default)."
            ),
        ),
        migrations.AddField(
            model_name="orientationbooking",
            name="amount_paid_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Amount paid to book, in cents. 0 for free bookings. Set provisionally at checkout start; the webhook's amount_total is canonical.",
            ),
        ),
        migrations.AddField(
            model_name="orientationbooking",
            name="stripe_payment_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe PaymentIntent ID, stamped by the webhook on payment.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="orientationbooking",
            name="stripe_session_id",
            field=models.CharField(blank=True, default="", help_text="Stripe Checkout Session ID.", max_length=255),
        ),
        migrations.AlterField(
            model_name="orientationbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("requested", "Requested"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                help_text="Request lifecycle state.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationbooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending_payment", "requested", "confirmed"])),
                fields=("guild", "member"),
                name="uq_orientationbooking_active_per_guild",
            ),
        ),
    ]
