# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0143_paid_orientations"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="allow_member_announcement_suggestions",
            field=models.BooleanField(
                default=True,
                help_text="Let members suggest announcements for this guild from its guild page.",
            ),
        ),
    ]
