# Generated by Django 6.0.7 on 2026-08-27
#
# Drops the four now-defunct welcome-email columns from GuildOrientationSettings.
# The welcome email fired from the "Join This Guild" trigger, which was removed last
# round, so no code path writes or reads these fields any longer. Django auto-generates
# the AddField reverse, so this migration runs backward cleanly, BUT the column drop is
# destructive: any welcome-email subject/body a guild had stored is lost and a reverse
# migration restores empty columns, not the old copy. This is acceptable — the feature
# is dead, and the fields are lead-authored config, not member records.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0144_guild_allow_member_announcement_suggestions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildorientationsettings",
            name="join_email_body",
        ),
        migrations.RemoveField(
            model_name="guildorientationsettings",
            name="join_email_enabled",
        ),
        migrations.RemoveField(
            model_name="guildorientationsettings",
            name="join_email_subject",
        ),
        migrations.RemoveField(
            model_name="guildorientationsettings",
            name="join_email_updated_at",
        ),
    ]
