# Generated by Django 6.0.7 on 2026-08-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0146_readd_guild_welcome_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votepreference",
            name="guild_2nd",
            field=models.ForeignKey(
                blank=True,
                help_text="Second-choice guild (3 points). Optional; must differ from the other choices.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_choice_votes",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="guild_3rd",
            field=models.ForeignKey(
                blank=True,
                help_text="Third-choice guild (2 points). Optional; must differ from the other choices.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_choice_votes",
                to="membership.guild",
            ),
        ),
    ]
