# Generated by Django 6.0.7 on 2026-09-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0149_alter_guild_discord_welcome_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="discord_welcome_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown to the member in Discord (their private confirmation) and posted in your guild's Discord channel when someone joins via /join-guild. This is separate from your guild Welcome Email. Write it in your voice (a lead's welcome). Blank uses a generic welcome.",
            ),
        ),
    ]
