# Generated by Django 6.0.7 on 2026-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0151_alter_guildstaffmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacerequest",
            name="kind",
            field=models.CharField(
                choices=[("lease", "Studio space"), ("cubby", "Cubby / shelf")],
                default="lease",
                help_text="Whether this is a studio space ask or a cubby/shelf ask. Sets who reviews it.",
                max_length=10,
            ),
        ),
    ]
