# Generated by Django 6.0.7 on 2026-09-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0152_alter_spacerequest_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free text pronouns shown in the member directory (e.g. she/her, they/them).",
                max_length=50,
            ),
        ),
    ]
