# Generated by Django 6.0.7 on 2026-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0154_blank_prefer_not_to_share_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="show_on_space_map",
            field=models.BooleanField(
                default=False,
                help_text="Member opted in to being named as an occupant on the public Spaces map. Off by default: an opted out member's space still shows as occupied, just with no name attached. Even when on, names and occupant cards appear only for logged in members, never guests.",
            ),
        ),
    ]
