# Generated by Django 6.0.7 on 2026-09-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0155_member_show_on_space_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrientationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Member-facing name, e.g. 'Shop Basics' or 'Lathe'.", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="What this orientation covers, shown to members (plain text)."
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Length of this orientation in minutes. Custom time requests use it."
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Price to book this orientation type, in cents. 0 = free (the default)."
                    ),
                ),
                (
                    "default_seats",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Default capacity for new slots of this type."
                    ),
                ),
                (
                    "default_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where this orientation usually happens, e.g. 'Woodshop'.",
                        max_length=200,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers sort first on the guild page and in pickers."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Offer this type to members. An inactive type keeps its history but takes no new bookings.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="The guild that offers this orientation type.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_types",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="orientationavailability",
            name="orientation_type",
            field=models.ForeignKey(
                help_text="The orientation type slots generated from this rule are for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="membership.orientationtype",
            ),
        ),
        migrations.AddField(
            model_name="orientationbooking",
            name="orientation_type",
            field=models.ForeignKey(
                help_text="Denormalized from the slot (like guild) for cheap filtering and the per-type duplicate guard.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="membership.orientationtype",
            ),
        ),
        migrations.AddField(
            model_name="orientationslot",
            name="orientation_type",
            field=models.ForeignKey(
                help_text="The orientation type this slot is for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="membership.orientationtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationtype",
            constraint=models.UniqueConstraint(fields=("guild", "name"), name="uq_orientationtype_guild_name"),
        ),
    ]
