# Generated by Django 6.0.7 on 2026-09-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0158_orientation_type_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientationslot",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Added manually"),
                    ("generated", "From a recurring rule"),
                    ("from_block", "Booked into an availability block"),
                ],
                default="manual",
                help_text="How this slot was created.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrientationAvailabilityBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starts_at", models.DateTimeField(help_text="When the availability window opens.")),
                ("ends_at", models.DateTimeField(help_text="When the availability window closes.")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where orientations booked into this block happen.",
                        max_length=200,
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        default=False, help_text="Set when the orienter calls the window off. Stops new bookings only."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="Parent guild.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_blocks",
                        to="membership.guild",
                    ),
                ),
                (
                    "orienter",
                    models.ForeignKey(
                        help_text="The staff member available during this window. Required — a block is one person's posted time.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_blocks_offered",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.AddField(
            model_name="orientationslot",
            name="block",
            field=models.ForeignKey(
                blank=True,
                help_text="The availability block this slot was carved out of, for FROM_BLOCK slots.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="membership.orientationavailabilityblock",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationavailabilityblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))), name="ck_orientationblock_end_after_start"
            ),
        ),
    ]
