# Generated by Django 6.0.7 on 2026-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0159_alter_orientationslot_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Verified address email notifications are sent to. Blank means the primary email. If this address is later removed or unverified, notifications fall back to the primary. Read via core.events.channels.notification_email_for; see the three-store note on Member.primary_email for how emails are stored (this field routes notifications only and never changes primary_email semantics).",
                max_length=254,
            ),
        ),
    ]
