# Generated by Django 6.0.7 on 2026-09-03 18:43

import core.validators
import django.db.models.deletion
from django.db import migrations, models


def _backfill_equipment_capability(apps, schema_editor):
    """Grant every current ``fog_role='admin'`` member the EQUIPMENT capability.

    The migration-0118 precedent: admins held blanket authority before capabilities
    existed, so nobody loses create/manage authority (or the PR 2 notifications) the
    day the Equipment directory rolls out. New admins added later are assigned the
    capability deliberately in the member edit UI.
    """
    Member = apps.get_model("membership", "Member")
    AdminCapability = apps.get_model("membership", "AdminCapability")
    rows = [
        AdminCapability(member=member, capability="equipment")
        for member in Member.objects.filter(fog_role="admin").iterator()
    ]
    AdminCapability.objects.bulk_create(rows, ignore_conflicts=True)


def _remove_equipment_capability(apps, schema_editor):
    """Reverse: delete exactly the EQUIPMENT capability rows this backfill seeds."""
    AdminCapability = apps.get_model("membership", "AdminCapability")
    AdminCapability.objects.filter(capability="equipment").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0160_member_notification_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admincapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("class_approver", "CMS Administrator"),
                    ("space_approver", "Space & Cubby Administrator"),
                    ("discount_approver", "Discount Code Administrator"),
                    ("events_approver", "Calendar Administrator"),
                    ("billing_approver", "Billing Administrator"),
                    ("refunds", "Refunds"),
                    ("equipment", "Equipment Administrator"),
                ],
                help_text="Which scoped admin authority this grant confers.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hero_crop_x",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box left edge in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_y",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box top edge in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_w",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box width in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                (
                    "hero_crop_h",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Crop box height in source-image pixels — set by the hero cropper.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name members see, e.g. CNC Router.", max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL slug for the equipment page, auto-generated from the name (stable across renames).",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("tool", "Tool"), ("room", "Room")],
                        default="tool",
                        help_text="Whether this is a tool or a room. Both live on the Equipment page.",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Hero photo shown on the card and detail page.",
                        upload_to="equipment/",
                        validators=[core.validators.validate_image_size],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The About body on the equipment page — what it is, how to use it well.",
                    ),
                ),
                (
                    "location_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wayfinding note, e.g. 'Back corner of the wood shop.'",
                        max_length=200,
                    ),
                ),
                (
                    "requires_guild_membership",
                    models.BooleanField(
                        default=False,
                        help_text="Only members of the owning guild may book. Only meaningful when a guild is set.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Offer this equipment to members. Inactive (retired) gear is hidden from the index.",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this equipment belongs to; its leadership manages it. Blank = standalone. PROTECT: deleting a guild with equipment must be a deliberate re-home, not a silent cascade.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="membership.guild",
                    ),
                ),
                (
                    "required_orientation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Members must complete this orientation before booking. PROTECT: deleting an orientation type that gates live equipment should fail loudly, not silently un-gate a dangerous tool.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gated_equipment",
                        to="membership.orientationtype",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional read-only link to the physical room on the space map. Django never writes through this relationship; the Airtable sync never sees Equipment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="membership.space",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentStaffMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Manager")],
                        default="manager",
                        help_text="The staff role on this equipment. Manager is the only role today.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this role was granted.")),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment this manager role applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_memberships",
                        to="membership.equipment",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member who granted this role (audit; nulled if they're deleted).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member holding the manager role.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_staff_memberships",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["member__full_legal_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("equipment", "member"), name="uq_equipmentstaffmembership_equipment_member"
                    )
                ],
            },
        ),
        migrations.RunPython(_backfill_equipment_capability, _remove_equipment_capability),
    ]
