# Generated by Django 6.0.7 on 2026-09-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0161_equipment_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="closed_message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown to members while closed, e.g. 'Down for maintenance.'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="Temporarily stop NEW reservations. Existing reservations stand until a manager cancels each.",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_active_reservations_per_member",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="How many upcoming reservations one member can hold on this equipment at once."
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_advance_days",
            field=models.PositiveSmallIntegerField(default=30, help_text="How far ahead members can book, in days."),
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=240, help_text="Longest reservation members can make, in minutes (half hour steps)."
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="min_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Shortest reservation members can make, in minutes (half hour steps)."
            ),
        ),
        migrations.CreateModel(
            name="EquipmentHours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week (Monday=0).",
                    ),
                ),
                ("start_time", models.TimeField(help_text="When the window opens (half hour grid, local time).")),
                ("end_time", models.TimeField(help_text="When the window closes (half hour grid, local time).")),
                ("is_active", models.BooleanField(default=True, help_text="Pause a window without deleting it.")),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment this window opens.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_rules",
                        to="membership.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipment hours",
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="ck_equiphours_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EquipmentReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starts_at", models.DateTimeField(help_text="When the reservation begins (aware UTC).")),
                ("ends_at", models.DateTimeField(help_text="When the reservation ends (aware UTC).")),
                (
                    "purpose",
                    models.CharField(
                        blank=True, default="", help_text="Optional one liner shown on the schedule.", max_length=140
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                        default="confirmed",
                        help_text="Confirmed or cancelled.",
                        max_length=20,
                    ),
                ),
                (
                    "cancelled_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required when a manager cancels; shown to the member.",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the reservation was made.")),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, help_text="When it was cancelled, if it was.", null=True),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who cancelled it — distinguishes self cancel from manager cancel.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The reserved equipment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="membership.equipment",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who reserved it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_reservations",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "confirmed")),
                        fields=["equipment", "starts_at"],
                        name="idx_equipres_confirmed",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))), name="ck_equipres_end_after_start"
                    )
                ],
            },
        ),
    ]
