# Generated by Django 6.0.7 on 2026-09-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0162_equipment_reservations"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationtype",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="The equipment that owns this orientation type. Empty for a guild-owned type. PROTECT: deleting equipment that owns orientation history must fail loudly.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_orientation_types",
                to="membership.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="orientationbooking",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from the slot for cheap filtering and scoping. Empty for an equipment-owned orientation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_bookings",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="orientationslot",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent guild. Empty for an equipment-owned orientation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_slots",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="orientationtype",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="The guild that offers this orientation type. Empty for an equipment-owned type.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_types",
                to="membership.guild",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("equipment__isnull", True), ("guild__isnull", False)),
                    models.Q(("equipment__isnull", False), ("guild__isnull", True)),
                    _connector="OR",
                ),
                name="ck_orienttype_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("equipment__isnull", False)),
                fields=("equipment", "name"),
                name="uq_orienttype_equip_name",
            ),
        ),
    ]
