# Generated by Django 6.0.7 on 2026-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0163_equipment_owned_orientations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityevent",
            name="google_calendar_target",
            field=models.CharField(
                choices=[("member", "Member calendar"), ("public", "Public calendar")],
                default="public",
                help_text="Which Google calendar this event syncs to when Google sync is on. Public is the norm; pick the members-only calendar for member-only events.",
                max_length=10,
                verbose_name="Which calendar",
            ),
        ),
        migrations.AlterField(
            model_name="communityeventdraft",
            name="google_calendar_target",
            field=models.CharField(
                choices=[("member", "Member calendar"), ("public", "Public calendar")],
                default="public",
                help_text="Which Google calendar the published event posts to. Public is the norm; members-only is the exception.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="guild",
            name="calendar_color",
            field=models.CharField(
                blank=True,
                default="#4B9FEE",
                help_text="Hex color code for this guild's events on the Calendar (e.g. #4B9FEE).",
                max_length=7,
            ),
        ),
    ]
