# Generated by Django 6.0.7 on 2026-09-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0164_alter_communityevent_google_calendar_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationavailability",
            name="buffer_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minutes left free between consecutive carved slots. Ignored when slot_minutes is empty.",
            ),
        ),
        migrations.AddField(
            model_name="orientationavailability",
            name="slot_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Carve each occurrence of this window into slots this long. Empty keeps one slot spanning the whole window.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orientationavailability",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent guild. Empty when an equipment owns the orientation type.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientation_rules",
                to="membership.guild",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_minutes__isnull", True), ("slot_minutes__gt", 0), _connector="OR"),
                name="ck_orientavail_slot_positive",
            ),
        ),
    ]
