# Generated by Django 6.0.7 on 2026-09-07 20:32

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0166_queued_results_send"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="What the page is called, e.g. 'SawStop Table Saw'.", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL name under /wiki/p/. Filled from the title once and never changed, so a deep link and a printed sticker never break.",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("machine", "Machine or tool"),
                            ("howto", "How to do something"),
                            ("material", "Material"),
                            ("project", "Project write-up"),
                            ("guild_info", "How this guild works"),
                            ("reference", "Reference table or chart"),
                        ],
                        help_text="What sort of page this is. Drives the starter template and how often it asks to be checked.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community"),
                            ("guild_verified", "Guild verified"),
                            ("official", "Official"),
                        ],
                        default="community",
                        help_text="Community (the normal state), Guild verified, or Official.",
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The page body. Rich text from the editor, or Markdown on older pages.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the page was created.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the page was last saved.")),
                (
                    "body_edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a person last edited the body. Blank means the body is still exactly what the seeder wrote, which is how the seeder knows it may refresh the page.",
                        null=True,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When someone last confirmed the page is still accurate. The freshness clock.",
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, help_text="When it was verified.", null=True)),
                (
                    "unverified_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why a green check was dropped, e.g. 'Edited since it was verified.' Shown beside the status pill, because a reason recorded and never shown is a lie told to the next reader.",
                        max_length=200,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Off means the page is held for a second read and only its author and the guild's leads can see it.",
                    ),
                ),
                (
                    "needs_review_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set while a member's report about this page is open. Denormalized so the amber chip can appear in search results without a join.",
                        null=True,
                    ),
                ),
                (
                    "needs_review_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A one-line summary of the open report, shown beside the status pill. Member-supplied, so it is escaped on render.",
                        max_length=300,
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the page was archived. The URL keeps working and explains itself; members cannot delete, and hard delete is not in the UI.",
                        null=True,
                    ),
                ),
                (
                    "archive_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why it was archived. Shown to the author by name on the archived page.",
                        max_length=300,
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Flattened plain text of the title, body, Quick Answers, and attachment labels. Rebuilt on save so search never matches HTML tag names.",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The short code behind the /m/ sticker link. Filled once and never changed.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who archived it. An archive that cannot say who cleared an item cannot be audited.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created the page. Blank for pages the equipment seeder wrote.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tool this page documents, when it documents one. Drives the locked Official block.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_pages",
                        to="membership.equipment",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this page belongs to. Leave blank for a page that belongs to the whole space.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_pages",
                        to="membership.guild",
                    ),
                ),
                (
                    "last_checked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who last confirmed it. Named in the byline.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who saved it last.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who stood behind this page with a green check.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="WikiAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        help_text="What to call this, e.g. 'Blade change steps'. Required, because the label is what makes the file worth opening.",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a document or a photo. Leave blank if you're adding a link instead.",
                        upload_to="wiki/attachments/",
                        validators=[core.validators.validate_wiki_upload],
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to something elsewhere. Leave blank if you uploaded a file instead.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When it was added.")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who added it. Shown on the attachment card.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page this attachment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="membership.wikipage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WikiPageFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        help_text="The question, in two or three words. 'Blade' or 'Max width'.", max_length=60
                    ),
                ),
                ("value", models.CharField(help_text="The answer. Short enough to read at a glance.", max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page this fact belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="membership.wikipage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WikiRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="The title as it was at this version.", max_length=200)),
                ("body", models.TextField(blank=True, default="", help_text="The body as it was at this version.")),
                (
                    "facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The Quick Answers rows as they were, so a revert restores the whole page and not just the prose.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community"),
                            ("guild_verified", "Guild verified"),
                            ("official", "Official"),
                        ],
                        help_text="The status at save time, so a revert restores it rather than guessing.",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("save", "Edit"), ("revert", "Reverted"), ("conflict_draft", "Unmerged draft")],
                        default="save",
                        help_text="What produced this version: a normal edit, a revert, or a draft that was never applied.",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A short line for the history list, e.g. 'Photo added'.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this version was saved.")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who saved it. Blank for versions the equipment seeder wrote.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_revisions",
                        to="membership.member",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="membership.wikipage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="WikiDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("machine", "Machine or tool"),
                            ("howto", "How to do something"),
                            ("material", "Material"),
                            ("project", "Project write-up"),
                            ("guild_info", "How this guild works"),
                            ("reference", "Reference table or chart"),
                        ],
                        help_text="The kind chosen for a new page; mirrors the page's kind otherwise.",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", help_text="The title as typed so far.", max_length=200),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The body as typed so far. Sanitized on every autosave, so a draft is never a hole in the sanitizer.",
                    ),
                ),
                (
                    "facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The Quick Answers rows as typed so far. Held as JSON because a draft is a scratch buffer, not a queryable store.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the draft was last autosaved.")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Whose draft this is.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_drafts",
                        to="membership.member",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scope chosen for a new page.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership.guild",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page being edited. Blank for a new page that does not exist yet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="membership.wikipage",
                    ),
                ),
                (
                    "base_revision",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page's newest version when this draft was started, so a conflict is measured against what the member actually typed over.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.wikirevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(fields=["guild", "kind"], name="idx_wikipage_guild_kind"),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(fields=["status", "kind"], name="idx_wikipage_status_kind"),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(fields=["-updated_at"], name="idx_wikipage_updated"),
        ),
        migrations.AddConstraint(
            model_name="wikipage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("equipment__isnull", False), ("kind", "machine")),
                fields=("equipment",),
                name="uq_wikipage_machine_equip",
            ),
        ),
        migrations.AddConstraint(
            model_name="wikiattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("file", ""), models.Q(("url", ""), _negated=True)),
                    models.Q(models.Q(("file", ""), _negated=True), ("url", "")),
                    _connector="OR",
                ),
                name="ck_wikiattach_file_xor_url",
            ),
        ),
        migrations.AddIndex(
            model_name="wikirevision",
            index=models.Index(fields=["page", "-created_at"], name="idx_wikirevision_page"),
        ),
        migrations.AddConstraint(
            model_name="wikidraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)), fields=("page", "author"), name="uq_wikidraft_page_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikidraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", True)),
                fields=("author", "kind"),
                name="uq_wikidraft_new_author_kind",
            ),
        ),
    ]
