# Generated by Django 6.0.7 on 2026-09-09 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0168_member_welcome_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="archive_redirect",
            field=models.ForeignKey(
                blank=True,
                help_text="The page readers should go to instead, if there is one. Set from the archived page itself, because you rarely know the replacement at the moment you archive.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="official_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A locked staff note pinned above member content. Members cannot edit or remove it.",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="official_note_at",
            field=models.DateTimeField(
                blank=True, help_text="When the official note was last written. Drives its byline date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="official_note_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who wrote the official note. Named in its byline.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.member",
            ),
        ),
        migrations.CreateModel(
            name="WikiEditLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this holder opened the editor. What the warning's '3 minutes ago' counts from.",
                    ),
                ),
                (
                    "refreshed_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Bumped by every autosave. Expiry is measured from here, not from the start.",
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        help_text="Who has the editor open.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_edit_locks",
                        to="membership.member",
                    ),
                ),
                (
                    "page",
                    models.OneToOneField(
                        help_text="The page being edited. One holder at a time; claiming overwrites a stale row.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_lock",
                        to="membership.wikipage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WikiReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.TextField(help_text="What the member says is wrong. Shown on the page, in their own words."),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="When it was reported."),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a lead or admin marked it reviewed, or the reporter withdrew it. Null means open.",
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note from the reviewer, for the audit trail. The reporter is not emailed it.",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page being reported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="membership.wikipage",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reported it. Nulled if the account is deleted; the banner then reads 'a member'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_reports",
                        to="membership.member",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who closed it out. The reporter themselves, for a withdrawal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_reports_resolved",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["resolved_at", "created_at"], name="idx_wikireport_open_age"),
                    models.Index(fields=["page", "resolved_at"], name="idx_wikireport_page_open"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("page", "reporter"),
                        name="uq_wikireport_open_reporter",
                    )
                ],
            },
        ),
    ]
