# Generated by Django 6.0.7 on 2026-09-09 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0169_wiki_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="verified_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="An optional line the verifier left for the next reader. Shown under the credit.",
                max_length=280,
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="verified_role_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The verifier's role at the moment they verified, e.g. 'Woodworking orienter'. Frozen on purpose: 'Verified by Kate (Woodworking orienter), 3 Mar' is a historical statement and must not silently rewrite itself when Kate leaves the guild.",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="WikiSearchMiss",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "query",
                    models.CharField(help_text="Exactly what the member typed, kept for display.", max_length=200),
                ),
                (
                    "query_normalized",
                    models.CharField(
                        help_text="Case-folded, whitespace-collapsed query. The grouping key.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="When they searched.")),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scope the search ran in. Blank means they searched everything.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_search_misses",
                        to="membership.guild",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who searched. Blank after a member is deleted; the miss still counts.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_search_misses",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["guild", "created_at"], name="idx_wikimiss_guild_created"),
                    models.Index(fields=["query_normalized"], name="idx_wikimiss_norm"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WikiWantedPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="What the page should be called, in the asker's own words.", max_length=200
                    ),
                ),
                (
                    "title_normalized",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Case-folded, whitespace-collapsed title. Filled on save; powers the duplicate bump.",
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Optional: what the page should cover, or who to ask."
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When it was claimed. Drives the 'claimed 5 weeks ago' staleness line.",
                        null=True,
                    ),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many PEOPLE asked for this. '4 people asked for this' is the most useful number on the panel; a lead filing a row does not increment it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the ask was first recorded.")),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who said they would write it. A claim is a signal, never a lock.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_pages_claimed",
                        to="membership.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who asked. Blank survives a member deletion; the row is still useful.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_pages_wanted",
                        to="membership.member",
                    ),
                ),
                (
                    "fulfilled_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page that answered the ask. Non-blank means this row is done.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_wants",
                        to="membership.wikipage",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild asking. Leave blank for a page the whole space wants.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_wiki_pages",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["guild", "fulfilled_page"], name="idx_wikiwanted_guild_open")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("fulfilled_page__isnull", True)),
                        fields=("guild", "title_normalized"),
                        name="uq_wikiwanted_guild_title",
                    )
                ],
            },
        ),
    ]
