# Generated by Django 6.0.7 on 2026-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0169_wiki_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="teaching_application_note",
            field=models.TextField(
                blank=True, default="", help_text="What the member said they want to teach, in their own words."
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_applied_at",
            field=models.DateTimeField(
                blank=True, help_text="When the member applied to teach. Null means they have never applied.", null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_decided_at",
            field=models.DateTimeField(
                blank=True, help_text="When an admin approved or declined the teaching application.", null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_decline_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why the application was declined. Shown to the member. Blank when approved.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="instructor_oriented_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an admin granted this member teaching access; null = teaching portal locked. Cleared when an admin revokes access.",
                null=True,
            ),
        ),
    ]
