# Generated by Django 6.0.7 on 2026-09-13 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0171_member_teaching_application_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildorientationsettings",
            name="external_signup_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Send orientation signups to an outside form, e.g. a Google Form, instead of the built-in booking flow. Members see this link where the booking times used to be. Leave blank to keep booking here. An orientation type can set its own link to override this one.",
                max_length=500,
                validators=[
                    django.core.validators.URLValidator(
                        message="Enter a link that starts with http:// or https://.", schemes=["http", "https"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="orientationtype",
            name="external_signup_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Send signups for this orientation to an outside form instead of the built-in booking flow. Overrides the guild's link when both are set, and is the only way to point an equipment-owned orientation outside. Leave blank to follow the guild.",
                max_length=500,
                validators=[
                    django.core.validators.URLValidator(
                        message="Enter a link that starts with http:// or https://.", schemes=["http", "https"]
                    )
                ],
            ),
        ),
    ]
