# Generated by Django 6.0.7 on 2026-09-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0173_video_provider_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationavailability",
            name="anchor_date",
            field=models.DateField(
                blank=True,
                help_text="Any day in the first week an every other week rule runs. Ignored by a weekly rule.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orientationavailability",
            name="interval_weeks",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Every week"), (2, "Every other week")],
                default=1,
                help_text="How often this window recurs: every week, or every other week from the week of anchor_date.",
            ),
        ),
    ]
