# Generated by Django 6.0.7 on 2026-09-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0173_video_provider_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationavailability",
            name="anchor_date",
            field=models.DateField(
                blank=True,
                help_text="The first day this rule runs. Required for every cadence but weekly, which ignores it.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orientationavailability",
            name="cadence",
            field=models.CharField(
                choices=[
                    ("weekly", "Every week"),
                    ("fortnightly", "Every other week"),
                    ("monthly", "Every month"),
                    ("every_2_months", "Every 2 months"),
                    ("every_3_months", "Every 3 months"),
                    ("every_6_months", "Every 6 months"),
                    ("yearly", "Every year"),
                ],
                default="weekly",
                help_text="How often this window recurs. Every cadence but weekly counts from anchor_date.",
                max_length=16,
            ),
        ),
    ]
