# Generated by Django 6.0.7 on 2026-09-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0174_orientation_availability_cadence"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hero_title",
                    models.CharField(default="Leadership Directory", help_text="The page heading.", max_length=120),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        blank=True,
                        default="Who runs Past Lives, who leads each guild, and how to reach them.",
                        help_text="A sentence or two under the heading. Blank hides the line.",
                    ),
                ),
                (
                    "team_heading",
                    models.CharField(
                        default="Leadership & Admin Team",
                        help_text="Heading of the curated section, ordered by admins.",
                        max_length=120,
                    ),
                ),
                (
                    "team_intro",
                    models.TextField(
                        blank=True,
                        default="The people who keep the makerspace running, and how to reach each of them.",
                        help_text="Intro line under the team heading. Blank hides the line.",
                    ),
                ),
                (
                    "guilds_heading",
                    models.CharField(
                        default="Guild Leaders",
                        help_text="Heading of the section built from each guild's lead and co-leads.",
                        max_length=120,
                    ),
                ),
                (
                    "guilds_intro",
                    models.TextField(
                        blank=True,
                        default="Every active guild and who leads it, straight from the guild's own settings.",
                        help_text="Intro line under the guilds heading. Blank hides the line.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Directory page",
                "verbose_name_plural": "Leadership Directory page",
            },
        ),
        migrations.CreateModel(
            name="LeadershipListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_listed",
                    models.BooleanField(
                        default=False,
                        help_text="Show this member on the Leadership Directory. Off hides the card and keeps the role lines.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this listing last changed. The page's Updated line reads the newest.",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        help_text="The member this card shows. Photo, name and pronouns come from their profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_listing",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="The role as shown on the card, e.g. 'Member Liaison'.", max_length=120),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Contact address for this role. Blank shows no email line.",
                        max_length=254,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this role line last changed. The page's Updated line reads the newest.",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The listing this role line belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="membership.leadershiplisting",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
