# Generated by Django 6.0.6 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0175_leadership_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="show_in_directory",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether this member appears in the member directory. New members are hidden by "
                    "default; they can opt in any time in profile settings."
                ),
            ),
        ),
    ]
