# Generated by Django 6.0.8 on 2026-09-20 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0176_member_directory_hidden_by_default"),
        ("membership", "0176_memberagreementacceptance"),
    ]

    operations = []
