# Generated by Django 6.0.8 on 2026-09-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0176_member_directory_hidden_by_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAgreementAcceptance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the member accepted the agreement."),
                ),
                (
                    "agreement_url",
                    models.URLField(
                        blank=True, help_text="The URL of the agreement the member read, as configured at the time."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="The IP they accepted from.", null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who accepted the agreement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_agreement_acceptances",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("member",), name="unique_member_agreement_acceptance")],
            },
        ),
    ]
