# Generated by Django 6.0.7 on 2026-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0177_memberagreementacceptance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientationavailability",
            name="anchor_date",
            field=models.DateField(
                blank=True,
                help_text="The first day this rule runs, and the floor on every cadence. Required for every cadence but weekly, which may leave it blank and then runs from now.",
                null=True,
            ),
        ),
    ]
