# Generated by Django 6.0.8 on 2026-09-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0177_memberagreementacceptance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='memberagreementacceptance',
            name='unique_member_agreement_acceptance',
        ),
        migrations.AddField(
            model_name='memberagreementacceptance',
            name='content_length',
            field=models.PositiveIntegerField(blank=True, help_text='Size in bytes of the document that was hashed. A cheap second check on the hash.', null=True),
        ),
        migrations.AddField(
            model_name='memberagreementacceptance',
            name='content_sha256',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the document fetched from agreement_url as they accepted. Proves the text has not changed since. Blank if the fetch failed — accepting is never blocked on it.', max_length=64),
        ),
        migrations.AddField(
            model_name='memberagreementacceptance',
            name='document_version',
            field=models.CharField(blank=True, default='', help_text="The released version accepted, from Site Settings at the time. Blank on rows written before versions were recorded — blank means unknown, never 'the current one'.", max_length=40),
        ),
        migrations.AddField(
            model_name='memberagreementacceptance',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='The browser and device they accepted from, as reported. Corroborates the IP.'),
        ),
        migrations.AddIndex(
            model_name='memberagreementacceptance',
            index=models.Index(fields=['member', '-accepted_at'], name='member_agr_accept_idx'),
        ),
    ]
