# Generated by Django 6.0.7 on 2026-09-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0178_orientation_anchor_date_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrientationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_on", models.DateField(help_text="The day the orientation happened.")),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note from the admin, e.g. where or how the orientation happened.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the record was entered.")),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who was oriented.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_records",
                        to="membership.member",
                    ),
                ),
                (
                    "orientation_type",
                    models.ForeignKey(
                        help_text="The orientation they completed. PROTECT: a type with recorded history cannot be deleted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="membership.orientationtype",
                    ),
                ),
                (
                    "oriented_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who ran the orientation, when known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orientation_records_given",
                        to="membership.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who entered this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_on", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "orientation_type"), name="uq_orientationrecord_member_type"
                    )
                ],
            },
        ),
    ]
