# Generated by Django 6.0.7 on 2026-09-25 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0179_orientationrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="communityevent",
            name="ck_communityevent_guild_matches_type",
        ),
        migrations.AlterField(
            model_name="communityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guild_meeting", "Guild meeting / event"),
                    ("lead_meeting", "Guild Lead Meeting"),
                    ("community", "Event"),
                    ("studio_hours", "Studio hours"),
                ],
                default="guild_meeting",
                help_text="What kind of event this is.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="communityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type__in", ["guild_meeting", "studio_hours"]), ("guild__isnull", False)),
                    models.Q(("event_type", "lead_meeting"), ("guild__isnull", True)),
                    ("event_type", "community"),
                    _connector="OR",
                ),
                name="ck_communityevent_guild_matches_type",
            ),
        ),
    ]
