# Generated by Django 6.0.7 on 2026-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0179_orientationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="late_cancel_fee_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Fee for cancelling a reservation or an owned orientation inside the site's cancellation notice window, in cents. 0 = no fee (the default). Applies only while Site Settings charges late fees.",
            ),
        ),
        migrations.AddField(
            model_name="guildorientationsettings",
            name="late_cancel_fee_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Fee for cancelling a confirmed orientation inside the site's cancellation notice window, in cents. 0 = no fee (the default). Applies only while Site Settings charges late fees.",
            ),
        ),
    ]
