# Generated by Django 6.0.7 on 2026-09-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0180_event_audience_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityevent",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="The guild this belongs to. Leave blank for a makerspace wide or leadership event.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="communityeventdraft",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="The resolved target guild — NULL means a makerspace wide event.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_event_drafts",
                to="membership.guild",
            ),
        ),
    ]
