# Generated by Django 6.0.7 on 2026-09-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0182_retire_community_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityeventdraft",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guild_meeting", "Guild meeting / event"),
                    ("lead_meeting", "Guild Lead Meeting"),
                    ("community", "Event"),
                    ("studio_hours", "Studio hours"),
                ],
                default="community",
                help_text="The kind the preview card's What-it-is select settled on. A guild-less draft has only one available, so the select asks the audience alone and this stays a plain event.",
                max_length=20,
            ),
        ),
    ]
