# Generated by Django 6.0.7 on 2026-09-27 00:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0183_draft_event_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo. It fronts the event page, rides along on the Discord announcement, and becomes the cover image in Discord's own Events tab.",
                upload_to="events/photos/",
                validators=[core.validators.validate_image_size],
            ),
        ),
    ]
