# Generated by Django 6.0.2 on 2026-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0184_event_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildorientationsettings",
            name="thankyou_email_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Body of the thank-you email. Leave it blank to send the standard message.",
            ),
        ),
        migrations.AlterField(
            model_name="guildorientationsettings",
            name="welcome_email_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Body of the welcome email, your personal note. Leave it blank to send the standard message.",
            ),
        ),
    ]
