# Generated by Django 6.0.7 on 2026-09-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0186_remove_memberagreementacceptance_unique_member_agreement_acceptance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationavailability",
            name="booking_style",
            field=models.CharField(
                choices=[("fixed", "Fixed start times"), ("open", "Any time in the window")],
                default="fixed",
                help_text="How members book this row's times. Fixed start times materialize slots with seats; any time in the window materializes open windows members pick a start inside, one member at a time.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="orientationavailabilityblock",
            name="availability",
            field=models.ForeignKey(
                blank=True,
                help_text="The recurring hours row that generated this window, if any. Empty for a one off.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="windows",
                to="membership.orientationavailability",
            ),
        ),
        migrations.AddField(
            model_name="orientationavailabilityblock",
            name="orientation_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Only this orientation may book into the window. Empty means any of the guild's active orientations.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="windows",
                to="membership.orientationtype",
            ),
        ),
        migrations.AlterField(
            model_name="orientationavailability",
            name="orientation_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The orientation type this row's times are for. Empty means any of the guild's active orientations, which only an open personal row may say.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="membership.orientationtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("orientation_type__isnull", False),
                    models.Q(("booking_style", "open"), ("guild__isnull", False), ("orienter__isnull", False)),
                    _connector="OR",
                ),
                name="ck_orientavail_any_type_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationavailabilityblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("availability__isnull", False)),
                fields=("availability", "starts_at"),
                name="uq_orientblock_rule_start",
            ),
        ),
    ]
