# Generated by Django 6.0.7 on 2026-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0187_orientation_open_windows"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="teaching_contact_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The email address or phone number the member gave for that method, exactly as they typed it.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_contact_method",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("text", "Text message"), ("phone", "Phone call")],
                default="",
                help_text="How the member asked to be reached about their teaching application: email, text message or phone call. Blank for an application filed before the question was asked.",
                max_length=10,
            ),
        ),
    ]
