# Generated by Django 6.0.8 on 2026-10-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0188_member_teaching_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadershiplisting",
            name="is_listed",
            field=models.BooleanField(
                default=False, help_text="Show this card on its tab. Off hides the card and keeps the role lines."
            ),
        ),
        migrations.AlterField(
            model_name="leadershiplisting",
            name="member",
            field=models.ForeignKey(
                help_text="The member this card shows. Photo, name and pronouns come from their profile.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leadership_listings",
                to="membership.member",
            ),
        ),
        migrations.CreateModel(
            name="LeadershipTab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="The tab's label in the strip, e.g. 'Council'.", max_length=120)),
                (
                    "intro",
                    models.TextField(
                        blank=True, default="", help_text="A line above the tab's cards. Blank hides the line."
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("people", "People"), ("guild_leads", "Guild Leads")],
                        default="people",
                        help_text="People holds the cards admins add; Guild Leads shows each visible guild's card.",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Ascending; lower shows first.")),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "guild_leads")),
                        fields=("kind",),
                        name="leadershiptab_one_guild_leads",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="leadershiplisting",
            name="tab",
            field=models.ForeignKey(
                help_text="The tab this card sits on. Always set; blank only on a row the release before tabs wrote mid deploy.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="membership.leadershiptab",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershiplisting",
            constraint=models.UniqueConstraint(fields=("tab", "member"), name="leadershiplisting_tab_member"),
        ),
    ]
