# Generated by Django 6.0.8 on 2026-10-01 17:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0190_leadership_tabs_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(help_text="The words on the badge, e.g. 'Elevator Certified'.", max_length=40),
                ),
                (
                    "color",
                    models.CharField(
                        default="#EEB44B",
                        help_text="The badge's background as a six digit hex code, e.g. #092E4C. The text picks black or white.",
                        max_length=7,
                        validators=[core.validators.validate_hex_color],
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The members who hold this badge; it shows on each of their Leadership Directory cards.",
                        related_name="leadership_badges",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
