# Generated by Django 6.0.8 on 2026-10-03 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0192_announcement_draft_queue_and_results_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="delivery_period",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The delivery ledger period this announcement's send used, stamped when it is sent, so its reach can be read back from EventDelivery. Blank for announcements sent before it was recorded.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="fundingsnapshot",
            name="results_draft_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this snapshot's results draft was first made or opened, by the snapshot job or an admin's Draft announcement. Set once, so a draft an admin deletes is never made again on its own.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcementdraft",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last saved this announcement, and the sender once it is sent (the send actor and the email's From line). Blank on a results draft the system made, until someone saves or sends it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcement_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
