# Generated by Django 6.0.8 on 2026-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0193_announcements_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="include_never_logged_in",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Site announcements only: also reach active members who have never logged in, by email and in their notification bell once they do. Off, a site announcement reaches only members who have logged in at least once.",
            ),
        ),
    ]
