# Generated by Django 6.0.8 on 2026-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0194_announcementdraft_include_never_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="added_recipients",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text='Site announcements only: people added on top of everyone, by the sender. Same shape as recipient_selection, {"users": [pk, ...], "custom": ["addr", ...]}: users are member accounts everyone does not reach (a former member), custom are typed addresses with no account, which get the email only.',
            ),
        ),
    ]
