# Generated by Django 6.0.8 on 2026-10-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0195_announcementdraft_added_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementdraft",
            name="audience",
            field=models.CharField(
                choices=[
                    ("site", "Everyone (site-wide)"),
                    ("guild", "A specific guild"),
                    ("class", "A class you teach"),
                    ("leads", "Guild leads"),
                ],
                default="site",
                help_text="Who hears it: everyone site-wide, one guild's joined members, a class's registrants, or every guild lead, officer and staffer.",
                max_length=10,
            ),
        ),
    ]
