# Generated by Django 6.0.8 on 2026-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0197_orientation_info_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admincapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("class_approver", "CMS Administrator"),
                    ("space_approver", "Space & Cubby Administrator"),
                    ("discount_approver", "Discount Code Administrator"),
                    ("events_approver", "Calendar Administrator"),
                    ("billing_approver", "Billing Administrator"),
                    ("refunds", "Refunds"),
                    ("equipment", "Equipment Administrator"),
                    ("space_manager", "Space Manager"),
                ],
                help_text="Which scoped admin authority this grant confers.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="kind",
            field=models.CharField(
                choices=[("tool", "Tool"), ("room", "Room"), ("space", "Space")],
                default="tool",
                help_text="Whether this is a tool, a room, or a space. All of them live on the Reservations page.",
                max_length=10,
            ),
        ),
    ]
