# Generated by Django 6.0.8 on 2026-10-03 23:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0200_drop_orientation_external_signup_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationtype",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo shown on this orientation's card. Leave empty to use the guild banner, or the equipment photo for an equipment orientation.",
                upload_to="orientations/photos/",
                validators=[core.validators.validate_image_size],
            ),
        ),
    ]
