# Generated by Django 6.0.8 on 2026-10-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0200_drop_orientation_external_signup_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admincapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("class_approver", "CMS Administrator"),
                    ("space_approver", "Space & Cubby Administrator"),
                    ("discount_approver", "Discount Code Administrator"),
                    ("events_approver", "Calendar Administrator"),
                    ("billing_approver", "Billing Administrator"),
                    ("refunds", "Refunds"),
                    ("equipment", "Equipment Administrator"),
                    ("space_manager", "Space Manager"),
                    ("webmaster", "Webmaster"),
                ],
                help_text="Which scoped admin authority this grant confers.",
                max_length=30,
            ),
        ),
    ]
