# Generated by Django 6.0.8 on 2026-10-04 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0201_admincapability_webmaster"),
        ("membership", "0201_orientationtype_photo"),
    ]

    operations = []
