# Generated by Django 6.0.8 on 2026-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0202_merge_webmaster_orientation_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="show_reservations_tab",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Show a Reservations tab on the guild page listing this guild's reservable rooms, spaces and tools.",
            ),
        ),
    ]
