# Generated by Django 6.0.8 on 2026-10-04 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0204_hide_app_review_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Name members see, e.g. 'Hot Glass Room'.", max_length=100, unique=True),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional short note, e.g. 'Upstairs next to the Kitchen'.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Offer this location on forms. A deactivated location keeps what it is already set on.",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild whose area this is. Its guild page shows whether the area is in use. Optional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="membership.guild",
                    ),
                ),
                (
                    "shares_space_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Locations on the same floor space. Activity in a linked location makes this one in use too.",
                        to="membership.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="communityevent",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The area of the building it uses. Its guild page shows the area in use while it runs. Optional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="membership.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The area of the building it sits in. A reservation shows the area in use on its guild page. Optional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="membership.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="orientationtype",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The area of the building its slots use. A slot with a booking shows the area in use on its guild page. Optional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orientation_types",
                to="membership.location",
                verbose_name="Location",
            ),
        ),
    ]
