# Generated by Django 6.0.8 on 2026-10-05 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0205_location_and_areas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="requires_guild_membership",
        ),
    ]
