# Generated by Django 6.0.8 on 2026-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0206_remove_equipment_requires_guild_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentreservation",
            name="cancelled_as_manager",
            field=models.BooleanField(
                default=False,
                help_text="Cancelled through the manager route, including a manager cancelling their own row (#633).",
            ),
        ),
        migrations.AddField(
            model_name="equipmentreservation",
            name="late_fee_waived",
            field=models.BooleanField(
                default=False,
                help_text="A manager cancel inside the late notice window: the fee a self cancel would owe was not charged.",
            ),
        ),
    ]
