# Generated by Django 6.0.8 on 2026-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0206_remove_equipment_requires_guild_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationtype",
            name="donation_minimum_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The least a member may pay on a donation based type, in cents. 0 (the default) or at least 100.",
            ),
        ),
        migrations.AddField(
            model_name="orientationtype",
            name="donation_suggested_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The donation the booking form starts with, in cents. Empty for none; when set, at least the minimum and at least 100.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orientationtype",
            name="is_donation",
            field=models.BooleanField(
                default=False,
                help_text="Members choose what they pay when they book, instead of the fixed price. $0 books as a free request; any other amount goes through checkout.",
                verbose_name="Donation based",
            ),
        ),
    ]
