# Generated by Django 6.0.8 on 2026-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0208_orientationtype_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadershipbadge",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="The members who hold this badge; it shows on their Leadership Directory and Member Directory cards.",
                related_name="leadership_badges",
                to="membership.member",
            ),
        ),
    ]
