# Generated by Django 6.0.8 on 2026-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0209_leadershipbadge_members_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("former", "Former"),
                    ("suspended", "Suspended"),
                    ("guest", "Guest"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
