# Generated by Django 6.0.8 on 2026-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0210_alter_member_status_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentreservation",
            name="kind",
            field=models.CharField(
                choices=[("reservation", "Reservation"), ("block", "Block")],
                default="reservation",
                help_text="A member's reservation, or a manager's block holding the time (#657): no cap, no fee, no emails.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentreservation",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional one liner shown on the schedule; on a block, its reason (up to 80 characters).",
                max_length=140,
            ),
        ),
    ]
