# Generated by Django 6.0.8 on 2026-10-07 13:23

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def copy_required_orientation_into_list(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Each item gated by ``required_orientation`` keeps its gate: that type becomes its one unlocking orientation."""
    Equipment = apps.get_model("membership", "Equipment")
    EquipmentUnlockingOrientation = apps.get_model("membership", "EquipmentUnlockingOrientation")
    EquipmentUnlockingOrientation.objects.bulk_create(
        [
            EquipmentUnlockingOrientation(equipment_id=equipment_id, orientation_type_id=type_id)
            for equipment_id, type_id in Equipment.objects.filter(required_orientation__isnull=False).values_list(
                "pk", "required_orientation_id"
            )
        ]
    )


def copy_first_unlocking_orientation_back(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Reverse: the single FK takes each item's first listed type, the closest one orientation gate can hold."""
    Equipment = apps.get_model("membership", "Equipment")
    EquipmentUnlockingOrientation = apps.get_model("membership", "EquipmentUnlockingOrientation")
    first_by_equipment: dict[int, int] = {}
    for equipment_id, type_id in EquipmentUnlockingOrientation.objects.order_by("pk").values_list(
        "equipment_id", "orientation_type_id"
    ):
        first_by_equipment.setdefault(equipment_id, type_id)
    for equipment_id, type_id in first_by_equipment.items():
        Equipment.objects.filter(pk=equipment_id).update(required_orientation_id=type_id)


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0210_alter_member_status_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="required_orientation",
            field=models.ForeignKey(
                blank=True,
                help_text="Retired by #656 and read by nothing: the gate is unlocking_orientations. Kept one release so the release still serving while migrations run keeps working; a follow up drops the column.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="membership.orientationtype",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentUnlockingOrientation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment this orientation unlocks.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocking_orientation_rows",
                        to="membership.equipment",
                    ),
                ),
                (
                    "orientation_type",
                    models.ForeignKey(
                        help_text="Completing this orientation unlocks the equipment. PROTECT: deleting a type that unlocks live equipment fails loudly rather than silently changing who can book it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocking_equipment_rows",
                        to="membership.orientationtype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="unlocking_orientations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Completing any one of these orientations lets a member reserve this equipment. Empty means any active member can book it.",
                related_name="gated_equipment",
                through="membership.EquipmentUnlockingOrientation",
                to="membership.orientationtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentunlockingorientation",
            constraint=models.UniqueConstraint(fields=("equipment", "orientation_type"), name="uq_equip_unlock_orient"),
        ),
        migrations.RunPython(copy_required_orientation_into_list, copy_first_unlocking_orientation_back),
    ]
