# Generated by Django 6.0.8 on 2026-10-07 13:19

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def list_owner_equipment(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Add every equipment owned type's own equipment to its "Equipment it uses" list (#658).

    Blocking now reads the list, so without this row an equipment orientation would stop
    holding its own machine. In production that is types 17 (CNC Machine) and 18 (Laser
    Engraver Mira 9).
    """
    OrientationType = apps.get_model("membership", "OrientationType")
    Through = OrientationType.uses_equipment.through
    Through.objects.bulk_create(
        [
            Through(orientationtype_id=type_id, equipment_id=equipment_id)
            for type_id, equipment_id in OrientationType.objects.filter(equipment__isnull=False).values_list(
                "pk", "equipment_id"
            )
        ],
        ignore_conflicts=True,
    )


def unlist_owner_equipment(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Remove the owner rows the forward step added, leaving any other listed equipment."""
    OrientationType = apps.get_model("membership", "OrientationType")
    Through = OrientationType.uses_equipment.through
    Through.objects.filter(
        orientationtype__equipment__isnull=False, equipment_id=models.F("orientationtype__equipment_id")
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0210_alter_member_status_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationtype",
            name="uses_equipment",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "The equipment a booked slot of this orientation holds, like a reservation (#658). "
                    "An equipment orientation always lists its own equipment. Who runs it stays with the owner."
                ),
                related_name="orientation_types_using",
                to="membership.equipment",
                verbose_name="Equipment it uses",
            ),
        ),
        migrations.RunPython(list_owner_equipment, unlist_owner_equipment),
    ]
