# Generated by Django 6.0.8 on 2026-10-07 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0211_equipment_unlocking_orientations"),
        ("membership", "0211_equipmentreservation_kind"),
        ("membership", "0211_orientationtype_uses_equipment"),
    ]

    operations = []
