# Generated by Django 6.0.8 on 2026-10-07 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0212_merge_0211"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="required_orientation",
        ),
    ]
