# Generated by Django 6.0.8 on 2026-10-07 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0213_remove_equipment_required_orientation"),
        ("membership", "0213_show_skills_on_directory_cards"),
    ]

    operations = []
