# Generated by Django 6.0.8 on 2026-10-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0214_merge_0213"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="teaching_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_time", "First time teaching"),
                    ("informal", "Taught informally"),
                    ("a_few", "Taught a few classes"),
                    ("experienced", "Experienced instructor"),
                ],
                default="",
                help_text="How much teaching the member says they have done. Blank for an application filed before the question was asked.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_socials",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Social handles or links the member gave on their teaching application, as typed. Optional.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="teaching_website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The website the member gave on their teaching application. Optional.",
            ),
        ),
    ]
