# Generated by Django 6.0.8 on 2026-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0215_member_teaching_inquiry_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("guild_lead", "Guild Lead"),
                    ("work_trade", "Work-Trade"),
                    ("employee", "Staff"),
                    ("contractor", "Contractor"),
                    ("volunteer", "Volunteer"),
                ],
                default="standard",
                help_text="What kind of member (standard, guild lead, work-trade, etc.).",
                max_length=20,
            ),
        ),
    ]
