# Generated by Django 6.0.8 on 2026-10-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0216_member_type_staff_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guildmailinglistemail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The member this row is, when a lead saved a member from an announcement (#729). Blank for a plain address. A member is reached in the app as well as by email.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_mailing_list_rows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="guildmailinglistemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("guild", "user"),
                name="uq_guildmaillist_guild_user",
            ),
        ),
    ]
