# Generated by Django 6.0.8 on 2026-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0217_guild_mailing_list_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementdraft",
            name="discord_post_as_me",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Post the Discord message under the sender's own Discord name and picture instead of the webhook's. Offered only to a sender who linked Discord; read from Discord when it sends.",
            ),
        ),
    ]
