# Generated by Django 6.0.8 on 2026-10-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0218_announcement_draft_discord_post_as_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="allow_custom_requests",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Let members propose their own orientation time when none of this equipment's orientations has an open time, the guilds' switch of the same name (#733).",
            ),
        ),
    ]
