# Generated by Django 6.0.8 on 2026-10-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0219_equipment_allow_custom_requests"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="equipmentreservation",
            name="idx_equipres_confirmed",
        ),
        migrations.AddField(
            model_name="equipment",
            name="requires_approval",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Every reservation waits for a manager to approve it before it is booked (#748). Turning it off leaves requests already waiting still waiting.",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("pending_approval", "Awaiting approval"),
                    ("declined", "Declined"),
                ],
                default="confirmed",
                help_text="Confirmed, cancelled, awaiting a manager's approval, or declined by one (#748).",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentreservation",
            index=models.Index(
                condition=models.Q(("status__in", ["confirmed", "pending_approval"])),
                fields=["equipment", "starts_at"],
                name="idx_equipres_holding",
            ),
        ),
    ]
