# Generated by Django 6.0.8 on 2026-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0219_equipment_allow_custom_requests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmentunlockingorientation",
            options={
                "ordering": [
                    models.OrderBy(models.F("way"), nulls_last=True),
                    "orientation_type__sort_order",
                    "orientation_type__name",
                    "pk",
                ]
            },
        ),
        migrations.AddField(
            model_name="equipmentunlockingorientation",
            name="way",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The way to qualify this row belongs to (#747): a member who completes every orientation in one way can reserve the equipment. Blank = a way of its own, as every row saved before ways existed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="unlocking_orientations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The orientations that let a member reserve this equipment, grouped into ways by each row's way number: completing every orientation in any one way is enough. Empty means any active member can book it.",
                related_name="gated_equipment",
                through="membership.EquipmentUnlockingOrientation",
                to="membership.orientationtype",
            ),
        ),
    ]
