# Generated by Django 6.0.8 on 2026-10-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0221_equipment_requires_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="usage_agreement_text",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="The usage agreement's text, shown to members before reserving. Optional.",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="usage_agreement_url",
            field=models.URLField(
                blank=True,
                db_default="",
                default="",
                help_text="Link to the usage agreement document members read before reserving. Optional.",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentAgreementAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 of the agreement's link and text as they read it: the version agreed to.",
                        max_length=64,
                    ),
                ),
                (
                    "agreement_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The agreement link as it stood when they agreed.",
                    ),
                ),
                (
                    "agreement_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The agreement text as it stood when they agreed.",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, help_text="When they agreed."),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="The IP they agreed from.", null=True),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The browser and device they agreed from, as reported.",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment whose usage agreement they agreed to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_acceptances",
                        to="membership.equipment",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who agreed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_agreement_acceptances",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "equipment", "fingerprint"),
                        name="uniq_equip_agreement_accept",
                    )
                ],
            },
        ),
    ]
