# Generated by Django 6.0.8 on 2026-10-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0221_equipment_requires_approval"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="equipmentreservation",
            name="idx_equipres_holding",
        ),
        migrations.AddField(
            model_name="equipment",
            name="donation_minimum_cents",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="The least a member may pay on donation based pricing, in cents. 0 (the default) or at least 100.",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="donation_suggested_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The donation the reserve form starts with, in cents. Empty for none; when set, at least the minimum and at least 100.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="hourly_rate_cents",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="The rate per hour, in cents, while pricing is hourly. Kept when pricing changes.",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="pricing",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("donation", "Donation based"),
                    ("hourly", "Hourly"),
                ],
                db_default="free",
                default="free",
                help_text="Free, donation based (members choose what they pay) or hourly (a rate times the time booked).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="equipmentreservation",
            name="amount_paid_cents",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="What the member paid to reserve, in cents. 0 when free or not paid yet; Stripe's amount_total is canonical.",
            ),
        ),
        migrations.AddField(
            model_name="equipmentreservation",
            name="stripe_payment_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Stripe PaymentIntent ID, stamped when the payment lands.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="equipmentreservation",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Stripe Checkout Session ID.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("pending_approval", "Awaiting approval"),
                    ("declined", "Declined"),
                    ("pending_payment", "Awaiting payment"),
                ],
                default="confirmed",
                help_text="Confirmed, cancelled, awaiting a manager's approval, or declined by one (#748).",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentreservation",
            index=models.Index(
                condition=models.Q(("status__in", ["confirmed", "pending_approval", "pending_payment"])),
                fields=["equipment", "starts_at"],
                name="idx_equipres_holding",
            ),
        ),
    ]
