# Generated by Django 6.0.8 on 2026-10-10 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0222_equipment_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                help_text="Who gets paid (#749): the manager whose share of each paid reservation is paid out. Empty means the whole payment stays with Past Lives. Only one of this item's managers; removing them as a manager clears it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_equipment",
                to="membership.member",
            ),
        ),
    ]
