# Generated by Django 6.0.8 on 2026-10-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0224_equipment_payee"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="discord_pushed_start",
            field=models.DateTimeField(
                blank=True,
                help_text="The scheduled_start_time last sent to Discord: a series' next occurrence at the time of the push, or a single event's start. The retry cron compares a series' next occurrence against it and re-anchors the Discord series when the clocks have changed.",
                null=True,
            ),
        ),
    ]
