"""App version and changelog."""

from __future__ import annotations

VERSION = "2.5.0"

CHANGELOG: list[dict[str, str | list[str]]] = [
    {
        "version": "2.5.0",
        "date": "2026-06-08",
        "title": "Booking-site fixes, a clearer teaching area, and email auditing",
        "changes": [
            "On the public booking site (book.pastlives.space), the 'Manage Classes & Workshops' and 'Manage My Classes' buttons now take you straight to the right place in your member dashboard — before, they led to a dead page.",
            "Hosting classes is open to every member: there's no separate 'instructor' role anymore. Any member can create and manage a class or workshop — it still needs approval from the category's Guild Lead and an admin before it goes live. The teaching pages now live at a clearer /classes/teach address, and old links redirect there automatically.",
            "The top bar on the booking site is tidier for signed-in members — the link back to your FOG dashboard and your 'Member' badge are now properly styled and only appear where they're useful.",
            "Admins have a new site-wide Activity dashboard in the sidebar. One tab shows a chronological feed of what's happening across the site — logins, profile updates, votes, tab charges, class registrations, and more. A second tab logs every automatic email the site sends (receipts, class confirmations, invites) so you can confirm exactly what went out and catch anything that failed.",
        ],
    },
    {
        "version": "2.4.0",
        "date": "2026-06-08",
        "title": "Old-CMS classes import and sync automatically every day",
        "changes": [
            "The class catalog and Community Calendar now refresh themselves automatically every morning. New workshops imported from the old class site (classes.pastlives.space) and any updated guild calendars show up on their own — nobody has to open the calendar or press a button to pull them in. The 'Sync Now' buttons in Site Settings are still there whenever you want an instant refresh.",
        ],
    },
    {
        "version": "2.3.2",
        "date": "2026-06-07",
        "title": "Booking site polish: upcoming-only listing, pagination, and cross-site login",
        "changes": [
            "The class list now only shows classes with upcoming sessions — past events no longer clutter the page.",
            "Classes are paginated 25 at a time, sorted by closest upcoming date first. A Previous/Next bar appears at the bottom when there's more than one page.",
            "The sticky category strip has been removed. A small arrow button appears in the bottom-right corner when you scroll down — click it to jump back to the top.",
            "If you're already logged into pastlives.space, visiting your account on book.pastlives.space will automatically sign you in without a second login prompt.",
            "The Past Lives logo in the top-left of the booking site now links to the class list instead of the main website.",
            "Class detail pages no longer show a blank instructor tile when the instructor isn't on record.",
            "Class descriptions now display with proper paragraph breaks instead of running together as a single block of text.",
        ],
    },
    {
        "version": "2.3.1",
        "date": "2026-06-06",
        "title": "Classes from the old CMS now show up on book.pastlives.space",
        "changes": [
            "All classes from classes.pastlives.space now automatically sync into book.pastlives.space every 15 minutes — flip the toggle in Site Settings → Legacy CMS to turn it on. When you're ready to manage classes exclusively here, just turn it off.",
            "Imported classes link to the right instructor automatically when the class title includes 'with [Instructor Name]'. Once linked, the connection is never overwritten by a re-sync so any manual adjustments stick.",
            "Hero images from the old CMS are served through a proxy so class cards look complete right away — run 'Download legacy images' when you're ready to move them into plfog's own storage.",
            "The Members admin table now shows how many classes each instructor is teaching, with a one-click link that filters the Classes table to just their classes.",
            "The Classes admin table now has an instructor dropdown filter so you can quickly see every class taught by a specific person.",
            "Site Settings has a new Legacy CMS tab with the sync toggle, a 'Sync Now' button for on-demand imports, and an instructor match table that shows how many of each instructor's classes were automatically linked by name.",
        ],
    },
    {
        "version": "2.3.0",
        "date": "2026-05-28",
        "title": "Classes CMS round 2: rebrand, waitlist, dual approval, activity feed, and more",
        "changes": [
            "The public Classes site at book.pastlives.space now matches the look of pastlives.space. The old blue Squarespace backdrop is gone, the whole portal uses the Past Lives palette, and there is a slim PAST LIVES header at the top with Home, Guilds, Membership, Classes, and Contact links so it feels like one site to your customers.",
            "Light theme is the default on book.pastlives.space. The dark/light toggle in the top bar still works on the member hub the same way it always has.",
            "Class detail pages are now full width with bigger, easier-to-read text (16px floor everywhere). New sections appear automatically when the class has them: a video block, gallery, schedule, materials and prereqs side by side, an instructor card, a guild card, a short FAQ, related classes, and a sticky booking card on the right that follows you as you scroll.",
            "Instructors can paste a YouTube link onto any class and it embeds right in the description. Works with watch links, youtu.be short links, embed URLs, and shorts.",
            "Each of the 14 guild categories has a small icon next to its name on the public list. Admins can swap any icon for a custom one from the category admin.",
            "All Classes page got a Filter button. Sort by category from a dropdown, then click Filter to pick instructors, set a price range, or show only classes with a member discount, free classes, or classes with upcoming sessions. The URL updates as you filter so you can share a link to exactly what you are looking at.",
            'Discount codes can now be made for a single class. Open Edit on any class and look at the new "Discount codes for this class" section. Codes you make here only work for that class. There is also an Auto-apply toggle, which drops the price for every registrant without them needing to type the code. Global codes still live on the Discount Codes tab and still require an admin to make.',
            "New approval flow for classes. When an instructor submits a class, it now goes to both an admin AND the Guild Lead of that class's guild (when one is set). Each reviewer gets an email with their own link so they can approve, request changes, or decline with notes. The instructor gets an email each step of the way: the class only goes live when every reviewer has approved. Requesting changes or declining bounces the class back to Draft so the instructor can edit and resubmit.",
            'Waitlists for sold-out classes. When a class is full the Register button changes to "Join the waitlist" and the registrant gets confirmation of their spot in line, no charge. When somebody cancels, we email the next person on the waitlist with a 24-hour window to register. Admins see the waitlist on each class\'s admin page.',
            "New Activity tab in the Classes admin area. Reverse chronological feed of everything that happens with classes: who created a class, who submitted it for review, who approved or requested changes, who registered, who got refunded, who joined the waitlist, when a discount code was used. Filter chips for Classes, Registrations, Waitlist, and Discount codes plus a search box for class title, name, or email.",
            "Fixed invisible text on the Register button and category chip on class detail pages in light theme.",
            "Community Calendar now uses the same clean background as the rest of the site — the old Squarespace backdrop image is gone.",
            "Registration form inputs and text are now readable in both light and dark mode. Dropdowns on the form also match the rest of the field styling.",
        ],
    },
    {
        "version": "2.2.2",
        "date": "2026-05-26",
        "title": "Image uploads work on the New Class form",
        "changes": [
            "The 'New Class' form now has the same hero image and gallery image upload experience as the edit form — drag-and-drop zone with instant preview instead of a plain file picker. Gallery images are uploaded when you hit Save.",
        ],
    },
    {
        "version": "2.2.1",
        "date": "2026-05-26",
        "title": "Students on class detail, dollar pricing, admin create form fix",
        "changes": [
            "The class detail page now shows all registered students right on the page. You can see who signed up, their email, payment status, and registration date without leaving the class. Cancelled or refunded registrations appear dimmed for reference.",
            "Admins can email students directly from the class detail page. Check the students you want to reach, click 'Email selected students', type your message, and send. Recipients are BCC'd so no one sees the others' emails, and every send is logged.",
            "Price fields on class forms now accept dollars (e.g. 80.00) instead of cents (e.g. 8000). Same for the fixed discount field on discount codes. Existing prices display correctly; nothing changes behind the scenes.",
            "Fixed the discount code list showing dollar amounts wrong (e.g. '$2000.00' instead of '$20.00').",
            "The 'New Class' form for admins now has the session calendar and gallery image section, matching the edit form.",
            "The 'View Publicly' button on the Classes page now opens book.pastlives.space in a new tab.",
        ],
    },
    {
        "version": "2.2.0",
        "date": "2026-05-25",
        "title": "Visual session calendar, AJAX images, admin polish",
        "changes": [
            "Instructors now schedule class sessions on a visual month-view calendar — click a day, pick a time and duration, done. No more fiddling with raw datetime fields. Sessions show as gold dots on the calendar and are listed below with times.",
            "Gallery images upload instantly without hitting Save. Drag and drop to reorder, inline alt text, one-click delete. Max 10 images, 3 MB each, auto-compressed.",
            "Hero image also uploads instantly via drag-and-drop — no more needing to save the whole form.",
            "Instructors get an email notification when someone registers for their class. Admins can subscribe to registration notifications via CLASS_ADMIN_NOTIFY_EMAILS.",
            "The registration detail page got a full redesign — all info at a glance in clean card sections.",
            "Fixed the admin registrations page showing payment amounts in cents instead of dollars ($7200 → $72.00). Stripe charges were always correct — display-only bug.",
            "Member pricing now says 'for PL members' on public class pages.",
            "Removed the 'Recurring pattern' and 'Requires model release' fields from class forms — they were confusing and unused.",
            "Fixed hero image stretching on the edit page preview.",
            "Fixed gallery hover-zoom distorting images that aren't 16:9.",
            "Registrant names are now clickable links in the admin registrations table.",
        ],
    },
    {
        "version": "2.1.0",
        "date": "2026-05-25",
        "title": "CMS polish: styled emails, admin consolidation, instructor registrations",
        "changes": [
            "Class confirmation and reminder emails now match the polished look of our login emails — dark card with gold accents, clear schedule and location details, and a big 'Manage Registration' button so you can view or cancel right from the email.",
            "Billing receipt emails got the same treatment — itemized charges in a clean card layout with a link to your Stripe receipt.",
            "All email links are now full clickable URLs instead of bare paths, so they work in every email client.",
            "The classes admin area is now one consolidated workspace — Settings and Registration Questions are tabs alongside Classes, Registrations, Instructors, Categories, and Discount Codes. No more hunting across separate pages.",
            "Instructors now see their registrations grouped by class. Each class section expands to show its registrants and has its own email compose tool, so you can quickly see who's signed up and message them without switching tabs.",
            "Registration Questions (the custom questions asked on every class sign-up) can now be managed from the classes admin tab instead of the Django admin.",
            "Fixed paid class registration not redirecting to Stripe checkout when submitting the registration form.",
            "Discount codes created by instructors now require admin approval before they can be used. Admins see an approve/unapprove toggle on each code.",
            "Every admin table (Classes, Registrations, Instructors, Categories, Discount Codes, Questions) now has a search bar, clickable sortable column headers, and pagination.",
        ],
    },
    {
        "version": "2.0.7",
        "date": "2026-05-23",
        "title": "Fix: production deploy blocked by migration conflict",
        "changes": [
            "Fixed a migration conflict that was preventing the app from starting on production. Two independent changes landed on the same migration number and Django refused to run until they were merged — no data was affected, the app just couldn't start.",
        ],
    },
    {
        "version": "2.0.6",
        "date": "2026-05-23",
        "title": "Classes: smarter photos, newsletter tagging, custom questions, and instructor messaging",
        "changes": [
            "Class photos now auto-resize on upload — drop in a 4MB iPhone HEIC and we'll downscale and convert it to a clean web JPEG. The hero image gets a built-in crop tool: pick the 16:9 focal point and the public page crops to your selection.",
            "Newsletter tagging picks up more context. When someone registers for a class, their newsletter contact now gets tagged with the category, the instructor, the guild (if the category is linked to one), and 'first-time-student' if it's their first class with us.",
            "Categories can now be linked to a guild. Admins set the link from the category edit page, and it drives the new guild Mailchimp tag.",
            "When a member finishes onboarding on book.pastlives.space, their account is now synced to Mailchimp with their persona, referral source, and category interests as tags — so newsletter campaigns can target by 'how they found us' or 'what they're interested in', not just who's already registered for a class.",
            "Tour status from Simplybook is now pulled into member profiles. The account overview and instructor roster can show whether a member has completed a tour, refreshed at most once a day per member.",
            "You can now set up global registration questions that get asked on every class registration. Admins manage the list from the Django admin — short text, paragraph, yes/no, or pick-one — and instructors see the answers next to each registrant on their registrations page.",
            "Instructors can now email their students directly from the registrations page. Tick the rows you want to message, type a subject and body, and send. Recipients are BCC'd so no one sees the others' addresses, and every send is logged for the audit trail.",
        ],
    },
    {
        "version": "2.0.5",
        "date": "2026-05-22",
        "title": "Classes: multi-image galleries with hover-zoom + a preview button",
        "changes": [
            "When you create or edit a class, you can now upload extra gallery photos in addition to the hero banner — finished pieces, the studio space, tool close-ups, anything that helps a visitor picture the workshop. Each photo gets an optional alt-text field and a sort number so you can put them in the order you want.",
            "Picking a new image instantly shows a thumbnail in the form so you can tell which file you grabbed before saving.",
            "On the public class page, the hero now leads a real gallery — thumbnails along the bottom, hover anywhere on the main image to magnify a close-up of that spot (great for showing detail on glasswork, ceramics, fiber pieces), and click to open a full-screen lightbox with arrow-key navigation.",
            "A new 'Preview' button on the class form opens the public class page in a new tab — instructors and admins can see exactly how the page will look to visitors before submitting for review or publishing, including drafts.",
            "The hero image field now has a small '?' tooltip showing the recommended dimensions (1600 × 900, 16:9) and max file size so you know what to aim for before uploading.",
        ],
    },
    {
        "version": "2.0.4",
        "date": "2026-05-22",
        "title": "book.pastlives.space: an obvious way to sign up",
        "changes": [
            "The public site at book.pastlives.space now has a 'Sign up' button right in the navbar next to 'Log in' — new visitors don't have to know to click through Log in to find the signup link anymore.",
            "Signing up on book.pastlives.space is always open, regardless of the invite-only setting in Site Settings. The invite-only gate was meant for makerspace membership signups on members.pastlives.space — it shouldn't be blocking someone from making a book account just to track their class registrations.",
        ],
    },
    {
        "version": "2.0.3",
        "date": "2026-05-22",
        "title": "Site Settings: add multiple calendars to the Community Calendar",
        "changes": [
            "Site Settings now has its own Calendar tab with a list of named calendar feeds — General, Workshops, Open Studio, anything you want. Click '+ Add calendar' to drop in another iCal URL, give it a name and a color, and it shows up on the Community Calendar legend with its own colored chips.",
            "The Site Settings page is now organized into two tabs (General and Calendar) so finding registration, MailChimp, and analytics settings stays out of the way when you're just managing calendars.",
            "Existing General Calendar setups were automatically migrated into the new list as a 'General Calendar' feed — nothing to do, no events go missing.",
        ],
    },
    {
        "version": "2.0.2",
        "date": "2026-05-22",
        "title": "Delete classes outright, and a $1 minimum on paid classes",
        "changes": [
            "Admins can now delete any class that has no registrations — not just drafts. The Delete button shows up on the class detail page next to Archive whenever no one has signed up yet. Classes with registrations still have to be archived so we keep the history.",
            "When you set a price on a class, the minimum is now $1.00. Anything cheaper should just be a free class — tick 'This is a free class / workshop' and the price goes to zero. (This only affects new prices you set going forward; classes that were already priced below a dollar still work.)",
        ],
    },
    {
        "version": "2.0.1",
        "date": "2026-05-22",
        "title": "Class registration: friendlier error when a price comes out too low",
        "changes": [
            "Fixed a bug where the 'Continue to payment' button on a class registration page could show an error screen if the total ended up less than $0.50 (for example after applying a big discount code). You'll now see a clear message asking you to remove the code or get in touch with the studio.",
        ],
    },
    {
        "version": "2.0.0",
        "date": "2026-05-22",
        "title": "Classes & workshops are now open to everyone at book.pastlives.space",
        "changes": [
            "We launched a brand new public site at book.pastlives.space — anyone can browse our classes and workshops, sign up, and pay, no Past Lives account required. Send the link to friends, family, or anyone curious about taking a class with us.",
            "Members: nothing changes for you. Classes still live in the sidebar at /classes/ inside your hub, the member discount still applies automatically, and your dashboard looks exactly the same as it did yesterday.",
            "One login, two doors — if you're signed in on members.pastlives.space and you wander over to book.pastlives.space, we still recognize you and your member discount still applies. Handy for grabbing a link to share or showing a class to a non-member friend looking over your shoulder.",
            "Anyone who registers for a class can now create a free account and log in at book.pastlives.space to see their upcoming classes, past classes, receipts, and edit their contact info. No membership required — it's just a lightweight place for class takers to keep track of what they've booked.",
            "A short 3-step welcome runs the first time someone signs in at book.pastlives.space — it asks if they've ever taken a class with us before, collects a preferred name and a day-of contact phone, and lets them check off which kinds of classes they'd like to hear about. Every step is skippable, and we only email them about new classes in the categories they picked.",
            "Booked as a guest and forgot to make an account? There's a new 'Find my booking' page at book.pastlives.space/account/lookup/ — type in your last name and the confirmation order number from your email (the friendly PL-XXXX-YY one we now print at the top of every confirmation) and we'll pull up your booking. No password needed.",
            "Instructors can hop over to book.pastlives.space anytime to see classes they've personally signed up for as a student. A small link inside their account points back to their teaching dashboard on members.pastlives.space — that's still where class management happens.",
            "Registrations from both surfaces land in the same place — admins manage everything from one Classes admin in the members hub, so there's nothing new to learn and nothing to keep in sync.",
        ],
    },
    {
        "version": "1.9.1",
        "date": "2026-05-21",
        "title": "Stop login-page email spam from draining our daily quota",
        "changes": [
            "The login page now has a few new defenses against the bot that's been hammering it the last couple of days. The form looked too easy to spam, which is why our daily email quota was getting maxed out: every random email someone typed in (real or not) triggered an outgoing email, and Resend has a daily cap.",
            "Random emails no longer trigger an outgoing 'no account found' message. After you submit the login form, the page now says 'If you are a member at Past Lives, we sent a sign-in code to ...' — that wording is intentional. It doesn't confirm or deny whether the email is on file, which protects member privacy and also stops bots from using the form to enumerate real addresses. Nothing actually gets emailed unless the address matches a member.",
            "Tighter rate limiting on the login page: at most 5 requests per minute from any one device, and at most 3 codes per hour to the same email address. Repeated submissions beyond that quietly drop instead of sending.",
            "Added an invisible 'honeypot' field that real browsers ignore but most bots dutifully fill in. If it comes back filled, the request is treated the same as if the user had been rate-limited.",
            "Hard daily and hourly caps on total login emails (configurable, defaulting to 100/hour and 500/day) as a last-resort safety net. If anything ever slips past the other defenses, the site will stop sending login emails before the bill runs over instead of after.",
        ],
    },
    {
        "version": "1.9.0",
        "date": "2026-05-05",
        "title": "Mailchimp signup + site-wide Google Analytics",
        "changes": [
            "Class registration now has an opt-in checkbox — tick it and you'll start getting our newsletter about future classes, events, and what's happening at Past Lives. Leave it unchecked and nothing changes.",
            "Brand new Newsletter page at /newsletter/ — anyone (members or not) can drop their email in to get our updates, no account required.",
            "Site Settings now has working MailChimp credentials — paste in the API key and audience ID and the signup paths above start sending people to the right list, tagged so we can tell who came from a class versus the standalone newsletter form.",
            "Google Analytics now tracks every page on the site instead of just the public Classes pages — set the GA4 ID once in Site Settings and every member page, every public page, every auth page reports back. The Django admin is excluded so we don't pollute analytics with internal traffic.",
        ],
    },
    {
        "version": "1.8.0",
        "date": "2026-05-01",
        "title": "Calendar QOL + a redesigned Profile page that lets you control what's public",
        "changes": [
            "The Calendar's month view used to show the calendar month you're in, which meant by the end of April you were staring at a near-empty grid. It now shows a rolling 4-week window starting from the current week, so you always see this week plus the next three. The Prev/Next arrows step the window forward or back by 4 weeks at a time.",
            "Event titles are now visible right on the calendar grid in both Week and Month views — no more guessing which colored dot is which event. Click any title and the page jumps to that event in the list below and gives it a quick highlight. If the event lives on a different page, the list auto-flips to that page first.",
            "Today's column on the calendar grid now has a thin red line across the top, and any event that's happening right now gets a red outline plus a pulsing 'Live now' pill on its card.",
            "Profile settings got a new design with per-field privacy controls. Next to each field — phone, email, Discord, pronouns, photo, about-me, etc. — there's a small Public/Hidden eye-icon toggle so you can decide exactly what other members see when they look you up. A live preview on the side shows your directory card update in real time as you flip toggles or type. A panel at the bottom lists everything that's never shown to other members (legal name, billing, emergency contact, internal notes) so there's no ambiguity.",
            "On mobile, the Feedback button used to live at the bottom of the sidebar where it could get cut off and was hard to find. There's now a yellow Feedback bubble pinned to the bottom-right corner of every page on mobile so it's one tap away. The mobile sidebar also handles short screens better and respects the device's safe area.",
        ],
    },
    {
        "version": "1.7.5.2",
        "date": "2026-04-27",
        "title": "Hotfix: site layout broken for everyone",
        "changes": [
            "Fixed a bug introduced in the last release where the entire site rendered at half-width with a stray line of text near the top — the page was unusable. Everything looks correct again.",
        ],
    },
    {
        "version": "1.7.6",
        "date": "2026-04-26",
        "title": "Free classes & workshops — and a fix for the Register page styling",
        "changes": [
            'When you create or edit a class, there\'s now a "This is a free class / workshop" checkbox right above the price field. Tick it and the class is free — members and visitors register without entering any payment info, and they get a confirmation email immediately.',
            'Free classes show as "Free" everywhere on the site (the class card, the detail page, and the registration summary) instead of a $0 price tag.',
            "Fixed a bug where the Register page on a class could load with no styling if you clicked through from another page in the same browser tab. The page now keeps its full styling no matter how you arrive at it.",
        ],
    },
    {
        "version": "1.7.5",
        "date": "2026-04-25",
        "title": "Members can sign up for classes online — plus a unified Classes page",
        "changes": [
            "You can now register for classes and workshops directly on the website. Click Register on any class page, fill out a short form, sign the liability waiver online, and pay with a card through Stripe — no more email back-and-forth.",
            "Members get the member discount applied automatically when the email on the form matches a verified member email.",
            "Free classes skip the payment step and confirm immediately — you'll get a confirmation email right away.",
            "Discount codes are honored on the registration form, and stack on top of the member discount.",
            "Every confirmed registrant gets a confirmation email with the schedule, location, and a personal link they can use to view or cancel their spot — no login needed.",
            "There's now a single Classes & Workshops page in the sidebar — the same page everyone sees, members and visitors alike. Admins and instructors get a Manage button right on that page that opens the classes admin (or the Teaching dashboard for instructors), so you don't lose anything, it's just one entry point instead of two.",
            'Fixed: a class you publish now shows up on the Classes & Workshops page right away, even before its sessions are scheduled — it appears with an "Upcoming dates TBA" note until you add dates.',
        ],
    },
    {
        "version": "1.7.4",
        "date": "2026-04-25",
        "title": "One unified view — Classes, Calendar, Payments, and admin all live in the FOG dashboard",
        "changes": [
            "The Classes page at /classes/ is now public for everyone — no admin toggle needed.",
            "Everything now lives inside the FOG dashboard with the same sidebar and topnav. No more bouncing into a different admin layout — Classes, Community Calendar, Payments, Reports, Manage Members, Site Settings, and the new Voting Dashboard all open in the hub.",
            "Admins see one sidebar with everything they need: Community Calendar, Manage Classes, Manage Members, Member Directory, My Tab, Payments, Reports, Site Settings, and Voting Dashboard.",
            'The "Viewing as" dropdown stays in the topbar so admins can preview the hub as a Member, Guild Officer, Instructor, or Guest without switching accounts.',
            'All instructors are members by default — the "Non-member Instructor" label is gone, instructors are just instructors.',
        ],
    },
    {
        "version": "1.7.3",
        "date": "2026-04-23",
        "title": "Classes: public portal, instructor dashboard, and calendar integration",
        "changes": [
            "Browse classes at a new public page at /classes/ — grouped by category with sticky filters, hero, and polished card grid; gated behind an admin toggle in Classes → Settings so it only goes live when you're ready",
            "Class detail and instructor profile pages with schedule, description, pricing, member discount, and links back to the portal",
            "New Teaching section in the hub sidebar for instructors — lets them see their classes, submit drafts for admin review, view their registrations, and edit their own profile (photo, bio, website, social handle)",
            "Classes admin gets a status filter (All / Draft / Pending / Published / Archived) with live counts and dims archived rows, plus a Delete button for drafts with zero registrations — Archive preserves history; Delete is only for cleanup",
            "Published local classes now show up on the Community Calendar alongside the external feed during the transition period",
            "Scheduled reminder email infrastructure in place — `manage.py send_class_reminders` emails confirmed registrants for sessions starting soon (reminder window configurable in Classes → Settings)",
            "Small admin polish: shortened URLs from /classes/admin/classes/ → /classes/admin/, 'View public portal' link in the Classes admin header, proper small red delete buttons with confirmation modals across Categories, Discount Codes, and Classes",
        ],
    },
    {
        "version": "1.7.2",
        "date": "2026-04-23",
        "title": "Fix: logout page styling",
        "changes": [
            "Fixed the logout confirmation page so it uses the normal Past Lives site styling instead of showing an unstyled default page",
        ],
    },
    {
        "version": "1.7.1",
        "date": "2026-04-21",
        "title": "Photos for member profiles, guild banners, and classes",
        "changes": [
            "You can now upload a profile photo on your User Settings → Profile page — your photo replaces your initials in the member directory and in the top-right of the navbar",
            "Guild leads can add a banner image to their guild's page — it appears at the top of the guild detail page above the name and About section, with a tooltip explaining the recommended dimensions",
            "Class images (categories, instructors, and individual classes) and other photos uploaded through the admin now stay around between deploys instead of disappearing",
            "Image uploads have a 5 MB limit so things stay snappy and don't blow up our storage bill",
            "Replacing or removing a photo now also deletes the old file from storage so we don't accumulate orphaned images over time",
            "Friendlier image-upload UI everywhere — the small 'Currently / Clear checkbox' has been replaced with a thumbnail preview and a small red 'Remove' (or 'Delete photo') button that asks for confirmation before deleting",
        ],
    },
    {
        "version": "1.7.0.2",
        "date": "2026-04-21",
        "title": "Hotfix: deploy failing on Render",
        "changes": [
            "Fixed a deploy failure that was blocking new releases from going live on Render — the build step that packages up static files was being rejected because it couldn't see the production database settings. It now uses a harmless placeholder just for that build step, so deploys go through again",
        ],
    },
    {
        "version": "1.7.0.1",
        "date": "2026-04-21",
        "title": "Classes: admin tabs foundation",
        "changes": [
            "New Classes admin area (admins only) with six tabs — Classes, Categories, Instructors, Registrations, Discount Codes, and Settings — so we can build out the makerspace's class catalog natively inside Past Lives without needing the old booking site",
            "Admins can create categories, invite instructors (who get their own login), build classes with a full set of fields (prerequisites, materials, capacity, member discount, scheduling), and manage discount codes — the public registration flow + Stripe payments come in a follow-up release",
            'Instructors now exist as a first-class role: someone can be a member, an instructor, or both. The "Viewing as" dropdown recognizes the new role so admins can preview what teachers see',
            "Class titles and category names auto-fill the URL slug as you type — saves a step every time you make a new one",
        ],
    },
    {
        "version": "1.6.3",
        "date": "2026-04-17",
        "title": "Admin role preview in the hub",
        "changes": [
            'Admins and guild officers now have a new "Viewing as" button in the topbar — use it to preview the hub the way a plain member or guild officer would see it, without logging out. Unchecking a role hides that role\'s UI for the current session only.',
        ],
    },
    {
        "version": "1.6.2",
        "date": "2026-04-15",
        "title": "Fix: login page CSS broken after navigating from the hub",
        "changes": [
            "Fixed a bug where navigating to a protected page with an expired session would redirect you to the login page with completely broken styles — it now does a proper full-page load so the login page looks correct",
        ],
    },
    {
        "version": "1.6.1",
        "date": "2026-04-15",
        "title": "Calendar: Classes sync, configurable colors & pagination",
        "changes": [
            "Classes from classes.pastlives.space now show up on the Community Calendar — click the title to go straight to the registration page",
            "Classes have their own color on the calendar, separate from General events — customize it in Site Settings",
            "The event list now shows 10 events per page with prev/next arrows so the page doesn't get overwhelmed",
            "Admins can configure the Classes color in Site Settings → Community Calendar alongside the existing General color",
        ],
    },
    {
        "version": "1.6.0",
        "date": "2026-04-15",
        "title": "Community Calendar",
        "changes": [
            "New Community Calendar — see all upcoming makerspace events in one place, with week and month views so you can plan ahead",
            "Filter events by guild to find workshops, meetups, and events from just the guilds you care about",
            "Export any event to your personal calendar app (Google, Apple, Outlook — whatever you use) with one click",
            "Guild officers can now link their guild's Google Calendar so events sync automatically — no more posting events in two places",
        ],
    },
    {
        "version": "1.5.7",
        "date": "2026-04-15",
        "title": "Current Vote Standings — real totals",
        "changes": [
            "Current Vote Standings now show the real point totals — a guild that picked up votes at multiple ranks (say, one 1st, two 2nds, and three 3rds) was being displayed with those counts multiplied together instead of added, so some guilds were appearing at 60 points when the actual total was 17. Fixed on the Guild Voting page and the admin dashboard",
        ],
    },
    {
        "version": "1.5.6",
        "date": "2026-04-15",
        "title": "Voting hotfixes, User Settings, and sidebar polish",
        "changes": [
            "The Guild Voting page is now split into three tabs: Current Standings (live points), New Votes This Month (only votes cast or changed since the last snapshot), and Last Month's Results (the most recent snapshot with funding breakdown)",
            "Your vote still rolls over automatically every cycle — once you've submitted it, it stays in place and keeps counting until you change it",
            "The admin Voting Preferences page now shows a per-member voting history pulled from past snapshots, so you can audit how anyone's picks contributed to the totals cycle by cycle",
            "New unified User Settings page at /settings/ with Profile and Emails tabs — the old Manage Email Addresses page that looked like the login screen is gone, and adding/removing/verifying emails now happens inside the hub layout",
            "On the Emails tab, Manage Email Addresses and Email Preferences are now two separate cards, and the Re-send Verification button only appears when the selected email isn't verified yet",
            "The user menu in the top-right is now just Settings + Log Out — everything else lives inside the new User Settings page",
            "Resources links (Member Guide + Code of Conduct) and Feedback now live together in the bottom of the left sidebar, each styled consistently with the rest of the nav — no more floating button overlapping other content",
            "Fixed a Postgres error that was blocking the last deploy on Render — the migration that clears legacy product data and drops old columns now commits its cleanup before altering the schema, so the two steps can't collide in a single transaction",
        ],
    },
    {
        "version": "1.5.5",
        "date": "2026-04-14",
        "title": "Edit products in place",
        "changes": [
            "You can now edit a product right from your guild page — click the small pencil on a product card and the same pop-up you use to add products opens up pre-filled with that product's name, price, and revenue split",
            "Saving updates the product in place — no need to delete and re-add it just to fix a typo or change the percentages",
            "Product cards are cleaner — the 'Admin 20% · Guild 80%' split summary is hidden now that you can see and edit the same info from the product's edit pop-up",
        ],
    },
    {
        "version": "1.5.4",
        "date": "2026-04-14",
        "title": "Edit Your Guild Page Directly",
        "changes": [
            "Guild leads can now edit their guild's page without going through the admin — just open your guild page and you'll see an 'Edit Guild Page' button next to the title and an 'Add Product' button in the Products section",
            "Admins and guild officers see the same edit buttons on every guild page",
            "Changing the guild name or description happens right in a pop-up window on the guild page",
            "Adding a new product now opens a pop-up with the revenue-split builder instead of sending you to the admin panel — closing and re-opening the pop-up resets it cleanly",
            "Existing products show a small delete button in the corner so you can remove them without leaving the page",
            "The old 'Guilds' entry in the admin panel is gone — everything guild-related lives on the public guild pages now",
            "My Tab page now has a hoverable '?' next to the title that explains how tabs work, and the next-charge date shows as subtext below the heading instead of buried in the middle of the card",
            "Small copy fix on guild pages so the payment-method prompt reads 'add items to your tab' instead of just 'add items'",
            "Sidebar 'Guilds' section starts expanded by default, and remembers your preference if you collapse it",
        ],
    },
    {
        "version": "1.5.3",
        "date": "2026-04-14",
        "title": "Flexible Product Revenue Splits",
        "changes": [
            "Products can now split revenue across multiple guilds and admin in any combination — for example, a $10 product can be set up so 20% goes to admin, 60% to the Ceramics Guild, and 20% to the Art Framing Guild",
            "The percentages have to add up to 100%, but otherwise you can mix recipients however you like",
            "The Add Product form has been redesigned: it now appears inline on the guild edit page (no more popup) with a live preview that shows exactly how a sale will be divided up",
            "The 'active/inactive' toggle is gone — if a product exists, it's available; if you delete it, it's gone",
            "Existing products and past tab entries were cleared during this upgrade — you'll need to re-add your products with their new split configuration",
        ],
    },
    {
        "version": "1.5.2",
        "date": "2026-04-14",
        "title": "Local Dev Setup & Cart Toast Fix",
        "changes": [
            "New developer setup: clone the repo, run make setup, make db-up, make server — and you're running locally with PostgreSQL",
            "New 'make db-pull-prod' command downloads a copy of the production database for local testing",
            "Login codes now appear directly on screen during local development — no more checking the terminal",
            "The 'added to cart' notification now appears in the center of the screen instead of covering the tab balance",
        ],
    },
    {
        "version": "1.5.1",
        "date": "2026-04-13",
        "title": "My Tab & Guild Page Hotfixes",
        "changes": [
            "My Tab page redesigned: Current Balance and Pending Charges are combined into one card, and Payment Method now lives at the bottom",
            "My Tab page now shows your saved card with a link to add, replace, or remove it",
            "My Tab page tells you when your tab will be processed by Stripe so there are no surprises",
            "Removing a pending charge from your tab is now a one-click trash button — no confirmation dialog",
            "Removed the 'Add to Tab' form from the My Tab page — add items from guild pages instead",
            "Guild pages now have a 'General Consumables' card with a quantity picker so you can add custom-priced items directly to your tab",
            "Fixed a bug where one action would show two toast notifications at once",
            "Cleaner spacing between cards on the My Tab page and the payment-method setup page",
        ],
    },
    {
        "version": "1.5.0",
        "date": "2026-04-11",
        "title": "Single Stripe Account, Revenue Splits & Reports",
        "changes": [
            "Billing now runs through a single Past Lives Stripe account — each guild no longer links its own account separately",
            "Every charge has a configurable admin/guild percentage split (20% / 80% by default) — set site-wide or per-product",
            "New 'split equally across all guilds' option on any product or custom charge — the guild share gets divided evenly between active guilds",
            "New 'Enter Your Own Price' form on every guild page — add a custom-price item to your tab without an officer creating a product first",
            "Guild product cards now have an 'Add to tab' button so members can add items in one click from the guild page",
            "New admin Reports page (Payments → Reports) with date/guild/status filters and CSV export — shows exactly how much to pay each guild",
            "Product editor on the admin now includes admin % and split-mode controls for officers",
            "Saved card required again for tab entries (the direct-keys Checkout flow is gone)",
            "Cleanup: removed Stripe Connect OAuth flow, per-guild direct-keys management, and per-guild webhook endpoints — they're no longer needed",
        ],
    },
    {
        "version": "1.4.1",
        "date": "2026-04-11",
        "title": "Funding Results — Quieter Display & Admin Email Aliases",
        "changes": [
            "The funding results section no longer shows how many members contributed to each snapshot — keeping that detail private for now",
            "Admins can now add email aliases directly from the member page — handy for shared addresses like guild mailboxes where the member can't easily receive a verification code themselves",
            "Admins can also remove aliases, change which one is primary, and toggle whether an alias is marked verified",
            "Fixed a quiet bug where changing your primary email could silently revert on the next save — primary changes now stick",
        ],
    },
    {
        "version": "1.4.0",
        "date": "2026-04-11",
        "title": "Email Aliases & Smarter Funding Snapshots",
        "changes": [
            "New 'Manage email addresses' page in your profile menu — add, remove, verify, and set a primary email all in one place",
            "Sign in with any of your verified email addresses, not just the one you signed up with",
            "Cleaner admin: removed the confusing 'is primary' toggle on member email aliases",
            "Funding snapshots now have a $1,000 minimum pool so small-turnout months still allocate meaningful amounts to guilds",
            "New Snapshot Analyzer admin page — preview live vote results with filters by member type, role, and paying status before taking a snapshot",
            "Stored snapshots can be re-sliced with the same filters to see exactly who voted for what",
            "Admins can now delete a snapshot from the analyzer page",
            "Fixed: non-paying guild officers' votes are no longer silently zeroed out when the funding pool is calculated",
        ],
    },
    {
        "version": "1.3.2",
        "date": "2026-04-07",
        "title": "Pay-as-you-go Tabs, Guild Product Cards & Stripe in Settings",
        "changes": [
            "You no longer need to save a card before adding things to your tab — just add the item and pay later",
            "When you have charges ready to pay, a 'Pay Now' button appears on your Tab page that opens Stripe's secure checkout",
            "Money goes directly to the guild that owns the items you bought",
            "Guild pages now show products as cards instead of a table — easier to scan",
            "All Stripe configuration now lives in the admin Payments → Settings page — no more editing server environment variables",
            "Stripe Connect platform billing can now be enabled with a single toggle in Settings (for future membership and space-lease billing)",
        ],
    },
    {
        "version": "1.3.1",
        "date": "2026-04-07",
        "title": "Pay Guilds Directly for Consumables",
        "changes": [
            "Guilds can now connect their own Stripe account by pasting their API keys — no platform setup required",
            "Money for consumables (clay, materials, etc.) goes straight to the guild that owns the items",
            "Admins can test a guild's Stripe keys before saving to make sure everything is connected",
        ],
    },
    {
        "version": "1.3.0",
        "date": "2026-04-02",
        "title": "Tab Billing System",
        "changes": [
            "New tab system — charges accumulate on your tab and get billed on a schedule, just like a bar tab",
            "See your tab balance at a glance with the new balance pill in the top bar",
            "My Tab page shows your pending charges, tab limit, and remaining balance",
            "Tab History page shows all past charges with itemized details you can expand",
            "Add items to your own tab with the self-service form",
            "Set up a payment method securely through Stripe — your card info never touches our server",
            "Automated billing engine charges tabs on a configurable schedule (daily, weekly, or monthly)",
            "Failed charges automatically retry up to 3 times before locking the tab",
            "Email receipts after every successful charge with an itemized breakdown",
            "Guild Stripe accounts can be connected via Stripe Connect — each guild receives their share of charges directly",
            "Members can pick products when adding to their tab — price and description are filled in automatically",
            "Unified Payments admin — one page for outstanding tabs, charge history, billing settings, and Stripe accounts",
            "All financial records are preserved forever — entries are voided, never deleted",
            "Guild pages — each guild now has its own page with an about section and a list of products",
            "Guild leads can edit their guild's about text and manage their product listings directly from the guild page",
        ],
    },
    {
        "version": "1.2.1",
        "date": "2026-04-01",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar on mobile — it now slides open as a drawer with a dark backdrop you can tap to close",
            "Sidebar starts closed on mobile so you get the full screen for content",
            "Tapping a nav link on mobile automatically closes the sidebar",
        ],
    },
    {
        "version": "1.2.0",
        "date": "2026-03-30",
        "title": "Member Management Redesign",
        "changes": [
            "Admin Members page now lets you create users with a login right from the add form",
            "Added email aliases — members can have multiple email addresses and log in with any of them",
            "New 'Users' filter on the Members page to see who has logged into the app",
            "Search now finds members by their alias emails too",
            "Removed the separate User admin page — everything is managed through Members now",
        ],
    },
    {
        "version": "1.1.2",
        "date": "2026-03-30",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar menu button not working on Android phones — the side menu now opens and closes properly on mobile",
        ],
    },
    {
        "version": "1.1.1",
        "date": "2026-03-28",
        "title": "Better Discord Announcements",
        "changes": [
            "Discord now gets a friendly release announcement when updates go live — with version and what changed",
            "Removed noisy PR-opened notifications so the channel stays clean",
        ],
    },
    {
        "version": "1.1.0",
        "date": "2026-03-28",
        "title": "Vote Standings & Discord Notifications",
        "changes": [
            "Live vote standings with bar charts on the guild voting page — see who's leading in real time",
            "Admin voting dashboard now shows visual bar charts for vote leaders",
            "Discord notifications — the team gets pinged when PRs are opened or code is merged to main",
        ],
    },
    {
        "version": "1.0.3",
        "date": "2026-03-28",
        "title": "Login & Email Fixes",
        "changes": [
            "Members synced from Airtable can now log in immediately — no signup step needed",
            "All emails from Past Lives are now properly branded (no more 'example.com')",
            "Table columns in the admin panel are now left-aligned for easier reading",
        ],
    },
    {
        "version": "1.0.2",
        "date": "2026-03-28",
        "title": "Admin Fixes",
        "changes": [
            "Role management moved out of the member directory — it now lives in the admin panel only",
            "Login code entry allows up to 5 attempts before locking out (was 3)",
        ],
    },
    {
        "version": "1.0.1",
        "date": "2026-03-27",
        "title": "Hotfix",
        "changes": [
            "Guild vote history from before launch is now reflected in voting results",
            "Login code emails no longer show [example.com] in the subject line",
            "Login page email field now shows the correct placeholder",
        ],
    },
    {
        "version": "1.0.0",
        "date": "2026-03-27",
        "title": "Launch Day",
        "changes": [
            "Vote for your favorite guilds each month and see how funding gets split",
            "Your own member hub — one place for voting, directory, and settings",
            "Passwordless sign-in — just enter your email and we send you a code",
            "Member directory — find other members, see their bios and contact info",
            "Member roles — admins, guild officers, and regular members each see what they need",
            "Admins can invite new members, manage the roster, and take funding snapshots",
            "Send us feedback anytime from the Feedback button",
            "Works on your phone — install it like an app from your browser",
            "Forgot which email you signed up with? The new account finder has you covered",
        ],
    },
]
