# Generated by Django 6.0.2 on 2026-03-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0006_guild_cover_image_guild_description_guild_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakerClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maker_classes",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maker Class",
                "verbose_name_plural": "Maker Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maker_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="education.makerclass"
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Orientation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orientations",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orientation",
                "verbose_name_plural": "Orientations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledOrientation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("cancelled", "Cancelled"), ("completed", "Completed")],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_orientations",
                        to="education.orientation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Orientation",
                "verbose_name_plural": "Scheduled Orientations",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
