# Generated by Django 6.0.8 on 2026-10-08 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0215_member_teaching_inquiry_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="What members are asked, in plain words.",
                        max_length=200,
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(help_text="When members can start voting."),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        help_text="When voting ends. Close now sets it to the moment the admin closed it."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the poll was posted."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who posted the poll.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opens_at"],
            },
        ),
        migrations.CreateModel(
            name="PollChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="The answer as members see it.", max_length=120),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(help_text="Its place in the list, from 0."),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="The poll this answers.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["poll", "position"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the vote was cast."),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        help_text="The answer chosen.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.pollchoice",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Who voted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="membership.member",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="The poll voted in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["closes_at", "opens_at"], name="poll_window_idx"),
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                condition=models.Q(("closes_at__gte", models.F("opens_at"))),
                name="poll_closes_after_opens",
            ),
        ),
        migrations.AddConstraint(
            model_name="pollchoice",
            constraint=models.UniqueConstraint(fields=("poll", "position"), name="pollchoice_one_per_position"),
        ),
        migrations.AddConstraint(
            model_name="pollvote",
            constraint=models.UniqueConstraint(fields=("poll", "member"), name="pollvote_one_per_member"),
        ),
    ]
