# Generated by Django 6.0.8 on 2026-10-08 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0214_merge_0213"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClayOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name makers pick on the ticket form.",
                        max_length=80,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Ascending order on the form and the list."),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the crew took this off new tickets; blank while it is offered.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When it was added to the list."),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who archived it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlazeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name makers pick on the ticket form.",
                        max_length=80,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Ascending order on the form and the list."),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the crew took this off new tickets; blank while it is offered.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When it was added to the list."),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who archived it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KilnTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maker_type",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("student", "Student or guest"),
                            ("staff", "Guild staff"),
                        ],
                        default="member",
                        help_text="What the maker was when they last saved the ticket (a snapshot).",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "In the queue"),
                            ("loaded", "In the kiln"),
                            ("fired", "Ready for pickup"),
                        ],
                        default="draft",
                        help_text="Where the ticket is.",
                        max_length=20,
                    ),
                ),
                (
                    "firing_type",
                    models.CharField(
                        blank=True,
                        choices=[("bisque", "Bisque"), ("glaze", "Glaze")],
                        help_text="Bisque or glaze; blank on an early draft.",
                        max_length=10,
                    ),
                ),
                (
                    "height_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in inches.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "width_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in inches.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "length_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in inches.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Identical pieces on this ticket. Blank means one.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "clay_other",
                    models.BooleanField(
                        default=False,
                        help_text="The maker chose Other (specify) for the clay.",
                    ),
                ),
                (
                    "clay_other_name",
                    models.CharField(
                        blank=True,
                        help_text="The clay named under Other.",
                        max_length=120,
                    ),
                ),
                (
                    "clay_other_cone6",
                    models.BooleanField(
                        default=False,
                        help_text="The maker confirmed the Other clay can be fired to at least Cone 6.",
                    ),
                ),
                (
                    "walls_under_inch",
                    models.BooleanField(
                        blank=True,
                        help_text="Bisque: every wall is under 1 inch thick. Blank when unanswered.",
                        null=True,
                    ),
                ),
                (
                    "glaze_studio",
                    models.BooleanField(
                        default=False,
                        help_text="Glaze: a studio glaze is on the piece.",
                    ),
                ),
                (
                    "glaze_commercial",
                    models.BooleanField(
                        default=False,
                        help_text="Glaze: a commercial glaze is on the piece.",
                    ),
                ),
                (
                    "commercial_glaze_name",
                    models.CharField(
                        blank=True,
                        help_text="The commercial glaze's brand and name.",
                        max_length=200,
                    ),
                ),
                (
                    "glaze_self_made",
                    models.BooleanField(
                        default=False,
                        help_text="Glaze: a self made or other glaze is on the piece.",
                    ),
                ),
                (
                    "self_made_glaze_description",
                    models.CharField(
                        blank=True,
                        help_text="What the self made or other glaze is.",
                        max_length=300,
                    ),
                ),
                (
                    "bottom_free_of_glaze",
                    models.BooleanField(
                        blank=True,
                        help_text="Glaze: the bottom quarter inch is free of glaze. Blank when unanswered.",
                        null=True,
                    ),
                ),
                (
                    "stilts_added",
                    models.BooleanField(
                        blank=True,
                        help_text="Glaze with a glazed bottom: stilts or cookies protect the shelf.",
                        null=True,
                    ),
                ),
                (
                    "glaze_cone6",
                    models.BooleanField(
                        default=False,
                        help_text="The maker confirmed the clay and every glaze can be fired to at least Cone 6.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the ticket was started."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When the ticket was last saved."),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ticket first went in the queue.",
                        null=True,
                    ),
                ),
                (
                    "clay",
                    models.ForeignKey(
                        blank=True,
                        help_text="The studio clay, when the maker picked one from the list.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="kiln.clayoption",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        help_text="Who filed the ticket. Their name and contact are read from here, never typed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiln_tickets",
                        to="membership.member",
                    ),
                ),
                (
                    "studio_glazes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which studio glazes are on the piece.",
                        related_name="tickets",
                        to="kiln.glazeoption",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KilnFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("other_clay", "Other clay"),
                            ("commercial_glaze", "Commercial glaze"),
                            ("self_made_glaze", "Self made or other glaze"),
                            ("thick_walls", "Thick walls"),
                            ("glaze_on_bottom", "Glaze near the bottom"),
                            ("glaze_no_stilts", "Glaze on the bottom, no stilts"),
                            ("manual", "Added by the crew"),
                        ],
                        help_text="Why the ticket is flagged.",
                        max_length=30,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="The crew's note on a flag they added by hand.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the flag was raised."),
                ),
                (
                    "cleared_at",
                    models.DateTimeField(blank=True, help_text="When the crew cleared it.", null=True),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The crew member who added the flag; blank for an automatic flag.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who cleared it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="The flagged ticket.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="kiln.kilnticket",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="KilnTicketPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The photo, resized for the detail page.",
                        upload_to="kiln/photos/",
                    ),
                ),
                (
                    "tile",
                    models.ImageField(
                        help_text="A small copy for rows and tiles.",
                        upload_to="kiln/tiles/",
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False,
                        help_text="The photo the crew finds the piece by.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Order in the gallery."),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the photo was added."),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="The ticket this photo shows.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="kiln.kilnticket",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="clayoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("name",),
                name="uq_kiln_clay_active_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazeoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("name",),
                name="uq_kiln_glaze_active_name",
            ),
        ),
        migrations.AddIndex(
            model_name="kilnticket",
            index=models.Index(fields=["maker", "status"], name="kiln_ticket_maker_status"),
        ),
        migrations.AddConstraint(
            model_name="kilnflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "manual"), _negated=True),
                fields=("ticket", "kind"),
                name="uq_kiln_flag_auto_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="kilnticketphoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("ticket",),
                name="uq_kiln_photo_one_cover",
            ),
        ),
    ]
