# Generated by Django 6.0.8 on 2026-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiln", "0002_seed_clay_and_glaze_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="kilnflag",
            name="answer",
            field=models.CharField(
                blank=True,
                help_text="The answer that raised an automatic flag. When the maker changes it, a cleared flag opens again.",
                max_length=300,
            ),
        ),
    ]
