# Generated by Django 6.0.8 on 2026-10-08 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiln", "0003_kilnflag_answer"),
        ("membership", "0215_member_teaching_inquiry_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="KilnFiring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firing_type",
                    models.CharField(
                        choices=[("bisque", "Bisque"), ("glaze", "Glaze")],
                        help_text="Bisque or glaze; every ticket in it matches.",
                        max_length=10,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="The firing's number, one sequence across bisque and glaze.",
                        unique=True,
                    ),
                ),
                (
                    "loaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the load was confirmed.",
                    ),
                ),
                (
                    "loaded_by",
                    models.ForeignKey(
                        help_text="The crew member who confirmed the load.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="kilnticket",
            name="firing",
            field=models.ForeignKey(
                blank=True,
                help_text="The firing the crew loaded this piece into; blank until it is loaded.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="kiln.kilnfiring",
            ),
        ),
        migrations.CreateModel(
            name="KilnReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="The message.")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When it was sent."),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Who wrote it: the maker or a crew member.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiln_replies",
                        to="membership.member",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="The ticket this message is on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="kiln.kilnticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
