# Generated by Django 6.0.8 on 2026-10-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiln", "0004_firings_and_replies"),
        ("membership", "0215_member_teaching_inquiry_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="kilnfiring",
            name="unloaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When it was unloaded; blank while it is in the kiln.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kilnfiring",
            name="unloaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The crew member who unloaded it and told the makers; blank while it is in the kiln.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="kilnreply",
            name="firing",
            field=models.ForeignKey(
                blank=True,
                help_text="The firing being unloaded when the crew wrote this note; blank for an ordinary message.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exceptions",
                to="kiln.kilnfiring",
            ),
        ),
        migrations.AddField(
            model_name="kilnreply",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fired", "Fired, with this note"),
                    ("back_to_queue", "Back to the queue"),
                ],
                help_text="Whether the piece was fired anyway or went back to the queue; blank for an ordinary message.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kilnreply",
            name="what_happened",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cracked", "Cracked"),
                    ("glaze_ran", "Glaze ran"),
                    ("stuck", "Stuck to the shelf"),
                    ("other", "Something else"),
                ],
                help_text="What went wrong with the piece at the unload; blank for an ordinary message.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kilnticket",
            name="fired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the crew unloaded it and marked it Ready for pickup.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="kilnreply",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("firing__isnull", True), ("outcome", ""), ("what_happened", "")),
                    models.Q(
                        ("firing__isnull", False),
                        models.Q(("what_happened", ""), _negated=True),
                        models.Q(("outcome", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_kiln_reply_unload_note",
            ),
        ),
    ]
